### ISSUE TITLE
People: Option to select main picture for person on "People's" page

### ISSUE THREAD

**Issue by JaswinderJohal** [photoprism/photoprism#2731] opened 2022-09-22 14:32 UTC
There should be an option to select which picture should be used as a main thumbnail for persons face on "People" page. Issue i am running into is it recognized different person as one of the person on my list. I want and edited the person tag to change. But now in peoples page it still shows wrong persons picture in thumbnail and i have no way to edit it.

**Comment by graciousgrey** [comment] 2022-09-22 16:02
Duplicate of https://github.com/photoprism/photoprism/issues/383. 

> But now in peoples page it still shows wrong persons picture in thumbnail and i have no way to edit it.

The cover image should be updated automatically after some time in case you changed the person assignment of the face on the cover image

**Closed as completed** 2022-09-22 16:02 UTC
Labels: duplicate
