### ISSUE TITLE
Bulk edit for metadata

### ISSUE THREAD

**Issue by mariomare22** [photoprism/photoprism#329] opened 2020-05-22 11:13 UTC
Hi Team,

I am uploading my library to Photoprism running on docker.
since the photos are taken with an old reflex is there a way to "Bulk Edit" metadata for more items? (Location, etc)?

**Comment by ravetam** [comment] 2020-05-22 11:20
Still ongoing i believe
#271

**Comment by lastzero** [comment] 2020-05-22 13:48
Yes, it's on our todo, but I'm currently working on albums, not editing. We'll probably release afterwards and do bulk edit later.

**Comment by lastzero** [comment] 2020-05-26 11:51
I'll close this as a duplicate of #271.

**Closed by lastzero** 2020-05-26 11:51 UTC
