### ISSUE TITLE
Container not starting up after June 3, 2023 upgrade

### ISSUE THREAD

**Issue by yieldhog** [photoprism/photoprism#3446] opened 2023-06-03 16:34 UTC
#### 1. What is not working as documented?

PhotoPrism docker no longer starting -- throws off the following error:

[mysql] 2023/06/03 16:26:09 packets.go:36: unexpected EOF
--
Upgraded to latest version (June 3, 2023) no other changes made

#### 2. How can we reproduce it?

Starting container

#### 3. What behavior do you expect?

Start-up

#### 4. What could be the cause of your problem?

Upgraded to [230603-378d4746a](https://github.com/photoprism/photoprism/releases/tag/230603-378d4746a)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: [230603-378d4746a](https://github.com/photoprism/photoprism/releases/tag/230603-378d4746a)

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Synology

(d) Browser Types & Versions: Safari

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? na

#### 7. On what kind of device is PhotoPrism installed?

Synology NAS

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

na

**Comment by lastzero** [comment] 2023-06-03 16:36
Using MariaDB 11? What Docker image - or self compiled?

**Comment by lastzero** [comment] 2023-06-03 16:40
I'm asking because the builds are still running, at least if you're using the "latest" tag:
https://hub.docker.com/r/photoprism/photoprism/tags

**Comment by lastzero** [comment] 2023-06-03 17:02
No one has reported any problems with the preview build. I just built a new version and none of our own instances fail to start. Others who reported the error message you see had problems with MariaDB, e.g. because they accidentally upgraded it as well and the new version failed to start (see our release notes for a possible solution):

- https://docs.photoprism.app/release-notes/#june-3-2023

If you have a different problem, our troubleshooting checklists may help as well::

- https://docs.photoprism.app/getting-started/troubleshooting/mariadb/

I'll close this for now, since we can't reproduce the problem. If you think it is an actual bug in our software and not a local configuration issue, feel free to provide further details so we can reproduce it.

**Closed as completed by lastzero** 2023-06-03 17:02 UTC
Labels: question

**Comment by yieldhog** [comment] 2023-06-03 17:14
Appears to have been an issue w/ a recent upgrade of Mariadb on my end, ignore. Thank you

**Comment by lastzero** [comment] 2023-06-03 17:19
Thanks for the update! Glad you could figure it out.
