### ISSUE TITLE
Backend: MySQL deadlocks when indexing large photo collections

### ISSUE THREAD

**Issue by jamesemoody** [photoprism/photoprism#357] opened 2020-06-10 19:41 UTC
Photoprism 0610 in docker.
Mysql 8.0.20 in docker.
workers = 3

With workers = 3, when scanning/indexing, I get a periodic:
`index: Error 1213: Deadlock found when trying to get lock; try restarting transaction for IMG_0123.JPG`
In itself this feels like a normal thing in a parallel system, but photoprism does not seem to retry the transaction, and as a result _a number of photos do not appear in the `files` table in mysql_ after the scan is complete.

Reducing workers to 1 fixes this, but it would be nice to have multiple workers when I run a long import over many thousands of photos.

**Comment by jamesemoody** [comment] 2020-06-10 23:30
Cool, workaround is great for me. Not urgent, just thought you'd want to know.

**Comment by lastzero** [comment] 2020-06-23 09:43
This is related to MariaDB config options I added to fix an issue with our indexer (it stopped and didn't continue, so it looked like it is waiting for the database to do something):

```
--innodb-rollback-on-timeout=ON --innodb-lock-wait-timeout=120
```

See example `docker-compose.yml` file:

https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/docker-compose.yml

Maybe we have to revert it and use `--innodb-rollback-on-timeout=OFF` instead, not 100% sure what side effects this has... deadlocks are worse than a rollback.

**We'd be happy to accept advice and pull requests from our community if someone is experienced with this.** If not, I'll do it as soon as I have time for reading all related manuals and perform tests with different options. Takes a while since it typically only happens when indexing many files (>10.000) on a CPU with at least 3 cores (more is better for testing).

**Comment by lastzero** [comment] 2020-07-01 17:01
Reverted **mysqld** settings back to `--innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50` (default).

Docs: https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_rollback_on_timeout

Not sure if this helps. As this is not an accounting / business application, we don't really use transactions. Just implicitly on the InnoDB row level, not sure what [GORM](https://gorm.io/) does internally.

IMO this should not be handled in our application code if that means implementing retry loops for every single statement. Open to suggestions.

**Comment by wiwie** [comment] 2020-07-01 19:58
I am experiencing this issue as well.

It's weird though, that this error occurs if you are not really using transactions except the ones on row level.


I don't think that these mysql/mariadb settings are likely to solve the underlying problem.

These settings tell the DBMS how to distinguish between long running operations and deadlock situations. Setting the timeout setting to 50s means that if a locking operation is running longer than 50s it is to be considered abnormal and one or more operations are likely stuck in a deadlock (blocking each other as they are waiting for each others locked resources). The DBMS will then forcefully solve that deadlock by aborting some transactions.

In this case, I don't think the issue is caused by long-running transactions but rather by a real deadlock situation where two or more workers are waiting for each others locked resources. And that is because the index workers need much less time per photo than that timeout threshold - at least in my case each picture takes only few seconds. Hence, I'd think that it is indeed deadlocks that are occurring due to code design.

But if you are really not using transactions except the row level ones, the only thing I can think of that could cause a deadlock would be if you had update/delete statements [that affect the same rows but in different order](https://stackoverflow.com/a/2423921/1744922).

**Comment by lastzero** [comment] 2020-07-01 20:07
Certain GORM functions like Save() might use transactions, but not our own application code.

**Comment by wiwie** [comment] 2020-07-01 20:46
Just had a look at index_worker.go .

Using a channel for the jobs makes sure that not two workers process the same file. But what about the related files? Could it be that to workers process the same related file and try updating its row simultaneously?

**Comment by lastzero** [comment] 2020-07-01 20:49
They should not, related files are grouped together.

**Comment by wiwie** [comment] 2020-07-01 21:00
So no file can be a related file to multiple files?

**Comment by lastzero** [comment] 2020-07-01 21:02
It should not, except it's a duplicate with a different name. In that case, it may get indexed twice.

**Comment by lastzero** [comment] 2020-07-07 08:54
GORM seems to make heavy use of blocking transactions when saving & updating associations automatically. Refactored some of it, situation much better now although not 100% resolved. Trying to fix more today.

**Comment by lastzero** [comment] 2020-07-07 16:35
Might be a bit early to tell, but it looks very much like all database errors are gone using the latest Docker image... You're welcome to help testing (again)!

**Comment by lastzero** [comment] 2020-07-07 16:51
Same issue exists for labels, but should be easy to fix using the same (ugly) Find > Create > Find strategy:

![Screenshot 2020-07-07 at 18 49 06](https://user-images.githubusercontent.com/301686/86815103-91a4ce80-c082-11ea-83a6-9d14190e7d63.png)

**Comment by lastzero** [comment] 2020-07-08 20:04
Closing this... We can open a new issue when somebody happens to find a related error.

**Closed by lastzero** 2020-07-08 20:04 UTC
Labels: bug, help wanted, important, please-test

**Comment by jamesemoody** [comment] 2020-07-09 19:43
Thanks! This weekend I'll try to find time to do a bulk reindex of a large folder - that triggered it pretty reliably for me with 3 workers.

**Comment by lastzero** [comment] 2020-07-09 19:46
Not sure what strategy is ultimately best, but it should work like that. Indexed 100,000 files without issues.
