### ISSUE TITLE
Filename with brackets not supported

### ISSUE THREAD

**Issue by scilaci** [photoprism/photoprism#131] opened 2019-08-18 18:52 UTC
Hi guys,

I found a bug blocking the indexation process :'(

How to reproduce :

Rename the filename of a picture and use the brackets in the name:
- Ex: pictureFilename[1].jpg
 

Move the file in the Originals folder and try to reindex 

The indexation process is stopped by this error:

> photoprism_1  | time="2019-08-18T18:22:25Z" level=info msg="updated main jpg file \"2019/08/20190815_002342_D41083B2B2C2.jpg\""
photoprism_1  | [GIN] 2019/08/18 - 18:22:25 | 500 |  7.230782403s |    192.168.1.40 | POST     /api/v1/index
photoprism_1  | time="2019-08-18T18:22:25Z" level=info msg="/home/photoprism/Pictures/Originals/P1090443[1].jpg"
photoprism_1  |
photoprism_1  |
photoprism_1  | 2019/08/18 18:22:25 [Recovery] 2019/08/18 - 18:22:25 panic recovered:
photoprism_1  | POST /api/v1/index HTTP/1.1
....
photoprism_1  |
photoprism_1  |
photoprism_1  | runtime error: invalid memory address or nil pointer dereference
photoprism_1  | /usr/local/go/src/runtime/panic.go:82 (0xcc3f50)
photoprism_1  | /usr/local/go/src/runtime/signal_unix.go:390 (0xcc3d7f)
photoprism_1  | /go/src/github.com/photoprism/photoprism/internal/photoprism/mediafile.go:372 (0x1c9f5b6)
photoprism_1  | /go/src/github.com/photoprism/photoprism/internal/photoprism/mediafile.go:372 (0x1c9f5b1)
photoprism_1  | /go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:111 (0x1c981e6)
photoprism_1  | /go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:359 (0x1c9cbc0)
photoprism_1  | /go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:397 (0x1cadbcf)
photoprism_1  | /usr/local/go/src/path/filepath/path.go:358 (0xd90c25)

Is a big problem when you are trying to index 50k of pictures and be blocked by one of these pictrues!

If you are tying to upload the picture from the UI and importing...
=> The file is never moved to Original folder and without error in the logfile

**Comment by lastzero** [comment] 2019-08-18 19:22
Good catch! While in development, we fail fast... final release will catch the panic and continue.

**Comment by korimillivijay** [comment] 2019-08-20 23:18
I am able to reproduce the issue, can I take a look into this

**Comment by lastzero** [comment] 2019-08-22 19:39
@korimillivijay Thank you!

**Comment by lastzero** [comment] 2019-12-30 09:28
Can somebody confirm this is fixed?

**Comment by lastzero** [comment] 2020-01-06 10:24
I'll close this since we didn't get feedback and our code has improved a lot since the bug was reported. My test with brackets worked without issues.

**Closed by lastzero** 2020-01-06 10:24 UTC
Labels: bug, waiting
