### ISSUE TITLE
SQLite: Photos disappeared after upgrading to the latest development preview build

### ISSUE THREAD

**Issue by gomme600** [photoprism/photoprism#2216] opened 2022-04-01 10:53 UTC
**What does not work as described in the documentation?**

All of my photos have disappeared on the latest update.

**How can we reproduce it?**

Update the container to the latest version.

**What behavior do you expect?**

Photos to appear.

**Can you provide us with example files for testing, error logs, or screenshots?**

![Screenshot_20220401-124005](https://user-images.githubusercontent.com/35890638/161248817-88e1727d-b9e5-4775-bf99-9fa2a43ffb6f.jpg)
![Screenshot_20220401-124015](https://user-images.githubusercontent.com/35890638/161248831-5d989cb3-dee7-439c-b1fb-92a76da4fa6f.jpg)

![Screenshot_20220401-124245](https://user-images.githubusercontent.com/35890638/161248847-96035b6f-6831-43cb-ae12-816fb66c23ad.jpg) 

**Which software versions do you use?**

- PhotoPrism Architecture & Build Number (AMD64, ARM64, ARMv7,...) : Build 220331-342904a4-Linux-ARM64
- Database : Not sure, the default one I think (SQLite) as I don't have another docker image.
- Operating System Types & Versions (Linux, Windows, Android,...) : Linux (raspberry pi)
- Browser Types & Versions (Firefox, Chrome, Safari on iPhone,...) : Chrome (Android), Firefox
- Browser Plugins & Ad Blockers (if any) : None

**Comment by gomme600** [comment] 2022-04-01 11:00
Downgrading from the latest preview build to the latest arm64 build (docker tags) has restored my photos. This seems to confirm the bug in the latest preview build.

**Comment by lastzero** [comment] 2022-04-01 11:57
It seems that the database schema migrations were not performed (correctly). Note that MySQL 8 is no longer supported, just in case.

Did you see any warnings/errors when starting the container?

**Comment by lastzero** [comment] 2022-04-01 14:28
Our latest [development preview](https://docs.photoprism.app/release-notes/#development-preview) build `220401-a61470df` includes a new command that lists the status of database migrations.

**Could you please run this command for us and show the result?**

```bash
docker-compose exec photoprism photoprism migrations ls
```

To retry previously failed migrations, you can run this command next and let us know if you see any errors or warnings:

```bash
docker-compose exec photoprism photoprism migrations run --failed
```

If you are lucky, the problem is already solved with this...

**Comment by lastzero** [comment] 2022-04-01 14:59
Updated the migration statements to match the queries used for indexing and started another build to test. When I run this on SQLite, at least I don't see any errors.

I suspect that one of the `UPDATE` statements did not execute or its `WHERE` condition did not match all the rows in the `files` table.

The following commands force the updates to be executed again:

```
docker-compose exec photoprism photoprism migrations run 20220329-071000
docker-compose exec photoprism photoprism migrations run 20220329-082000
docker-compose exec photoprism photoprism migrations run 20220329-092000
```

**Comment by gomme600** [comment] 2022-04-01 15:30
Will try that out tomorrow, thanks for the help so far !

**Comment by cgomesu** [comment] 2022-04-02 13:45
> Our latest [development preview](https://docs.photoprism.app/release-notes/#development-preview) build `220401-a61470df` includes a new command that lists the status of database migrations.
> 
> **Could you please run this command for us and show the result?**
> 
> ```shell
> docker-compose exec photoprism photoprism migrations ls
> ```

```
root@8c10301a62f5:/photoprism# photoprism migrations ls
```
```
INFO[2022-04-02T13:27:54Z] PhotoPrism® needs your support!              
INFO[2022-04-02T13:27:54Z] Visit https://docs.photoprism.app/funding/ to learn more. 
ID                Dialect   Started At            Finished At           Status
20211121-094727   sqlite    2021-11-22 13:26:00   2021-11-22 13:26:00   OK
20211124-120008   sqlite    2021-11-25 13:25:10   2021-11-25 13:25:09   OK
20220329-040000   sqlite3   2022-04-01 01:48:14   2022-04-01 01:48:14   OK
20220329-050000   sqlite3   2022-04-01 01:48:14   2022-04-01 01:48:14   OK
20220329-061000   sqlite3   2022-04-01 01:48:14   2022-04-01 01:48:14   OK
20220329-071000   sqlite3   2022-04-01 01:48:14   2022-04-01 01:48:14   OK
20220329-081000   sqlite3   2022-04-01 01:48:14   2022-04-01 01:48:14   OK
20220329-082000   sqlite3   2022-04-01 01:48:14   -                     UNIQUE constraint failed: files.media_id
20220329-091000   sqlite3   2022-04-01 01:48:14   2022-04-01 01:48:14   OK
20220329-092000   sqlite3   2022-04-01 01:48:14   2022-04-01 01:48:14   OK
INFO[2022-04-02T13:27:54Z] closed database connection
```

> To retry previously failed migrations, you can run this command next and let us know if you see any errors or warnings:
> 
> ```shell
> docker-compose exec photoprism photoprism migrations run --failed
> ```
> 
> If you are lucky, the problem is already solved with this...

```
root@8c10301a62f5:/photoprism# photoprism migrations run --failed
```
```
INFO[2022-04-02T13:30:54Z] PhotoPrism® needs your support!              
INFO[2022-04-02T13:30:54Z] Visit https://docs.photoprism.app/funding/ to learn more. 
INFO[2022-04-02T13:30:54Z] migrate: running previously failed migrations 
INFO[2022-04-02T13:30:54Z] migrating database schema...                 
INFO[2022-04-02T13:30:55Z] migrate: 20220329-082000 successful [453.887125ms] 
INFO[2022-04-02T13:30:55Z] migration completed in 827.964118ms          
INFO[2022-04-02T13:30:55Z] closed database connection  
```

refreshed my browser and *voilà*, the photos are once again showing up. :tada: 

the only issue I noticed afterwards is that that sorting photos by 'newest first' now shows a few old photos at the top, instead of the most recent photos (but 'recently added' does start by showing the most recent ones).

**Comment by lastzero** [comment] 2022-04-02 17:28
Hopefully these commits fix the remaining issues. Indexing (no complete re-scan) should be enough.

**Comment by lastzero** [comment] 2022-04-03 15:31
Does anyone still have problems or can we consider this done?

**Comment by gomme600** [comment] 2022-04-03 15:45
Running the above command has fixed it (photoprism migrations run --failed).
Unfortunately I also have old photos showing up when selecting newest first. I am running a reindex now and will report back when it's finished.

![Screenshot_20220403-174145](https://user-images.githubusercontent.com/35890638/161436134-1e154560-1b9d-4957-82cc-869ba20ed5c8.jpg)
![Screenshot_20220403-174249](https://user-images.githubusercontent.com/35890638/161436135-7a22f90b-940c-4855-a1b9-69f762f2553e.jpg)
![Screenshot_20220403-174308](https://user-images.githubusercontent.com/35890638/161436138-07aa5a91-c99a-45ee-98bc-8d0751f7fb12.jpg)

**Comment by lastzero** [comment] 2022-04-03 22:13
Thanks! Also run the 3 individual migrations mentioned above. Just started another build for testing.

**Comment by spyfly** [comment] 2022-04-04 01:23
I ran all the migrations mentioned above, but the `/api/v1/photos` endpoint keeps timing out on the latest development preview.

**Comment by lastzero** [comment] 2022-04-04 06:17
Noted that too 😂 reverted the preview until this is solved.... Caching is hard!

**Comment by spyfly** [comment] 2022-04-04 22:06
> Noted that too joy reverted the preview until this is solved.... Caching is hard!

The most recent preview still has the same issue.

**Comment by lastzero** [comment] 2022-04-04 22:20
Our demo and other instances all work fine. What's the specific problem?

**Comment by gomme600** [comment] 2022-04-05 08:02
Reindexing fixes old photos showing up first. Personally the endpoint returns "{"code":401,"error":"Please log in and try again"}" (which is normal because I'm not sending my session id) so it doesn't seem to be timing out.

**Comment by spyfly** [comment] 2022-04-05 10:14
> Our demo and other instances all work fine. What's the specific problem?

The requests to the endpoint `/api/v1/photos` seem to time out, it seems like photoprism doesn't properly handle them for some reason.

In the logs I do get a 
```
 2022-04-05 12:10:19 DEBU photos: found 60 results for public:true dist:20 year:0 month:0 quality:3 camera:0 lens:0 count:60 order:newest merged:true [10.336317ms]
```
statement, but the corresponding http request doesn't show up.

Here's the visual result: 
![grafik](https://user-images.githubusercontent.com/2892832/161732408-fe7c2281-f0e3-4260-8688-302c4268a278.png)

According to top photoprism is using quite some resources, but the logs don't tell me anything about what it is doing in the background:
![grafik](https://user-images.githubusercontent.com/2892832/161734622-28dd65e6-cbb3-4319-95b8-ab9d0195ae9f.png)
At some point it just gets killed, because it runs out of memory. This high cpu consumption starts after loading any page which uses the `/api/v1/photos` endpoint.

**Comment by lastzero** [comment] 2022-04-05 10:56
Are you using `Build 220405-7b508d6a` as referenced in our release notes at https://docs.photoprism.app/release-notes/#development-preview?

**Comment by spyfly** [comment] 2022-04-05 11:05
> Are you using `Build 220405-7b508d6a` as referenced in our release notes at https://docs.photoprism.app/release-notes/#development-preview?

My bad, was still using `Build 220403-cbcfa63f`

The issue is fixed in the new build

**Closed as completed** 2022-05-17 09:58 UTC
Labels: bug, released
