### ISSUE TITLE
People: Photos With All Faces Assigned Appear Under “New Faces”

### ISSUE THREAD

**Issue by comminutus** [photoprism/photoprism#2936] opened 2022-11-24 13:24 UTC
#### 1. What is not working as documented?

I've recently imported my media using PhotoSync on iOS. After the initial index completed, I assigned names to all of the face clusters in People -> New.

There was one face cluster that had assigned some wrong faces to several photos, so I clicked on the reject button for the few faces that didn't match the person.

I then went to People -> New -> Show All New Faces and started manually assigning faces to the photos by clicking on the edit button and going to the people section of each photo. I did this for at least 300 photos. All of the people in the photos I manually assigned have been assigned; there is no unrecognized person that I haven’t assigned a name to.

When I navigate away from the new faces section, and then go back People -> New -> Show All New Faces, all of the photos I've previously manually assigned still show up under the new faces search, even though all faces in these photos have already been assigned.

I thought maybe re-indexing would help but after re-indexing the entire library, the photos I've already manually assigned faces to still appear under the "show all new faces" section.

If a photo has already been assigned all possible faces, shouldn’t it lose it's "new" status?  Is there any way to completely delete a person/face and re-index all the photos without having to start from scratch?

#### 2. How can we reproduce it?

1. Go to 'People’
2. Click on ‘New’
3. Name a person's face
4. Click on that person's face to show all of the pictures containing that person
5. Click on one of the photos and click on the edit button
6. Go to the people section, click on the "eject" button  (⏏️)
7. Do this for a few more photos
8. Scroll to the bottom of the page
9. Click on ‘show all new faces’
10. Click on one of the photos displayed in the search
11. Click the edit button
12. Click on the people section at the top
13. Assign all detected faces to a name
14. Close the edit window by clicking the “x” at the top left
15. Click the same photo again
16. Click on the people section at the top
17. Verify all the people in the photo have been assigned names
18. Repeat this process for several photos
19. Navigate away from the new faces search by clicking on any grouping of photos on the left-hand side (I chose “Search”)
20. Go back to People
21. Click on New
22. Scroll to the bottom of the page
23. Click on show all new faces
24. Confirm the photos you had assigned faces to still appear under this “new faces” search

#### 3. What behavior do you expect?

After assigning all possible faces to a photo, it should no longer appear in the “new faces” search.

#### 4. What could be the cause of your problem?

I'm not sure.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

I can't think of what might help but please let me know if there's something I can provide which you think might help.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build
PhotoPrism CE Docker tag `221118-jammy` (linux/amd64), Build 221118-e58fee0fb

(b) Database Type & Version: MariaDB, MySQL, SQLite,...
MariaDB 10.9.4

(c) Operating System Types & Versions: Linux, Windows, Android,...
Ubuntu 22.04 Jammy (via Docker)

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...
Firefox 107.0 (64-bit)

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?
Some installed but all disabled for PhotoPrism site

#### 7. On what kind of device is PhotoPrism installed?

Docker 20.10.3 on Intel Atom C3538, 2.1Ghz, 4 cores, 18GB RAM

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Reverse proxy through Traefik, v2.9.1

**Comment by lastzero** [comment] 2022-11-24 13:52
Could these be stacks so the unassigning face is on a non-primary image of the stack?

**Comment by comminutus** [comment] 2022-11-24 14:02
@lastzero The photos in "new faces" that aren't being moved out of new faces don't appear in my "Stacks" area.

**Comment by graciousgrey** [comment] 2022-11-24 14:13
Just to be sure I understand you correctly:  With "Reject one of the face clusters" you mean hiding faces --> https://docs.photoprism.app/user-guide/organize/people/#hiding-faces ?
On the edit dialog, did you also assign a name to the faces that belong to the face cluster you have hidden ?

**Comment by comminutus** [comment] 2022-11-24 14:24
@graciousgrey No, sorry for the confusion.  It seems "hiding" a face disassociates a person's face from a photo and this is done by clicking the "X" button.

By rejecting the photo cluster I mean clicking the "eject" button described here: https://docs.photoprism.app/user-guide/organize/people/#change-people-assignments . I wasn't sure what the correct terminology is here, but it does say "When you reject a match, the corresponding face cluster will be updated in the background so that similar issues can be resolved automatically."

**Comment by graciousgrey** [comment] 2022-11-24 14:34
> No, sorry for the confusion. It seems "hiding" a face disassociates a person's face from a photo and this is done by clicking the "X" button.

This is not hiding a face but removing a face  ;) https://docs.photoprism.app/user-guide/organize/people/#remove-faces

So you did reject a  name from a face on the edit dialog, then you added a new name to this face and exactly this photo still shows up under faces:new afterwards?

**Comment by comminutus** [comment] 2022-11-24 14:38
@graciousgrey No I went to "Faces", then "New", then on one of the face clusters I clicked on the eject button.  I wasn't on the edit dialog, just on the main view of all of the faces.  This disassociated all of the photos in that face cluster with this person.  Then I went to "show all new faces," and started manually assigning the person associated with the photos that were just disassociated.

**Comment by comminutus** [comment] 2022-11-24 16:54
Is there a workaround I can do in the meantime?  Can I remove this particular face from the database without having to start from scratch?  It seems disassociating the face from the photo doesn't remove the face from the database.

**Comment by graciousgrey** [comment] 2022-11-24 17:15
Ok, so you have  hidden an unnamed face cluster on the people>new page by clicking the "x" ?

Then on the edit dialog of a photo that has a face from this cluster you added a name to the face that belongs to the hidden cluster and you also added names to all other faces that have been detected on this photo. 

Then after a refresh this photo still shows up when you click show all new faces?

**Comment by comminutus** [comment] 2022-11-24 18:32
@graciousgrey 
> Ok, so you have hidden an unnamed face cluster on the people>new page by clicking the "x" ?

No, I never said that I clicked on an "x" to hide a face.  I've only clicked on the "eject" button (⏏️) on the page where it shows all the different face clusters (People -> New), as described in the "Change People Assignment" section of the documentation on People (linked earlier).

After clicking the ⏏️ button, then I went to "show all new faces," then edited a photo that contains a face which used to be in the photo cluster that I had clicked the ⏏️ button, I assigned names to all of the faces in that photo, then when I refresh the photo still appears in the "new faces" search.

**Comment by graciousgrey** [comment] 2022-11-24 19:35
> I wasn't on the edit dialog, just on the main view of all of the faces. 

Could you provide us with some screenshots? The eject button is only visible on the people tab of the edit dialog, not on the people>new page.

**Comment by graciousgrey** [comment] 2022-11-24 19:41
If you rejected a name from a face using the edit dialog as described here: https://docs.photoprism.app/user-guide/organize/people/#change-people-assignments it is expected that face clusters are updated. 
This means other faces of the original cluster might have been removed from the cluster as well and will appear under "show all new faces" again. 
If you afterwards add names to those faces so that all faces that are shown in the edit dialog of a photo have a name assigned this photo should not appear under "show all new faces" anymore.

**Comment by comminutus** [comment] 2022-11-24 20:20
@graciousgrey Sorry, my mistake.  I thought there was an eject button on the entire face cluster.  I must've manually hit the eject button on the photos that didn't match the person.  Nonetheless, when I assign names to all the faces found in hundreds of photos in the 'new faces' area, they aren't disappearing from the 'new faces' area and remain.

**Comment by graciousgrey** [comment] 2022-11-24 20:34
With "New Faces area" you mean "Show all new faces"? Does a reload help?

Do you see any errors on /library/errors?

I will try to reproduce it tomorrow.

**Comment by comminutus** [comment] 2022-11-24 21:19
Yes, "Show all new faces" still shows several photos that have all faces assigned.  Some of the interesting messages from /library/errors:
```
faces: YZK2M6J27636SDB7FS2EE6QTSOV2MXIF has ambiguous subjects <REDACTED> and <unknown> 
faces: clearing ambiguous subject <REDACTED> from face YZK2M6J27636SDB7FS2EE6QTSOV2MXIF, similar face at dist 0.000000 with source manual
faces: marker mrlo86g3pgxr2qsx face 7SHECGA62SEVCLJKXVKYFMKQYHXSG5YF has ambiguous subjects jrlozay1dlqh27j8 <> jrlrkargya43egme, subject source manual
```

**Comment by comminutus** [comment] 2022-11-24 21:21
Also refreshing, restarting, and even re-indexing doesn't help unfortunately.

**Comment by lastzero** [comment] 2022-11-24 21:22
This message indicates inconsistent naming or very similar faces that cannot be distinguished, like siblings or small children.

**Comment by comminutus** [comment] 2022-11-24 21:36
@lastzero that makes sense, but probably an independent problem not related to this since all the faces are assigned but still appear in "Show all new faces"

**Comment by comminutus** [comment] 2022-11-25 02:11
This sounds strikingly similar to what I'm experiencing:  https://github.com/photoprism/photoprism/discussions/2030

**Comment by graciousgrey** [comment] 2022-11-25 08:17
Unfortunately I can't reproduce your issue on our instances.

How many files are associated to your photo? You can find this information on the files tab of the edit dialog (https://docs.photoprism.app/user-guide/organize/edit/#edit-files). 
In the discussion you mentioned,  the problem was that two files with faces on them have been stacked.

**Comment by lastzero** [comment] 2022-11-25 09:34
Screenshots or a video might be helpful as well.

**Comment by comminutus** [comment] 2022-11-25 12:13
> Unfortunately I can't reproduce your issue on our instances.
> 
> How many files are associated to your photo? You can find this information on the files tab of the edit dialog (https://docs.photoprism.app/user-guide/organize/edit/#edit-files). In the discussion you mentioned, the problem was that two files with faces on them have been stacked.

On one, a "live photo," there is 15 files associated with the photo. This photo appears under "Show all new faces" but if you go to Edit -> Faces there are no faces displayed.

On another "live photo," there are 8 files associated with the photo with two faces, both assigned.  This photo exists in a stack.

These are just a couple of examples but the problem appears over hundreds of photos.

There are some photos that the problem manifests that don't exist in stacks.

**Comment by comminutus** [comment] 2022-11-25 12:14
> Screenshots or a video might be helpful as well.
Sure, here's the photo that appears under "Show all new faces" but has no faces to assign (redacted personal information):
![Screenshot from 2022-11-25 1](https://user-images.githubusercontent.com/113857766/203983924-b2b913cc-c997-4dfb-9383-990f1240f83a.png)
![Screenshot from 2022-11-25 2](https://user-images.githubusercontent.com/113857766/203983930-332bce1f-1fc8-4c79-99fa-aecbd8158871.png)
![Screenshot from 2022-11-25 3](https://user-images.githubusercontent.com/113857766/203983933-7dcd8d13-a680-4cec-8aa1-02959cfe0591.png)

**Comment by comminutus** [comment] 2022-11-25 12:16
Here's another which has two faces, both assigned, but still appear in "Show all new faces" (redacted personal information): 
![Screenshot from 2022-11-25 4](https://user-images.githubusercontent.com/113857766/203984143-a3fdeb11-e012-4f1b-936d-158326c794bc.png)
![Screenshot from 2022-11-25 5](https://user-images.githubusercontent.com/113857766/203984144-30a9ac28-9a91-4570-a8d4-a8766aae1f54.png)
![Screenshot from 2022-11-25 6](https://user-images.githubusercontent.com/113857766/203984145-a6f1e9d1-7879-4eb6-bb21-fc99d3cdcba9.png)

**Comment by comminutus** [comment] 2022-11-25 12:18
Is there some way to debug why these photos still appear under "new faces?"

**Comment by graciousgrey** [comment] 2022-11-25 12:45
Those are stacks. So probably on the non-primary JPGs there are faces as well that have no names assigned yet.

You can read more about stacks here: https://docs.photoprism.app/user-guide/organize/stacks/#unstack-files

**Comment by lastzero** [comment] 2022-11-25 12:48
**So it seems that the problem is indeed related to stacked files, as I first suspected?**

- Judging from your screenshots, the images might have been stacked because they were taken at the same place and time (at least the time seems to match based on the file name).
- To prevent the files from getting stacked, please disable the feature(s) in *Settings > Library*.
- The Faces tab in the Edit dialog will only show the faces of the image that is currently selected as the primary image.
- Additional files in the stack are normally not searched for faces.
- However, if they were detected before the files were stacked, the markers are still there - but you can't edit or remove them without unstacking the affected images first.
- This is a rare special case that can occur when files are stacked based on metadata such as location and time.
- Since Live Photos contain 3 seconds of video, I wonder how you can capture several of them in the same second? Something seems odd here. If you are a sponsor, we could help you privately in case you are willing to provide sample files for debugging.
- Note that Live Photos do not appear in "Stacks" because it is a special type of media that is always "stacked". The "Stack" section is for regular images that don't usually include multiple files.

You can learn more about Stacks in our docs:
- https://docs.photoprism.app/user-guide/organize/stacks/

**Comment by lastzero** [comment] 2022-11-25 12:55
Although the UI could always use improvements and more features, I'm closing this issue for now since it seems to be working as intended. If these pictures weren't displayed, you wouldn't have noticed the actual problem with the stacks, which is also why we won't be changing it. However, the documentation should be improved to cover this particular case and reduce the number of related support requests.

**Closed as completed by lastzero** 2022-11-25 12:55 UTC
Labels: question, docs 📚

**Comment by lastzero** [comment] 2022-11-25 12:57
You are welcome to help improve our docs by sending a pull request:

👉 https://github.com/photoprism/photoprism-docs

**Comment by comminutus** [comment] 2022-11-25 13:16
> * Additional files in the stack are normally not searched for faces.

Shouldn't all images in a stack disappear from "Show all new faces" if all faces in the primary photo have been assigned?  This problem doesn't seem that rare given it's over hundreds of my images.

**Comment by comminutus** [comment] 2022-11-25 13:17
> * Since Live Photos contain 3 seconds of video, I wonder how you can capture several of them in the same second? 

It seems the live photo has been stacked with other photos.

**Comment by lastzero** [comment] 2022-11-25 13:22
> Shouldn't all images in a stack disappear from "Show all new faces" if all faces in the primary photo have been assigned?

If these pictures were not displayed, you would not have noticed the actual problem with the stacks, which is why we are not going to change it. Note that it doesn't make sense to show all faces of all stacked images in the tab, because then there would be lots of duplicates and you wouldn't know which face belongs to which file.

> It seems the live photo has been stacked with other photos.

Exactly. It doesn't look right to me, but figuring out why (misleading file names, bad metadata?) is beyond the scope of our free community support.

**Comment by comminutus** [comment] 2022-11-25 13:31
> If these pictures were not displayed, you would not have noticed the actual problem with the stacks, which is why we are not going to change it. Note that it doesn't make sense to show all faces of all stacked images in the tab, because then there would be lots of duplicates and you wouldn't know which face belongs to which file.

But ideally in cases where the images were stacked correctly, I don't want to unstack the stack.  To fix the problem, I have to unstack the images, which defeats the purpose of the stack in the first place, and then assign all of the faces correctly.  At this point the faces are correct and don't appear in "Show all new faces" but I've lost the usefulness of the stack.

**Comment by lastzero** [comment] 2022-11-25 13:37
Do we know yet if the stack is useful and why the files were stacked? IMHO that should be figured out first before taking any further steps...

**Comment by comminutus** [comment] 2022-11-25 15:13
@lastzero I do have, for example, a stack that has 2 raw images and 2 jpeg files (I'm guessing PhotoPrism generates these jpegs as sidecar files to the raw files).  The two images are very related, and I definitely want them to be stacked.  I found this stack from the "Show all new faces" option, but all faces are already assigned.  In order to correct the problem, I will have to unstack the two images and assign the face to other photo that was in the stack, and now I've lost the ability to stack them.

The two file names are `2021/06/20210613_213253_6436EEB7.heic` and `2021/06/20210613_213253_9E8BA3EF.heic`.  One of the UIDs is `FRLO37XB790H6LFU` and the other is `FRLO37Y1G90R11GJ`. I'm guessing they were stacked because they contain the same geocode and time.

There doesn't seem to be a way to preserve this stack, *and* be able to have the photo disappear from "Show all new faces."  Isn't that a bug?

**Comment by lastzero** [comment] 2022-11-25 15:29
Generally, secondary images will not be searched for faces for that reason. However, there is this special case where they do get stacked after detection. We'll be able to handle this in futures releases as our UI is getting more features. Bug means we let everything drop right now, stop working on multi user which everyone is waiting for, then focus on developing new features to solve this very special problem most users do not have.

Due to limited resources this unfortunately is a known limitation. You can help us by becoming a sponsor so we have more development resources as that is the only thing that helps.

**Comment by graciousgrey** [comment] 2022-11-25 15:32
For now you can simply change the primary file to assign names to the faces that have no names yet, there is no need to unstack the files if you want them to stay stacked.

https://docs.photoprism.app/user-guide/organize/stacks/#change-primary-files

**Comment by comminutus** [comment] 2022-11-25 15:43
> It's a known limitation. Generally, secondary images will not be searched for faces for that reason. However, there is this special case where they go get stacked after detection. We'll be able to handle this in futures releases as our UI is getting more features. Bug means we let everything drop right now, stop working on multi user which everyone is waiting for right now, then focus on developing new features to solve this very special problem most users do not have. Due to limited resources this unfortunately is a known limitation. You can help us by becoming a sponsor so we have more development resources as that is the only thing that helps.

I can certainly understand that there can be higher priorities than to fix this, but saying it's not a bug doesn't quite seem right since it clearly is one.

Isn't it possible to have features that are higher priorities than bugs?

**Comment by comminutus** [comment] 2022-11-25 15:44
> For now you can simply change the primary file to assign names to the faces that have no names yet, there is no need to unstack the files if you want them to stay stacked.
> 
> https://docs.photoprism.app/user-guide/organize/stacks/#change-primary-files

I tried doing that but original face still shows up in the faces dialog and I can't edit the other image in the stack's face.

**Comment by lastzero** [comment] 2022-11-25 15:54
We'll document it so it is a known issue. Was hoping for some support from your side.

**Comment by comminutus** [comment] 2022-11-25 15:56
@lastzero ok, thanks. I'll be becoming a sponsor in December ;)

**Comment by lastzero** [comment] 2022-11-26 14:22
:point_right: https://docs.photoprism.app/known-issues/#photos-with-all-faces-assigned-appear-under-new-faces

**Comment by ecker00** [comment] 2022-11-28 21:54
Just adding the fact that I'm also experiencing this. The cause seems to be stacked photos.

Could a solution be to show the faces from each image separated by files on the "People" tab? Similar UI to how each file is shown in the "Files" tab?

**Comment by lastzero** [comment] 2022-11-28 22:09
It would be very confusing to just display all the faces, especially if the images really belong together, because that would just look like a lot of duplicates. While it would be possible to develop a different UI/UX concept, that would also be quite expensive (and most users still would not need it). Ultimately, the best way to improve this is to improve our funding (which we are working on right now). Stay tuned and give us some time. Thank you very much!
