### ISSUE TITLE
Indexing of Symlinks Not Working

### ISSUE THREAD

**Issue by garrettdowd** [photoprism/photoprism#267] opened 2020-03-23 18:51 UTC
Action : `photoprism index` 
Details: I have mounted my main photo collection bind mounted inside the docker container. I added symlinks between certain folders in the collection and the Pictures/Originals folder.

Expected Result: I assumed it would index all of the photos in the Pictures/Originals folder by following the symlinks.

Actual Result: No photos are indexed. The indexer does not seem to find any of the photos through the symlinks.

Given my large photo collection, I am still trying to find ways to only index certain parts of the collection.

**Comment by lastzero** [comment] 2020-03-23 19:44
Thanks for reporting this! `os.Stat()` should follow links: https://golang.org/pkg/os/#Stat

So maybe this is related to permissions... different user id? Do you see an error in the logs?

**Comment by garrettdowd** [comment] 2020-03-23 20:24
Unfortunately nothing in the logs. 

Mounting the photo folder directly (bind mount) in the `Originals` folder works. However, mounting the photos folder (bind mount) in the container (at `/mnt/photos/`) and then symlinking it to the `Originals` folder does not seem to work.

**Comment by rockwotj** [comment] 2020-04-05 02:55
@lastzero the issue is with [filepath.Walk](https://golang.org/pkg/path/filepath/#Walk) which does not follow symlinks. [Here is the code](https://github.com/photoprism/photoprism/blob/develop/internal/photoprism/index.go#L89).

I may suggest trying out: [fastwalk.Walk](https://godoc.org/golang.org/x/tools/internal/fastwalk#Walk) instead because it faster (less syscalls) and it looks like you only need to know if it's a directory or not, and it looks like it has the ability to traverse links using [ErrTraverseLink](https://godoc.org/golang.org/x/tools/internal/fastwalk#pkg-variables). The only thing you have to handle is loops, which may be tricky and maybe for a first pass you can punt on that an assume the directory structure contains no loops? 

There are ways to get prevent loops, but they may not be cheap, since in practice I'd assume that people should only have either a single symlink or just a few in a single directory (like me) that it's probably fine to have traversing links be "expensive" by doing some extra checks to make sure it's not traversing into a folder that would cause a loop with another symlink.

If you're OK with doing this fix in two phases and using the fastwalk package, I maybe able to throw a PR together. Thoughts?

**Comment by lastzero** [comment] 2020-04-14 15:33
@rockwotj Sounds good!

**Comment by lastzero** [comment] 2020-04-27 11:57
@rockwotj No worries if you don't have time. Might find a chance to take care of this soon!

**Comment by lastzero** [comment] 2020-05-01 15:38
Symlinks should work like that, but we want to test it more before it's merged into master (Docker image). Maybe we'll also implement ignore files along the way.

**Closed** 2020-05-06 20:30 UTC
Labels: bug, done, important

**Comment by MFlasskamp** [comment] 2021-02-18 23:18
I'm still not able to add folders via symlink to the library with the latest docker image (210217-49039368-Linux-x86_64).

Folder `/share/media/photoprism` is mapped via docker to `/photoprism/originals`. Existing subfolders are found and indexed, but not the symlinks. The symlinks points to a folder on the same drive and filesystem:

```
[/share/media/photoprism] # file linktest
linktest: symbolic link to /share/media/photoprism_test
```

Relevant log output:
```
2021-02-18 23:56:02 INFO Indexing completed in 0 s
2021-02-18 23:56:02 DEBU moments: 32 albums saved as yaml files
2021-02-18 23:56:01 DEBU moments: updated “Bays, Capes & Beaches” (public:true label:beach|seashore)
2021-02-18 23:56:01 DEBU moments: updated “Nature & Landscape” (public:true label:landscape|nature)
2021-02-18 23:56:01 DEBU moments: updated “Nature & Landscape” (public:true label:landscape|nature)
2021-02-18 23:56:01 DEBU moments: updated “Bays, Capes & Beaches” (public:true label:beach|seashore)
2021-02-18 23:56:01 DEBU moments: index contains 1039 photos and 0 videos, using threshold 11
2021-02-18 23:56:01 INFO purge: searching index for hidden media files
2021-02-18 23:56:01 INFO purge: searching index for unassigned primary files
2021-02-18 23:56:01 DEBU removed folder:/:true:false from cache
2021-02-18 23:56:01 INFO index: no new or modified files
2021-02-18 23:56:01 ERRO index: stat /linktest: no such file or directory
2021-02-18 23:56:01 INFO index: no .ppignore file found
2021-02-18 23:56:01 INFO Indexing originals...
```
Am I doing anything wrong?

**Comment by alexislefebvre** [comment] 2021-02-19 00:38
I think `/share/media/photoprism_test` is not accessible because you mounted `/share/media/photoprism` and Docker can't follow a symlink out of the mount point.

**Comment by lastzero** [comment] 2021-02-19 06:44
Exactly

**Comment by MFlasskamp** [comment] 2021-02-19 18:45
You’re right, thank you! And shame on me...
After mounting the parent folder to the same path in the container, the symlink I create on the host are now valid in the container.
