### ISSUE TITLE
Configurable stacking time threshold

### ISSUE THREAD

**Issue by eigan** [photoprism/photoprism#1085] opened 2021-02-21 17:16 UTC
There is an option to stack media taken in the same second. Would it be possible to adjust the time here? Say I wanted to group everything with 4 seconds. I tend to take a lot of duplicates so its not that easy to scroll through my images when several images looks the same. Yes, I could probably handle this better myself be not doing this, but I just want to make sure I get at least one OK image, hehe...

![image](https://user-images.githubusercontent.com/41789/108632609-291f2c00-7470-11eb-82d2-79f4f672d54d.png)

I could however solve this myself by stacking them with a script (adding sequential names), but I would like to check if this would be possible to PhotoPrism first. Maybe others have similar case.. 😄

**Comment by graciousgrey** [comment] 2021-02-22 09:30
Could be done, at one point. But at the moment other tasks have higher priority

**Comment by graciousgrey** [comment] 2021-11-02 13:44
Closed as duplicate of: https://github.com/photoprism/photoprism/issues/1446. The newer one contains more information.

**Closed by graciousgrey** 2021-11-02 13:44 UTC
Labels: idea
