### ISSUE TITLE
Support for source files from apps like Inkscape, Pitivi, GIMP, Blender, Adobe Illustrator, Final Cut, etc.

### ISSUE THREAD

**Issue by heyakyra** [photoprism/photoprism#1177] opened 2021-04-07 03:22 UTC
It would be great to be able to support some of the functionality of [MediaGoblin](https://mediagoblin.org/), DeviantArt, [Git-Annex Assistant](https://git-annex.branchable.com/assistant/), or [Abstract](https://www.abstract.com/). First this requires adding other source files in addition to RAW (.svg, .xges, .xcf, .ai, etc.). 

Later, the concept of revisions or versions could be added. Would be a very powerful combination!

**Comment by lastzero** [comment] 2023-02-13 13:25
I'll close this issue since it's pretty much a duplicate of #2207. However, feel free to comment here about file type support! With the next release, our Plus and Pro Editions will support the svg, ps, and eps formats. It is possible to add more formats if requested.

**Closed by lastzero** 2023-02-13 13:25 UTC
Labels: idea, vector, pro-feature, plus-feature
