### ISSUE TITLE
Sharing: Public Image Wall

### ISSUE THREAD

**Issue by FreshMosh** [photoprism/photoprism#1159] opened 2021-03-29 12:18 UTC
Addendum to this: [Multi-User Photo Gallery with private and shared photos/albums](https://github.com/photoprism/photoprism/issues/98)

As user I want to be able to display a selected and curated list of images publicly. 

I could imagine this as some sort of unique yet easy to guess URL. 
Like:
photoprism.domain.tld/user1
photoprism.domain.tld/user2

This is only an idea at this point.

**Comment by graciousgrey** [comment] 2021-11-03 13:23
Duplicate of: https://github.com/photoprism/photoprism/issues/669. Feel free to leave a :+1: there :)

**Closed by graciousgrey** 2021-11-03 13:23 UTC
Labels: idea
