### ISSUE TITLE
JPEG: Support panoramas taken with a Samsung S21

### ISSUE THREAD

**Issue by maxime1992** [photoprism/photoprism#3363] opened 2023-05-03 10:08 UTC
#### 1. What is not working as documented?

[Latest release](https://docs.photoprism.app/release-notes/#may-2-2023) includes [improvement for broken pictures](https://github.com/photoprism/photoprism/issues/1407#issuecomment-1532437753).

But all the panoramas taken with a Samsung S21 are still appearing as "upload successful" while they're actually not.

#### 2. How can we reproduce it?

Download this image (just as a sanity check in case github does any kind of processing, the md5 checksum should be `75171ad4f47a883b97e73bced03a29c7`):

![20220605_153254](https://user-images.githubusercontent.com/4950209/235871906-ee5ed47c-0dfb-4f9f-943a-094414a8a0ea.jpg)

- Try to upload it on Photoprism
- At the end, notice that whether you get a success or an error for the upload, the file won't be in your gallery

#### 3. What behavior do you expect?

Being able to upload my panorama successfully

#### 4. What could be the cause of your problem?

Looking at related issues https://github.com/photoprism/photoprism/issues/1944, https://github.com/photoprism/photoprism/issues/1407, https://github.com/photoprism/photoprism/issues/2463 and this comment in particular https://github.com/photoprism/photoprism/issues/1407#issuecomment-873392688, I suspect the issue is in the golang repo mentionned. BUT, there seem to be a [1 line fix when consuming the picture](https://github.com/golang/go/issues/45902#issuecomment-1293328808) and I'm hoping it can be as simple as this on Photoprism side to fix this for now and eventually remove that useless 1 line fix once it's fixed upstream. But the upstream issue has been open for a while and it'd be lovely to have that fix available in Photoprism meanwhile. I know it's not ideal, but if it's really a 1 line fix, it'd be tremendously helpful :pray: 

And for refence, I'm creating this new issue as suggested [here](https://github.com/photoprism/photoprism/issues/2463#issuecomment-1532565664).

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Testing file uploaded above.

The kind of logs I'm getting is this:

```
import: failed creating thumbnails for 2021/11/20211128_141554_7B99F85D.jpg (EOF while decoding)
```

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...

AMD64, build `230502-c405f6eff`

(b) Database Type & Version: MariaDB, MySQL, SQLite,...

MariaDB 10.11 as suggested in the release note

(c) Operating System Types & Versions: Linux, Windows, Android,...

Linux / official Photoprism docker image

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...

Chrome

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?

Yes but works fine for any other picture

**Comment by lastzero** [comment] 2023-05-05 09:16
Yeah, the problem is probably that the upload is indeed successful, but the indexing fails. We don't yet know if all files can be indexed properly with all metadata, etc. at the time the success message is displayed. However, you should find error or warning logs under Library > Errors?

**Comment by lastzero** [comment] 2023-05-05 09:18
What would be a good solution (apart from never having problems with indexing)? Show another message that says "Sorry, upload was not successful, ignore the previous information"?

**Comment by lastzero** [comment] 2023-05-05 09:27
Of course, we will also take a look at improving the JPEG reader, but due to the many other tasks, I can't promise a quick solution. Ideally a contributor can help with this! Thank you :)

**Comment by maxime1992** [comment] 2023-05-05 11:17
@lastzero I've seen you've changed the title to "UX: Warn user if upload was successful but indexing failed 1".
I've edited that and changed it to "Broken file leads to an error when creating thumbnails after upload and the image isn't visible" as this is the issue I'm really after here.

That said, I did open a separate issue to track that specific problem here: https://github.com/photoprism/photoprism/issues/3371. Can you edit the labels accordingly please as this issue isn't about UX.

> Yeah, the problem is probably that the upload is indeed successful, but the indexing fails. We don't yet know if all files can be indexed properly with all metadata, etc. at the time the success message is displayed

Yup that'll be part of the new issue I've created to track the UX issue but it's not what I'm after here. In that very specific case, I'd just like not to have a crash in the first place and being able to upload my panoramas without running a bunch of commands with image magick to fix them upstream. What I'm after would be to have [this fix](https://github.com/golang/go/issues/45902#issuecomment-1293328808) included so that the bad images are not crashing.

> However, you should find error or warning logs under Library > Errors?

Correct. But because it appears as successful, I'm not tempted by any mean to open the logs. I only did because by chance I noticed that the album had a different number of pictures than what I had originally. But let's move UX discussion to the new issue.

> What would be a good solution (apart from never having problems with indexing)? Show another message that says "Sorry, upload was not successful, ignore the previous information"?

I'll reference that comment in the new issue and answer here.

> Of course, we will also take a look at improving the JPEG reader

Awesome :fire:. Hopefully it's limited to this [little fix](https://github.com/golang/go/issues/45902#issuecomment-1293328808) :crossed_fingers: 

> due to the many other tasks, I can't promise a quick solution

I understand. While I'm not in a position to help, I'm a developer and I know what a backlog is like :upside_down_face:. If you need any more info about this or if you've got any issue to repro, do ping me. Happy to help out.

Last but not least, as I see this issue already have a few ":+1:", **in case someone is interested in a temporary fix** to go pretty much automatically, through a lot of pics, I've explained how to do that [here](https://github.com/photoprism/photoprism/issues/1407#issuecomment-1532767800).

**Comment by graciousgrey** [comment] 2023-06-29 11:07
This should be fixed with 

- https://github.com/photoprism/photoprism/pull/2721 

However, we should take a look at the indexing performance, because it seems slower now, at least for files with errors.

**Comment by maxime1992** [comment] 2023-06-30 06:38
I just tried the preview version and I can confirm with my test image above that this is now fixed! :tada: 

Thanks a lot

**Closed as completed** 2023-07-19 16:12 UTC
Labels: enhancement, released

**Comment by lastzero** [comment] 2023-10-31 12:25
@maxime1992 While the changes did not help to read the "broken" JPEGs without re-encoding them, they broke the repair mechanism that we implemented for Samsung panoramas. I've just added (yet another) fix for this, see:

- #3855

An updated preview build will be available for testing soon!
