### ISSUE TITLE
Photos missing after upload

### ISSUE THREAD

**Issue by Aidan-OS** [photoprism/photoprism#296] opened 2020-05-06 16:51 UTC
Found and installed Photoprism today in hopes of moving all images off my google drive to a personal server. I used the docker compose method of creating the container.

My first uploads went fine, testing with single images. I noticed that the quality filter was blocking everything, so I turned it off. I also noticed that there is an NSFW Filter that I needed to turn off, so I did so in the Docker Compose and restarted the server.

Now, when I import a photo, either using the web interface or right on the server, the image does not appear. The amount of photos in the menu on the left does not reflect the amount of photos the software sees when browsing.

For example, when I tested importing 3 files by putting them in the "Import" folder on the server, connecting to the container and running `photoprism import` and `photoprism index`, the file count for files in the "private" section increased to 3, however when I go to browse there are no files.

Accurate image counts for what I have uploaded
![image](https://user-images.githubusercontent.com/1919827/81204923-f5821c80-8f97-11ea-8782-35f11b4561cb.png)

Private tab
![image](https://user-images.githubusercontent.com/1919827/81204948-003cb180-8f98-11ea-85e0-8a3ae54022b8.png)

Photos found in main tab (Cropped due to privacy reasons)
![image](https://user-images.githubusercontent.com/1919827/81205070-2cf0c900-8f98-11ea-83ab-21d198c4f62f.png)

**Comment by lastzero** [comment] 2020-05-06 16:53
Maybe the problem is that they are still marked as private? You can open the private page, mark all images and click on the lock in the context menu (bottom right). This should remove the private flag.

**Comment by lastzero** [comment] 2020-05-06 16:54
Also make sure to properly restart the container, `docker restart` does NOT work. You need down and up.

**Comment by Aidan-OS** [comment] 2020-05-06 16:54
There are no Images available for selection on the private page, as seen in the second photo

**Comment by Aidan-OS** [comment] 2020-05-06 16:55
I have been using `docker-compose restart` as stated here: https://docs.photoprism.org/en/latest/getting-started/docker-compose/#step-2-run

**Comment by lastzero** [comment] 2020-05-06 16:57
Thanks for the hint, this is wrong :/ Will change it! Down and up works.

**Comment by Aidan-OS** [comment] 2020-05-06 17:02
Used Down and Up, that has made my password change go through thankfully. Sadly I am still unable to upload any new files.

**Comment by lastzero** [comment] 2020-05-06 17:04
What do the logs say? See Library > Logs tab.

**Comment by lastzero** [comment] 2020-05-06 17:05
PHOTOPRISM_DETECT_NSFW is false and PHOTOPRISM_UPLOAD_NSFW is true now, right?

**Comment by Aidan-OS** [comment] 2020-05-06 17:06
Oddly enough, the logs are empty. I checked them earlier and there was some, but they seem to have vanished. PHOTOPRISM_DETECT_NSFW is false and PHOTOPRISM_UPLOAD_NSFW is true

**Comment by lastzero** [comment] 2020-05-06 17:08
`docker-compose logs --tail="100" -f`

Logs in the browser disappear when you reload so that we don't get memory issues.

**Comment by lastzero** [comment] 2020-05-06 17:11
If your photos are not strictly private, you're welcome to test with our demo too. Just in case it's a problem with a specific file.

**Comment by Aidan-OS** [comment] 2020-05-06 17:12
I uploaded 2 Images. The first has appeared in the photo browser, however the second has not.
```
photoprism_1  | time="2020-05-06T17:10:05Z" level=info msg="1 files uploaded in 8.347812ms"
photoprism_1  | time="2020-05-06T17:10:05Z" level=info msg="moving files from 1588785005218"
photoprism_1  | time="2020-05-06T17:10:05Z" level=info msg="import: no .ppignore file found"
photoprism_1  | time="2020-05-06T17:10:05Z" level=info msg="mediafile: taken at 2020-05-06 17:10:05.863905449 +0000 UTC"
photoprism_1  | time="2020-05-06T17:10:05Z" level=info msg="import: moving main png file Image-37.png to 2020/05/20200506_171005_75306D05.png"
photoprism_1  | time="2020-05-06T17:10:05Z" level=info msg="convert: 2020/05/20200506_171005_75306D05.png -> 2020/05/20200506_171005_75306D05.jpg"
photoprism_1  | time="2020-05-06T17:10:06Z" level=info msg="mediafile: 11 thumbnails created for 20200506_171005_75306D05 [261.019556ms]"
photoprism_1  | time="2020-05-06T17:10:06Z" level=info msg="import: added main png file 2020/05/20200506_171005_75306D05.png"
photoprism_1  | time="2020-05-06T17:10:07Z" level=info msg="index: no latitude and longitude in metadata"
photoprism_1  | time="2020-05-06T17:10:07Z" level=info msg="photo: changed photo title to “Unknown / 2020”"
photoprism_1  | time="2020-05-06T17:10:07Z" level=info msg="import: added related jpg file 2020/05/20200506_171005_75306D05.jpg"
photoprism_1  | time="2020-05-06T17:10:07Z" level=info msg="import: deleted empty directory /photoprism/import/upload/1588785005218"
photoprism_1  | time="2020-05-06T17:10:07Z" level=info msg="import completed in 1 s"
photoprism_1  | time="2020-05-06T17:10:20Z" level=info msg="1 files uploaded in 562.062µs"
photoprism_1  | time="2020-05-06T17:10:20Z" level=info msg="moving files from 1588785019465"
photoprism_1  | time="2020-05-06T17:10:20Z" level=info msg="import: no .ppignore file found"
photoprism_1  | time="2020-05-06T17:10:20Z" level=info msg="mediafile: taken at 2020-05-06 17:10:20.111666555 +0000 UTC"
photoprism_1  | time="2020-05-06T17:10:20Z" level=info msg="import: moving main png file Image-38.png to 2020/05/20200506_171020_C70D9FEC.png"
photoprism_1  | time="2020-05-06T17:10:20Z" level=info msg="mediafile: 11 thumbnails created for 20200506_171020_C70D9FEC [92.919637ms]"
photoprism_1  | time="2020-05-06T17:10:21Z" level=info msg="mediafile: taken at 2020-05-06 17:10:20.123666351 +0000 UTC"
photoprism_1  | time="2020-05-06T17:10:21Z" level=info msg="index: no latitude and longitude in metadata"
photoprism_1  | time="2020-05-06T17:10:21Z" level=info msg="photo: changed photo title to “Unknown / 2020”"
photoprism_1  | time="2020-05-06T17:10:21Z" level=info msg="import: added main png file 2020/05/20200506_171020_C70D9FEC.png"
photoprism_1  | time="2020-05-06T17:10:21Z" level=info msg="import: deleted empty directory /photoprism/import/upload/1588785019465"
photoprism_1  | time="2020-05-06T17:10:21Z" level=info msg="import completed in 1 s"
```

**Comment by Aidan-OS** [comment] 2020-05-06 17:19
Files upload to the demo without issue, however I am unable to test with the files I am currently trying on my personal server due to their NSFW nature. Could this have been a problem with the NSFW Filter, and if so, what is the best method for fully removing all data on my server and then starting from scratch again?

**Comment by lastzero** [comment] 2020-05-06 17:21
Same problem with JPEG files? The quality filter would certainly "block" PNGs without additional metadata, as those are typically used for screenshots and not for photography. We only support PNG because many users were asking for it.

You can simply delete the database and re-index. If you use the built-in server, delete the database directory (or Docker volume).

**Comment by Aidan-OS** [comment] 2020-05-06 17:24
All files I have been uploading have been PNGs without metadata. If it is the case that you do not fully support them, I sadly will have to find another software.

**Comment by lastzero** [comment] 2020-05-06 17:30
We fully support them, but if there is no metadata, we can not provide additional value by searching it or show they position on a map. Professional digital asset management systems might be better suited, like companies use them for product photos.

**Comment by lastzero** [comment] 2020-05-06 17:32
We even support Exif headers in PNGs, which is not very common.

**Comment by Aidan-OS** [comment] 2020-05-06 17:36
After deleting the database (/root/Pictures), I started the container again. Now, after indexing, it claims there are 34 photos, however none appear:

![image](https://user-images.githubusercontent.com/1919827/81209501-a12e6b00-8f9e-11ea-9503-1b91ba86cbf0.png)

**Comment by lastzero** [comment] 2020-05-06 17:39
Did you fully reload the app in the browser? Otherwise the number will not update. Pictures is probably not the database, directory is named `database`. In our docker-compose.yml example it's a docker volume, you need to use `docker volume ls` to see all volumes and then `docker volume rm` to delete it, should be names something like ` photoprism_photoprism-database`.

**Comment by Aidan-OS** [comment] 2020-05-06 17:47
I seem to understand now. I am looking to upload photos and then give them tags manually.

I just uploaded 2 photos, one of which was recognized as a portrait. In the "Labels" section, I see the image as the thumbnail for "Portrait", however when I click on it, it tells me that there are no photos with that label.

This seems to me that the software is aware that my pictures are on the server, however is not showing them to me in any way so that I may add labels to them.

**Comment by lastzero** [comment] 2020-05-06 17:52
Sounds like the nsfw / private flag is still set somehow. You could run `photoprism config` (for example in a terminal with `docker-compose exec photoprism bash`) and see if it is turned on for any reason.

**Comment by lastzero** [comment] 2020-05-06 17:54
Do you need the upload for anything specific? Otherwise you could just copy the files to the originals / import directory or use WebDAV for remote file management.

**Comment by Aidan-OS** [comment] 2020-05-06 17:58
Yes. After further testing I have deemed that it is some sort of problem with the NSFW tag, as uploading metadataless SFW png files works perfectly fine.

When running `photoprism config` I that `detect-nsfw` is false and `upload-nsfw` is true

The reason I am setting this up is for an artist who creates both NSFW and SFW works. They wish to be able to easily browse files they have uploaded and share them with select people over the internet. They do not like their files being hosted on hardware they do not control, thus I am assisting the movement to a small, locally hosted image server.

**Comment by lastzero** [comment] 2020-05-06 18:01
I see, makes sense. They could connect via WebDAV (supported by all major operating systems), it's also more convenient than web upload. You need to set a password in the config, the URL to connect is `example.com/originals/` and `example.com/import/`, whatever way of adding images you like.

**Comment by lastzero** [comment] 2020-05-06 18:03
It's already late here, I'll test NSFW tomorrow. Maybe there is an issue with our configuration.

**Comment by Aidan-OS** [comment] 2020-05-06 18:05
Is this the only way of bypassing the problems that seem to exist with the NSFW filter? I would prefer to leave them with an all in one and simple package, as they are not very technologically literate. 

The matter is not pressing and I have not found another software that appears to meet all our requirements, so I would be glad to wait for a possible fix.

**Comment by lastzero** [comment] 2020-05-06 18:07
If the NSFW filter is broken, we will fix it - just not tonight ;)

**Comment by pluja** [comment] 2020-05-07 07:03
I had the same issue, I just had to disable the "filter low quality pictures" option, and they all appeared. Resolution of my photos was full HD, so I guess there is something wrong?

**Comment by lastzero** [comment] 2020-05-07 07:18
@pluja Resolution is just one information that is used for the filter, exif information as created by a typical, modern camera is also important. High-res pictures can as well be screenshots or wallpapers. We want to make it easy to browse personal photography. Some people might use PNG without Metadata for this, but not the majority. I agree, we should not name it "quality filter" as this makes everyone think the resolution is not good enough or it's an ugly picture... "require a review for non-photographic or low-resolution images" was a bit long for a checkbox label... suggestions welcome.

@Aidan-OS Tested upload this morning with heaps of NSFW PNG images, and had no issues after setting the NSFW flags as described (`photoprism --detect-nsfw=false --upload-nsfw start`) and disabling private and quality filter in Settings. However, updating to Chrome 81 broke the upload file selector. That needs to be fixed now.

**Comment by lastzero** [comment] 2020-05-07 08:28
@Aidan-OS @pluja Added an additional check before running NSFW detection in the backend and improved the quality filter description. New Docker images for testing should be available in about one hour.

**Comment by lastzero** [comment] 2020-05-07 13:34
Updated getting started for docker-compose: https://github.com/photoprism/photoprism-docs/commit/3a8cce4191ed7b5218d96d8a58c75c7b23621298

It was in fact a bit old and not accurate anymore.

**Comment by lastzero** [comment] 2020-05-07 14:59
Also updated our pure Docker docs and added more details to the docker-compose guide: https://docs.photoprism.org/en/latest/getting-started/docker-compose/

Hope this is good for now, let us know when you have questions or spotted a typo! I'll close this ticket as the comments are getting way to long for anyone to read.

**Closed by lastzero** 2020-05-07 14:59 UTC
Labels: bug, docs, easy, help wanted
