### ISSUE TITLE
Missing Photos with WebDav via PhotoSync

### ISSUE THREAD

**Issue by mirisbowring** [photoprism/photoprism#2647] opened 2022-08-25 15:01 UTC
#### 1. What is not working as documented?

I am using PhotoSync on my Android Mobile and it was working great. Some Weeks ago, i discovered, that not all of my photos are placed within Photoprism.
I do not use the auto upload of photosync. I take Pictures with my Mobile Camera and manually select my fotos to be uploaded to Photoprism.

The Transfer popup of PhotoSync marks every transfer as successfull and the loading bar is at a decent speed -> nothing suspicious here.

When ich check the import folder of Photoprism (before importing), some files are already missing. Though, the logs are counting the correct amount of files.
In my case i uploaded 67 Files (see lines in log below) but only 64 are available in import folder.

#### 2. How can we reproduce it?

1. Take some Photos (around 100) on your smartphone camera
2. open PhotoSync (with WebDav DLC)
3. Select all the 100 Photos and upload them
4. Check Photoprism Logs and Import Folder

#### 3. What behavior do you expect?

All files should be there, or at least an error message

#### 4. What could be the cause of your problem?

I really don't know since there is no message on the console.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

```logs
photoprism-1  | time="2022-08-25T14:48:17Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-25_16-11-15-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:18Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-25_16-11-11-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:18Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-25_16-10-59-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:19Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-25_16-10-58-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:19Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-25_14-59-45-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:19Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-25_14-12-17-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:20Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-24_22-20-38-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:20Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-24_22-20-36-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:20Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-24_09-20-47-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:21Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_20-34-21-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:21Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_14-57-51-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:21Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_14-55-34-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:22Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_13-06-07-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:22Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-46-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:23Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-47-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:24Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-45-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:24Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-46-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:25Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-44-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:25Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-45-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:26Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-23-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:27Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-21-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:28Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-24-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:29Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-20-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:29Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-19-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:30Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-54-04-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:33Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-50-53-785_HUAWEI%20LYA-L29.mp4"
photoprism-1  | time="2022-08-25T14:48:34Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-47-53-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:34Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-47-50-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:35Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-45-45-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:36Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-45-40-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:36Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-45-31-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:37Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-42-20-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:38Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-41-53-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:38Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-41-53-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:38Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-41-51-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:39Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-41-17-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:39Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-41-15-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:40Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-41-12-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:41Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-41-10-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:41Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-41-04-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:41Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-41-01-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:42Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-40-59-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:42Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-40-50-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:45Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-23_12-40-44-879_HUAWEI%20LYA-L29.mp4"
photoprism-1  | time="2022-08-25T14:48:46Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_21-05-23-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:46Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_12-39-05-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:46Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_12-39-02-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:47Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_12-38-57-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:47Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_12-38-54-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:47Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_12-38-55-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:48Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_12-38-41-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:54Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_12-38-26-211_HUAWEI%20LYA-L29.mp4"
photoprism-1  | time="2022-08-25T14:48:54Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_12-36-32-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:55Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_12-30-24-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:55Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_12-29-27-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:56Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_11-45-38-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:56Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_11-45-37-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:57Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_11-45-36-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:58Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_11-45-30-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:58Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_11-38-52-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:59Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-22_11-38-48-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:48:59Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-21_15-45-12-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:49:00Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-21_15-25-05-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:49:00Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-21_15-24-45-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:49:01Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-21_15-24-39-000_HUAWEI%20LYA-L29.jpg"
photoprism-1  | time="2022-08-25T14:49:13Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-20_21-59-54-506_HUAWEI%20LYA-L29.mp4"
photoprism-1  | time="2022-08-25T14:49:13Z" level=info msg="webdav: PUT /import/HUAWEI%20LYA-L29/Camera/2022-08-20_08-14-04-000_HUAWEI%20LYA-L29.jpg"

```
#### 6. Which software versions do you use?

(a) [PhotoPrism® Plus](https://photoprism.primboard.de/about) Build [220730-0e1222c83](https://docs.photoprism.app/release-notes/)

(b) Database Type & Version: MariaDB 

(c) Operating System Types & Versions: Linux (UnraidOS)

(d) Browser Types & Versions: Firefox, Chrome

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? -> No

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: i5 7500

(b) Physical Memory & Swap Space in GB: 32GB & 0GB

(c) Storage Type: 4TB SSD

(d) Anything else that might be helpful to know? -> UnraidOS?

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

OPNSense with NGINX Plugin as reverse Proxy

**Comment by graciousgrey** [comment] 2022-08-26 07:41
Do you know what files are missing?  Is it possible that the missing ones are the videos? 

We had a case before, where it seemed like all files have been transferred but videos have been skipped (which was only visible after a refresh of PhotoSync) because there was some kind of setting to not transfer videos with mobile data.

**Comment by mirisbowring** [comment] 2022-08-26 08:40
This is not dedicated to Videos. In the case above, 3 Videos has been added but 4 Photos are missing.

Some Days ago i had the case that photos and videos are missing.

**Comment by graciousgrey** [comment] 2022-08-26 08:57
And after a refresh of PhotoSync those are still marked as already transferred?

I will try to reproduce this later toady.

**Comment by lastzero** [comment] 2022-08-26 09:02
Just a few ideas from my side (without having checked the above comments in detail):

- Do you move or copy files from the import folder to originals? Have you checked if the images are actually missing from your library?
- Could it be that the import is already partially complete and therefore the files have already been moved?
- Maybe PhotoSync remembers what has already been transferred and is configured not to do it twice, but just mark the file as done?

*Note that GitHub Discussions would be better to figure all this out before opening a bug ticket, as this effectively interrupts whatever we're doing right now.*

**Comment by mirisbowring** [comment] 2022-08-26 12:34
@graciousgrey All those images are marked as already transferred. Even after deleting the images on the server (import folder and/or photoprism itself) and retransferring, the same items are missing.

@lastzero generally i import with moving. However this is not the point here since the items are missing right after upload (before any processing of photoprism started - independent of manual or automatic processing).

Therefore this is definitely a bug and should not be moved to a discussion. The items itself should be ok since i can upload them via photoprism upload in mobile Webbrowser and everything is working as expected.

PhotoSync uploads all files i marked (it does not matter if it was already transferred or not).

**Comment by lastzero** [comment] 2022-08-26 12:59
Reverting to discussions or technical support via email (for sponsors) would avoid notifying all contributors by email after every new comment.

Our base case is currently not that files randomly disappear. Someone else should have noticed that as well by now? Could as well be a proxy, network or hardware problem.

At a minimum this issue requires more research as it's impossible to fix bugs that can't be reproduced. For example, try importing via copy instead of move! 👍

**Closed as completed** 2022-08-29 10:01 UTC
Labels: help wanted, needs-analysis
