### ISSUE TITLE
Portrait photos streched

### ISSUE THREAD

**Issue by tjlejeune** [photoprism/photoprism#469] opened 2020-08-17 14:18 UTC
Any photo taken in portrait mode is horribly distorted.  Also an option to delete photos from photo prism would be great

**Comment by tjlejeune** [comment] 2020-08-23 23:46
Here's an example of the stretching and a pic of the file details. I've viewed the same photo in emby, Plex, my S8's gallery and piwigo so I just assumed it was a bug in photoprism.  I'm running the latest docker on unraid
![Screenshot_20200823-184118_Chrome](https://user-images.githubusercontent.com/4181464/90991627-441bec80-e570-11ea-8b51-51a46fcdd2b3.jpg)


![Screenshot_20200823-183543_Chrome](https://user-images.githubusercontent.com/4181464/90991610-159e1180-e570-11ea-870a-a03c4ae1ca20.jpg)

**Comment by lastzero** [comment] 2020-08-24 05:14
Did you enable json sidecar files? Reading the orientation via exiftool might fix it.

We had such a case before and found out that the file contained multiple orientation values, so photoprism randomly got the wrong value while other Exif implementations randomly picked the right value.

**Comment by lastzero** [comment] 2020-08-24 10:28
See https://github.com/dsoprea/go-exif/issues/40 and https://github.com/photoprism/photoprism/issues/348

Use this command to see all orientation tags within a JPEG file:

```
exiftool -a -all -G1  -n filename.jpg | grep Orientation
```
Example output: 

```
[IFD0]          Orientation                     : 1
[XMP-tiff]      Orientation                     : 256
```

**Comment by tjlejeune** [comment] 2020-08-25 03:17
[IFD0]          Orientation                     : 6
[IFD1]          Orientation                     : 6

**Comment by lastzero** [comment] 2020-08-25 04:35
In that case, we need an example file to debug this further... You can also send it to hello@photoprism.org

**Comment by lastzero** [comment] 2020-08-26 08:13
Works for me when JSON sidecar files are enabled (`PHOTOPRISM_SIDECAR_JSON: "true"`) and the preview picture in your screenshot looks good too / the same:

![Screenshot 2020-08-26 at 09 56 16](https://user-images.githubusercontent.com/301686/91276892-68e7ae00-e782-11ea-8c71-64413c9c6dab.png)

If you enabled JSON sidecar files in the config, I assume there must be bad metadata cached and / or existing thumbnails for this photo need to be removed / rerendered.

Reason PhotoPrism can't detect the orientation without Exiftool / JSON sidecar files is that the Exif header seems broken. The parser we use does a bit more validation and sticks more to the standard than Exiftool.

The exact error is: 

```
length of size read for non-special marker (e5) is unexpectedly not more than two
```

@dsoprea is the author of [go-exif](https://github.com/dsoprea/go-exif), maybe he can tell you more about it?

**Comment by dsoprea** [comment] 2020-08-26 15:44
@lastzero Can you send the image to me?

**Comment by tjlejeune** [comment] 2020-08-26 15:55
I totally missed the comment about enabling JSON sidecar. Will try as soon as I can

**Comment by dsoprea** [comment] 2020-08-26 23:12
These have duplicate values:

```
...
IFD-PATH=[IFD] ID=(0x0100) NAME=[ImageWidth] COUNT=(1) TYPE=[LONG] VALUE=[[4032]]
IFD-PATH=[IFD] ID=(0x0101) NAME=[ImageLength] COUNT=(1) TYPE=[LONG] VALUE=[[2268]]
...
IFD-PATH=[IFD1] ID=(0x0100) NAME=[ImageWidth] COUNT=(1) TYPE=[LONG] VALUE=[[496]]
IFD-PATH=[IFD1] ID=(0x0101) NAME=[ImageLength] COUNT=(1) TYPE=[LONG] VALUE=[[280]]
...
```

These only have one set of values:

```
IFD-PATH=[IFD/Exif] ID=(0xa002) NAME=[PixelXDimension] COUNT=(1) TYPE=[LONG] VALUE=[[4032]]
IFD-PATH=[IFD/Exif] ID=(0xa003) NAME=[PixelYDimension] COUNT=(1) TYPE=[LONG] VALUE=[[2268]]
```

Since PP is calling `exif.GetFlatExifData()` to get the tags and then checks for the presence of the Image* tags before the Pixel* tags, I can only assume that the second set is overriding the first, and that's the one that you're using.

I would use the dimensions from the actual pixel-data and ignore the dimensions as reported by EXIF. We've seen so much insanity with the EXIF data.

**Comment by lastzero** [comment] 2020-08-27 05:37
@dsoprea we use the actual pixels for width & height, only the orientation was wrong since the error prevents reading Exif data completely.

**Comment by dsoprea** [comment] 2020-08-27 05:53
Firgot that you mentioned that you had one. I didn't get an error. Have a
stacktrace?

**Comment by tjlejeune** [comment] 2020-08-27 11:54
Ok, noob question. Can't find the sidecar JSON file. Checked /photoprism/cache and only sessions.json exists. Added photoprism_sidecar_json = true and photoprism_sidecar_ymal = true to docker variables. Am I looking in the right place or do I need to create it?

**Comment by lastzero** [comment] 2020-08-27 12:15
You also need to reindex. Generated sidecar files will be stored in the storage folder.

**Comment by dsoprea** [comment] 2020-08-28 05:34
Bump .https://github.com/photoprism/photoprism/issues/469#issuecomment-681574056

**Comment by lastzero** [comment] 2020-08-28 07:33
@dsoprea Could "fix" it with a fallback to `exif.SearchFileAndExtractExif(fileName)` as the above mentioned error was returned by `go-jpeg-image-structure` only:

```
jpegMp := jpegstructure.NewJpegMediaParser()
sl, err := jpegMp.ParseFile(fileName)
```

Tested the new `go-exif` version as well but had to revert the upgrade as it broke existing tests in our `meta` package:

```
START|   Exif/image-2011.jpg
     |     exif_test.go:190: 
     |         	Error Trace:	exif_test.go:190
     |         	Error:      	Not equal: 
     |         	            	expected: "GT-I9000"
     |         	            	actual  : "string with binary data (9 bytes)"
     |         	            	
     |         	            	Diff:
     |         	            	--- Expected
     |         	            	+++ Actual
     |         	            	@@ -1 +1 @@
     |         	            	-GT-I9000
     |         	            	+string with binary data (9 bytes)
     |         	Test:       	TestExif/image-2011.jpg
```

**Comment by lastzero** [comment] 2020-08-28 07:37
@tjlejeune Your issue should be fixed, even without JSON sidecar files, when the next Docker build is available. I didn't add your photo to our official test suite as it is private. If you have a file we can publicly use, we can add that to avoid regressions.

**Comment by tjlejeune** [comment] 2020-08-30 00:48
Just reindexed and everything is working just right. Unfortunately that made it difficult for me to reproduced the issue with any new photos because 99% of my photos are of my kids. This photo should have the same issue, but can't check. Anyways, thank you for the help. 
![IMG_20200827_155908](https://user-images.githubusercontent.com/4181464/91648693-21864980-ea30-11ea-97fe-b8f6b034c711.jpg)

**Closed** 2020-09-03 06:28 UTC
Labels: bug, done, question
