### ISSUE TITLE
UX: Restore scroll position when navigating back

### ISSUE THREAD

**Issue by whoshoe** [photoprism/photoprism#2597] opened 2022-08-07 03:30 UTC
#### 1. What is not working 

After clicking the download button on iOS and using the "X" to close the image view, the scrolling position is not remembered. Page goes back to the top.

#### 2. How can we reproduce it?

1. On iOS scroll down and open an image
2. Click on the download button, click "Done" and click "X" to go back to the list view.
3. Page goes back to the top

#### 3. What behavior do you expect?

Expect scrolling position to be remembered.

#### 4. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, Build [220730-0e1222c83](https://docs.photoprism.app/release-notes/)

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: iOS 15.6

(d) Browser Types & Versions: Safari on iPhone

**Comment by lastzero** [comment] 2022-08-07 03:46
@heikomat might be related to the virtual scrolling? AFAIK it was working before.

**Comment by heikomat** [comment] 2022-08-07 04:52
@lastzero possible. Would need to test that. Might have a look at it later, but I don't know if I find time today

**Comment by heikomat** [comment] 2022-08-07 07:59
@whoshoe two questions:

1. after clicking the x, is the scroll position instantly reset, or does it instead scroll to the top?

The "x" to close the image and the button to scroll to the top are at a similar location, maybe one click somehow triggers both.

2. Does it always happen when closing an image using the "x", or only after downloading it?

**Comment by whoshoe** [comment] 2022-08-08 02:02
> 1. after clicking the x, is the scroll position instantly reset, or does it instead scroll to the top?

I didn't see any scrolling actions being preformed. After clicking the x, the page just shows the top as if I was at the top.


> 2\. Does it always happen when closing an image using the "x", or only after downloading it?

Nope. Going into the image view and exiting using the "x" without clicking download DOES remember the position. Loss of scrolling position only happens after the download page being brought up.

**Comment by lastzero** [comment] 2022-08-10 19:42
Note I've fixed a similar issue in https://github.com/photoprism/photoprism/commit/5d7448d2df3d05580489b3e208ea09b8935bf69b by disabling history mode in full screen view when releasing the [search view render performance improvements](https://github.com/photoprism/photoprism/pull/2433) (probably also worked before):

https://github.com/photoprism/photoprism/blob/5d7448d2df3d05580489b3e208ea09b8935bf69b/frontend/src/common/viewer.js#L105

**See also:**
- #896

For this, we implemented the following event handler...

https://github.com/photoprism/photoprism/blob/fd27f88718e82074929cf29739019c187449acaa/frontend/src/app.js#L123-L135

It may need updating to be compatible with the new search result views.

**Comment by heikomat** [comment] 2022-08-19 18:28
I can confirm this issue, but it seems to only happen when the app is installed to the homescreen as PWA, not when used directly in the browser.
It seems that the "download image" part is fullscreen when used from the PWA, but only a popup when used from the browser.
This could mean that in the PWA, the page is reloaded while on the browser it's not, which would fit the explanation of @lastzero, that the cause is probably the disabled history-mode.

I tested it on demo.photoprism.app using an iphone 13 mini simulator with iOS 15.5

<table>
<tr>
<td>

**From browser**

https://user-images.githubusercontent.com/20770029/185683295-4c462305-7b03-4890-866c-4b59194ec18f.mp4

</td>
<td>

**From homescreen (PWA)**

https://user-images.githubusercontent.com/20770029/185683883-8850bef4-f3a6-4da1-b66f-ae31f6a43be0.mp4

</td>
</tr>

</table>

I will now see what can be done about history mode.

**Comment by lastzero** [comment] 2022-08-19 18:32
There's another closed issue for iOS downloads in PWA mode which required changes (compared to non PWA mode) to work.

**Comment by heikomat** [comment] 2022-08-19 18:53
Even with history-mode enabled, downloading pictures in PWA mode resets the scroll-position by seemingly reloading the page.
@whoshoe how are you accessing photoprism on your phone? Do you use the PWA?

@lastzero do you have a link to the issue you mention? I'd like to have a look at the changes

**Comment by heikomat** [comment] 2022-08-19 19:53
I think i found it: https://github.com/photoprism/photoprism/commit/b90599ddfcb75f2a570d0a50c2f175d2b344c9eb

**Comment by heikomat** [comment] 2022-08-19 22:54
i looked around a little, but it seems that there is unfortunately still no good way to prevent the page-reload after downloading in PWA mode.

it is exactly as @lastzero described [a couple comments earlier](https://github.com/photoprism/photoprism/issues/2597#issuecomment-1211188162). The scroll position is lost on navigation.
For non-virtualized views without lazy-loading there exists this code to jump back to the last scroll position after a navigation (the code shown in the linked comment).

This is however not compatible with the lazy-loaded views (virtualization is not an issue).
Jumping down to the last scroll position is not trivial when that position doesn't exist yet.

It is probably possible to save the clicked image index in addition to the scroll-pos.
The index could then be used to know how many images were required to be at that scroll position, so they can be loaded at once. Thanks to the virtualization that would only load the models, not the actual thumbnails.

If on a reload, we'd load "last saved index" amount of images, then render the placeholders and scroll to the bottom, we'd reach a scroll-position that is very near the actual position before the reload. Not exact, but probably good enough.
We might ignore the actual last scroll-position here. The browser-size might have changed, for example due to rotation of the phone or resizing of the browser window.

Just some thoughts.

**Comment by whoshoe** [comment] 2022-08-21 14:34
> @whoshoe how are you accessing photoprism on your phone? Do you use the PWA?

Yes, I use PWA mode.

**Comment by heikomat** [comment] 2022-08-21 18:42
As it turns out, a very similar feature to what i thought of is already part of the existing "remember scroll-pos on back-navigation"-feature for albums.

If we implement the same feature for the regular photos/results view (basically just apply [these changes](https://github.com/photoprism/photoprism/commit/67e655f6d0b7efd9060ad9c63dc4a1eb8aa3d53e#diff-b6643c88b6d5dc11dd061f10b0b6af0879ee301a84161673b789ebf5a16528f4) to [this file](https://github.com/photoprism/photoprism/blob/5d0a2ccf1bf981e3e91c14464f241cc8a585f857/frontend/src/pages/photos.vue)), it should fix the PWA-download-issue. I already confirmed that closing the download-window in PWA-mode does infact trigger a back-navigation, so remembering the scroll-position should work.

There is one issue though, and that is that implementing this would cause photoprism to always load hundrets or thousands of photos on future visits, because of https://github.com/photoprism/photoprism/issues/2627. If that is fixed, fixing this issue should be somewhat straight forward!

**Comment by heikomat** [comment] 2022-08-26 22:50
@whoshoe and @lastzero, i have a working fix (see https://github.com/photoprism/photoprism/pull/2648)

It required enabling history mode, detecting back-navigation and implementing the offset-remember-feature from albums for photos-search aswell.
It is also not tested enough, and i can currently not foresee all cases that would require testing, because my concentration for today is exhausted.

It is therefore probably unfit to be merged yet, but with a little love, this can be the fix for this issue.

**Comment by lastzero** [comment] 2022-08-27 00:04
Excellent, thank you! We've pushed (long overdue) mobile navigation improvements today and updated all our servers & Docker images. Meaning I'll take a break now., so let's see who gets it done first... 😁

![Screenshot_20220827_014827](https://user-images.githubusercontent.com/301686/187005579-606bd1bf-8045-4817-a652-3b92352280ba.jpg)

**Comment by heikomat** [comment] 2022-08-27 22:44
@lastzero i reviewed my code with a fresh head, cleaned it up a little, did some more testing and uploaded a test docker-image ([`ghcr.io/heikomat/photoprism:backnav`](https://github.com/heikomat/photoprism/pkgs/container/photoprism/39385259?tag=backnav)).

I'm now a lot more confident in the changes than i was yesterday.
Only thing missing now as far as i can tell is that [i don't know what issues you had with history-mode](https://github.com/photoprism/photoprism/issues/2477#issuecomment-1221022865), so i can't check if they still exist.

**Comment by lastzero** [comment] 2022-08-31 18:41
We'll try to release what's in our [current development preview](https://docs.photoprism.app/release-notes/#development-preview) tomorrow so we can merge this next to get it tested by more users!

**Comment by graciousgrey** [comment] 2022-10-12 15:45
I finally had time to test this in detail.

The case from the original bug description:

- Scroll down in search section and download someting from fullscreen mode
- Click "Done" and click "X" to go back to the card/mosiac/list view.

 is working now. Thank you for fixing this @heikomat :) 

I found some related cases where the scroll position is not remembered:

**Using swipe gesture instead of x to close fullscreen mode**

- Scroll down in search section and download someting from fullscreen mode
- Click "Done" and use **swipe gesture** to go back to the card/mosiac/list view.

**Scroll down within an album/moment/calendar/state/folder**

- Scroll down in **album/moment/calendar/state/folder** section and download someting from fullscreen mode
- Click "Done" and use  x to go back to the card/mosiac/list view.

**Scroll down search result**

- **Search for something**, e.g. label:building
- Scroll down and download someting from fullscreen mode
- Click "Done" and use  x to go back to the card/mosiac/list view.

**Download from context menu**

- Scroll down in search section and download someting **using the context menu**
- Click "Done" 

**Download from edit dialog**

- Scroll down in search section and **open the files tab of the edit dialog of an image and download someting**
- Click "Done"

**Comment by heikomat** [comment] 2022-10-12 15:55
Thanks for testing!

Sounds like these cases could be fixed by remembering more state before navigating (like the current search)

Can't promise anything, but I might have a look on the weekend

**Comment by heikomat** [comment] 2022-10-14 23:19
@graciousgrey although it was definitely pretty hard to find, it turns out that all issues you mentioned share the same root cause!
I created a fix for all of them [here](https://github.com/photoprism/photoprism/pull/2782) that even improves upon the original fix by eliminating any extra reloads and jumping around!

**Comment by graciousgrey** [comment] 2022-10-18 13:23
I can confirm that all issues are solved by https://github.com/photoprism/photoprism/pull/2782 :)

**Closed as completed** 2022-11-02 11:09 UTC
Labels: bug, released, ux
