### ISSUE TITLE
File indexing fails to read incorrect altitude from a 2013 Motorola X smartphone

### ISSUE THREAD

**Issue by dannns** [photoprism/photoprism#2586] opened 2022-08-03 14:28 UTC
File indexing fails to read incorrect altitude, possibly a negative value overflow, from a 2013 Motorola X smartphone.

This happens when doing a Library Indexing that contains files produced by a Motorola X (sample attached).

Invalid exif line:
GPS Altitude                    : 4294967275 m Below Sea Level

Reference altitude reported by Google Photos json:
  "geoData": {
...
    "altitude": -4.294967275E9,
...
  },

Log:
2022-08-03 09:27:52 ERRO index: failed adding main jpg file 'Google Photos/Photos from 2014/IMG_20141108_103948.jpg'
2022-08-03 09:27:52 ERRO index: Error 1264: Out of range value for column 'photo_altitude' at row 1 / record not found in 'Google Photos/Photos from 2014/IMG_20141108_103948.jpg' (find or create photo)
2022-08-03 09:27:52 INFO index: matched 3 labels with IMG_20141108_103948.jpg [341.536213ms]
2022-08-03 09:27:51 INFO media: IMG_20141108_103948.jpg was taken at 2014-11-08 15:39:49 +0000 UTC (meta)
2022-08-03 09:27:51 INFO index: found 2 faces in IMG_20141108_103948.jpg [333.822548ms]

PhotoPrism® CE
Build 220730-0e1222c83
AMD64
MariaDB
Ubuntu 22.04 docker host
Chrome
Intel Core i7
6GB RAM
Network storage from Synology NAS mounted docker volumes

https://user-images.githubusercontent.com/1377755/182632988-43ee2fdb-ee1c-45e4-9373-29b5e1f2891a.jpg

Edit: Updated incorrect related issue.
Possibly related to: https://github.com/photoprism/photoprism/issues/736

**Comment by lastzero** [comment] 2022-08-03 14:42
Does the original file as downloaded from Google Photos contain the altitude? AFAIK Google tends to remove some or all metadata. You can check this with Exiftool. If it is only included in the proprietary Google JSON file, it would be an improvement or feature request, not a bug. Note we are currently on vacation.

**Comment by lastzero** [comment] 2022-08-03 14:46
Also note `-4*10^9` is indeed not a valid altitude. Might be somewhere in the next galaxy.

**Comment by lastzero** [comment] 2022-08-03 14:50
If it's just a validation issue and you are OK with ignoring the invalid value, feel free to send a pull request. Should be easy to fix in the internal meta and/or entity package.

**Comment by dannns** [comment] 2022-08-03 15:05
The original files is what is referenced, and the exiftool does report that invalid altitude from a galaxy far away.

I think it is just validation, and the invalid value should be treated as not-provided altitude.

**Comment by dannns** [comment] 2022-08-03 15:07
Edit: Updated incorrect related issue.
Possibly related to: https://github.com/photoprism/photoprism/issues/736

**Comment by graciousgrey** [comment] 2023-07-17 14:11
This should be fixed by: 
- https://github.com/photoprism/photoprism/issues/3182

**Comment by cxcxcxcx** [comment] 2023-08-01 15:23
I have a similar Motorola phone XT907 (i.e. [Droid Razr M](https://en.wikipedia.org/wiki/Droid_Razr_M) ), confirmed the issue is resolved after updating to latest docker image.

**Closed as completed** 2023-08-01 15:48 UTC
Labels: duplicate
