### ISSUE TITLE
Photoprism failed to upload files with error  "invalid cross-device link"

### ISSUE THREAD

**Issue by selvakumarEsra** [photoprism/photoprism#136] opened 2019-08-28 16:06 UTC
I am running Photoprism using docker. When I tried uploading file i am getting below error.

ERRO[2019-08-28T16:00:27Z] could not move file to "": rename /home/photoprism/Pictures/Import/upload/1567007435464/
DSC_0019.JPG /home/photoprism/Pictures/Originals/2017/05/20170511_191901_3CEC15593D80.jpg: invalid cross-device link 

i ma uisng this cammand to start the service
docker run -p 2342:2342 -d --name photoprism   -v ~/Pictures:/home/photopri
sm/Pictures/Originals photoprism/photoprism

**Comment by baembel08** [comment] 2019-08-29 07:33
Hi, I've been testing around this week with photoprism this week, so I'm also a new user. As I'm using Windows OS as client operating system , I always start with an abosolut path like C:/pictures:/home....... . 
You have to share drive C: or whatsoever in Docker and configure the service for using Linux Containers

**Comment by lastzero** [comment] 2019-09-08 03:42
Yes, maybe ~ in the docker compose config can be an issue on some operating systems. Was this Windows? We've never tested our app on Windows so far.

PS: Sorry for the delay, I had to complete a commercial project to fund this. Development continues soon!

**Comment by baembel08** [comment] 2019-09-10 05:58
Hi, yes I've tested with Windows 10. When I'm using ~ , I am directed to my home drive C:\Users\xxxx.
Also ./ doesn't work for me. If you store the photos in your home drive , it might work, otherwise the absolut path somewhere on the laptop like E:\mypictures\holidays:....... as part of the volume mount works definitly.

**Comment by RUANHAOANDROID** [comment] 2019-09-22 04:20
Last login: Sun Sep 22 08:35:42 on ttys002
macbook-pro:photos rh$ docker-compose exec photoprism bash
photoprism@4dc54651ce80:~$ photoprism import
INFO[2019-09-22T00:41:29Z] importing photos from /home/photoprism/Pictures/Import 
INFO[2019-09-22T00:41:29Z] moving main raw file "100D5600/DSC_0350.NEF" to "/home/photoprism/Pictures/Originals/2019/07/20190720_202656_EAB15A4EABA7.nef" 
ERRO[2019-09-22T00:41:29Z] could not move file to "/home/photoprism/Pictures/Originals/2019/07/20190720_202656_EAB15A4EABA7.nef": rename /home/photoprism/Pictures/Import/100D5600/DSC_0350.NEF /home/photoprism/Pictures/Originals/2019/07/20190720_202656_EAB15A4EABA7.nef: invalid cross-device link 
ERRO[2019-09-22T00:41:29Z] could not index "/home/photoprism/Pictures/Originals/2019/07/20190720_202656_EAB15A4EABA7.nef" after import: file does not exist: /home/photoprism/Pictures/Originals/2019/07/20190720_202656_EAB15A4EABA7.nef

**Comment by RUANHAOANDROID** [comment] 2019-09-22 04:24
Nothing under the home folder @
![屏幕快照 2019-09-22 12 23 27](https://user-images.githubusercontent.com/10151414/65382281-de0d6080-dd33-11e9-801f-f4ec72a24c2a.png)

**Comment by lastzero** [comment] 2019-09-23 18:27
@RUANHAOANDROID Did you check the volumes section in the docker-compose.yml? Not sure if imports / exports is mounted by default... if you're using it in development mode, the folders would be within your code / repo directory and not in home.

**Comment by lastzero** [comment] 2019-10-26 18:40
Any update on this?

**Comment by RUANHAOANDROID** [comment] 2019-10-27 08:09
谢谢，还没有。I am using  ： https://github.com/photoprism/photoprism/wiki/Docker-Compose

This is my docker-compose.yml

```xml
version: '3.3'

# Example docker-compose config file for production use
# Container image on Docker Hub: https://hub.docker.com/r/photoprism/photoprism/
# To keep photoprism running, add "restart: always"
#
# Usage: docker-compose up

services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: always #开启后一直运行
    ports:
      - 2342:2342 # [local port]:[container port]
  volumes:
      - "~/Photos/Originals:/home/photoprism/Pictures/Originals" # [local path]:[container path]
      - "~/Photos/Import:/home/photoprism/Pictures/Import" # [local path]:[container path] (optional)
      - "~/Photos/Export:/home/photoprism/Pictures/Export" # [local path]:[container path] (optional)
      - "photoprism-cache:/home/photoprism/.cache/photoprism" # keep thumbnail cache
      - "photoprism-database:/home/photoprism/.local/share/photoprism/resources/database" # keep database files

volumes: # keep this
  photoprism-cache:
    driver: local
  photoprism-database:
    driver: local
```

**Comment by toasti2000** [comment] 2019-10-28 13:00
I have the same issue on my Linux Mint. I did not change anything in my docker-compose.yml.

**Comment by kennyhyun** [comment] 2019-11-03 09:05
I had the same issue using `photoprism/photoprism:20190927`.
I am new to Photoprism but seems found a workaround.
Try
```
  volumes:
      - "~/Photos:/home/photoprism/Pictures" # [local path]:[container path]
      - "photoprism-cache:/home/photoprism/.cache/photoprism" # keep thumbnail cache
      - "photoprism-database:/home/photoprism/.local/share/photoprism/resources/database" # keep database files
```

**Comment by thielepaul** [comment] 2019-11-09 15:40
I can confirm this bug.
It occurs, when `/home/photoprism/Pictures/Import/upload/` and `/home/photoprism/Pictures/Originals/` are not on the same filesystem.

The problem is caused by the use of `os.Rename`:   
https://github.com/photoprism/photoprism/blob/develop/internal/photoprism/mediafile.go#L438

A possible fix is to copy and then delete the file, if it needs to be moved between filesystems as stated here:   
https://groups.google.com/forum/#!topic/golang-dev/5w7Jmg_iCJQ

**Comment by lastzero** [comment] 2019-11-11 19:03
@thielepaul Thanks for your feedback! Makes sense, that's why we didn't find this with our tests.

Maybe we can just fall back to copying if it's a different file system.

**Comment by lastzero** [comment] 2019-12-01 16:01
@thielepaul @kennyhyun Can you please tests again?

Build is running, should be available on Docker hub in about one hour (if tests don't fail), see
https://travis-ci.org/photoprism/photoprism/builds/619262937

**Comment by thielepaul** [comment] 2019-12-01 17:11
It is not working for me, see https://github.com/photoprism/photoprism/commit/895a1cf1755058fb55e9d988b4568f5b01679561#r36210952

**Comment by lastzero** [comment] 2019-12-01 19:29
@thielepaul You're right, hard to verify in our dev environment as we don't have different filesystems for testing... on our list. Hopefully fixed now, build is running.

**Comment by lastzero** [comment] 2019-12-01 20:26
Docker hub image updated 👍

**Comment by thielepaul** [comment] 2019-12-01 20:47
Nice work, now it works for me :rocket:

**Comment by lastzero** [comment] 2019-12-01 20:51
Thank you for testing! 🥳

**Closed by lastzero** 2019-12-01 20:51 UTC
Labels: bug, waiting
