### ISSUE TITLE
MariaDB: Make sure that a supported version is used

### ISSUE THREAD

**Issue by ZoXx** [photoprism/photoprism#2381] opened 2022-05-30 11:37 UTC
Hello,

since the last update (docker image) we've got problems while uploading pictures to folders (albums).

Here is our log:
2022-05-30 12:45:18 ERRO file: Error 1292: Incorrect datetime value: '0000-00-00' for column 'photo_taken_at' at row 1 while saving

**Comment by graciousgrey** [comment] 2022-05-30 12:00
Please follow our issue template for reporting potential bugs :)

**Comment by ZoXx** [comment] 2022-05-30 12:08
Will do next time.
But your  template is a lot to do and this bug exist since last image. I dont know how you can reproduce it but i cant be the only one with this behaviour. The other "bugs" doesnt fill in template too.

**Comment by graciousgrey** [comment] 2022-05-30 12:39
> But your template is a lot to do

This also applies to the development of this software and answering questions. 

Uploading photos to albums works without problems on our public demo and private instances. 
So it could be a problem with your setup or files.

**Comment by graciousgrey** [comment] 2022-05-30 13:18
Might also be caused by a failed migration - could you run the following command

`docker-compose exec photoprism photoprism migrations ls`

to see if there have been errors

**Comment by ZoXx** [comment] 2022-05-30 13:29
Here we go:
`
time="2022-05-30T13:27:57Z" level=info msg="PhotoPrism® needs your support!"
time="2022-05-30T13:27:57Z" level=info msg="Visit https://photoprism.app/membership to learn more."
|-----------------|---------|---------------------|---------------------|--------------------------------|
|       ID        | Dialect |     Started At      |     Finished At     |             Status             |
|-----------------|---------|---------------------|---------------------|--------------------------------|
| 20211121-094727 | mysql   | 2022-02-26 22:16:19 | 2022-02-26 22:16:19 | OK                             |
| 20211124-120008 | mysql   | 2022-02-26 22:16:19 | 2022-02-26 22:16:19 | OK                             |
| 20220329-030000 | mysql   | 2022-05-17 03:02:35 | 2022-05-17 03:02:35 | OK                             |
| 20220329-040000 | mysql   | 2022-05-17 03:02:35 | -                   | Error 1064: You have an        |
|                 |         |                     |                     | error in your SQL syntax;      |
|                 |         |                     |                     | check the manual that          |
|                 |         |                     |                     | corresponds to your MySQL      |
|                 |         |                     |                     | server version for the right   |
|                 |         |                     |                     | syntax to use near 'IF EXISTS  |
|                 |         |                     |                     | idx_albums_album_filter ON     |
|                 |         |                     |                     | albums' at line 1              |
| 20220329-050000 | mysql   | 2022-05-17 03:02:35 | 2022-05-17 03:02:37 | OK                             |
| 20220329-060000 | mysql   | 2022-05-17 03:02:37 | 2022-05-17 03:02:40 | OK                             |
| 20220329-061000 | mysql   | 2022-05-17 03:02:40 | -                   | Error 1064: You have an error  |
|                 |         |                     |                     | in your SQL syntax; check      |
|                 |         |                     |                     | the manual that corresponds    |
|                 |         |                     |                     | to your MySQL server version   |
|                 |         |                     |                     | for the right syntax to use    |
|                 |         |                     |                     | near 'INDEX idx_files_photo_id |
|                 |         |                     |                     | ON files (photo_id,            |
|                 |         |                     |                     | file_primary)' at line 1       |
| 20220329-070000 | mysql   | 2022-05-17 03:02:40 | -                   | Error 1064: You have an error  |
|                 |         |                     |                     | in your SQL syntax; check      |
|                 |         |                     |                     | the manual that corresponds    |
|                 |         |                     |                     | to your MySQL server version   |
|                 |         |                     |                     | for the right syntax to use    |
|                 |         |                     |                     | near 'IF EXISTS photo_taken_at |
|                 |         |                     |                     | DATETIME AFTER photo_uid' at   |
|                 |         |                     |                     | line 1                         |
| 20220329-071000 | mysql   | 2022-05-17 03:02:40 | 2022-05-17 03:02:41 | OK                             |
| 20220329-080000 | mysql   | 2022-05-17 03:02:41 | -                   | Error 1064: You have an        |
|                 |         |                     |                     | error in your SQL syntax;      |
|                 |         |                     |                     | check the manual that          |
|                 |         |                     |                     | corresponds to your MySQL      |
|                 |         |                     |                     | server version for the right   |
|                 |         |                     |                     | syntax to use near 'IF EXISTS  |
|                 |         |                     |                     | media_id VARBINARY(32) AFTER   |
|                 |         |                     |                     | photo_taken_at' at line 1      |
| 20220329-081000 | mysql   | 2022-05-17 03:02:41 | -                   | Error 1064: You have an error  |
|                 |         |                     |                     | in your SQL syntax; check      |
|                 |         |                     |                     | the manual that corresponds    |
|                 |         |                     |                     | to your MySQL server version   |
|                 |         |                     |                     | for the right syntax to        |
|                 |         |                     |                     | use near 'UNIQUE INDEX         |
|                 |         |                     |                     | idx_files_search_media ON      |
|                 |         |                     |                     | files (media_id)' at line 1    |
| 20220329-083000 | mysql   | 2022-05-17 03:02:41 | 2022-05-17 03:02:41 | OK                             |
| 20220329-090000 | mysql   | 2022-05-17 03:02:41 | -                   | Error 1064: You have an        |
|                 |         |                     |                     | error in your SQL syntax;      |
|                 |         |                     |                     | check the manual that          |
|                 |         |                     |                     | corresponds to your MySQL      |
|                 |         |                     |                     | server version for the right   |
|                 |         |                     |                     | syntax to use near 'IF EXISTS  |
|                 |         |                     |                     | time_index VARBINARY(48) AFTER |
|                 |         |                     |                     | photo_taken_at' at line 1      |
| 20220329-091000 | mysql   | 2022-05-17 03:02:41 | -                   | Error 1064: You have an error  |
|                 |         |                     |                     | in your SQL syntax; check      |
|                 |         |                     |                     | the manual that corresponds    |
|                 |         |                     |                     | to your MySQL server version   |
|                 |         |                     |                     | for the right syntax to        |
|                 |         |                     |                     | use near 'UNIQUE INDEX         |
|                 |         |                     |                     | idx_files_search_timeline ON   |
|                 |         |                     |                     | files (time_index)' at line 1  |
| 20220329-093000 | mysql   | 2022-05-17 03:02:41 | 2022-05-17 03:02:42 | OK                             |
| 20220421-200000 | mysql   | 2022-05-17 03:02:42 | -                   | Error 1064: You have an error  |
|                 |         |                     |                     | in your SQL syntax; check the  |
|                 |         |                     |                     | manual that corresponds to     |
|                 |         |                     |                     | your MySQL server version for  |
|                 |         |                     |                     | the right syntax to use near   |
|                 |         |                     |                     | 'INDEX idx_files_missing_root  |
|                 |         |                     |                     | ON files (file_missing,        |
|                 |         |                     |                     | file_root)' at line 1          |
| 20220521-000001 | mysql   | 2022-05-25 03:02:43 | 2022-05-25 03:02:44 | OK                             |
| 20220521-000002 | mysql   | 2022-05-25 03:02:44 | 2022-05-25 03:02:45 | OK                             |
| 20220521-000003 | mysql   | 2022-05-25 03:02:45 | 2022-05-25 03:02:45 | OK                             |
|-----------------|---------|---------------------|---------------------|--------------------------------|

time="2022-05-30T13:27:57Z" level=info msg="closed database connection"

**Comment by ZoXx** [comment] 2022-05-30 15:28
So it's an official bug? The tag was set at least

**Comment by graciousgrey** [comment] 2022-05-30 15:53
Possibly, @lastzero will have a look as soon as possible

**Comment by gyto6** [comment] 2022-05-30 22:12
Did you check this command in MariaDB? It stopped the trouble to me.

`mysql_upgrade --user=root --password=<root_pwd>`

**Comment by lastzero** [comment] 2022-05-31 04:13
Please verify if you are using a supported mariadb version >= 10.5.12 and its service config includes the following environment variables as shown in our docker-compose.yml examples on dl.photoprism.app:

```
environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
```

If you do not use auto upgrade, our Troubleshooting Guide includes a section about MariaDB that explains how to upgrade it manually.

**Comment by ZoXx** [comment] 2022-05-31 07:24
> Please verify if you are using a supported mariadb version >= 10.5.12 and its service config includes the following environment variables as shown in our docker-compose.yml examples on dl.photoprism.app:
> 
> ```
> environment:
>       MARIADB_AUTO_UPGRADE: "1"
>       MARIADB_INITDB_SKIP_TZINFO: "1"
> ```
> 
> If you do not use auto upgrade, our Troubleshooting Guide includes a section about MariaDB that explains how to upgrade it manually.

iam using my own mysql docker database.
Latest docker image with mysql version 8.0.29

**Comment by lastzero** [comment] 2022-05-31 09:35
👉  https://docs.photoprism.app/getting-started/troubleshooting/#mysql-errors

**Comment by ZoXx** [comment] 2022-05-31 09:38
> 👉 https://docs.photoprism.app/getting-started/troubleshooting/#mysql-errors

MySQL Errors[¶](https://docs.photoprism.app/getting-started/troubleshooting/#mysql-errors)
↪ [Official support for MySQL 8 is discontinued](https://docs.photoprism.app/getting-started/#databases)

So not longer MYSQL Support and i have to switch to MariaDB?

**Comment by ZoXx** [comment] 2022-05-31 10:42
We switched from MYSQL to MariaDB and imported our sql database.
Now we can upload photos again but we cant create albums? There is no error in logs.

**Comment by ZoXx** [comment] 2022-05-31 12:36
The folders are created in the database, but they are not visible in Photoprism. In Photoprism there are no errors in the log. Also an indexing brings here no success.

There are no more problems with the images.

**Comment by lastzero** [comment] 2022-05-31 18:03
👉 https://docs.photoprism.app/getting-started/troubleshooting/mariadb/#incompatible-schema

**Comment by ZoXx** [comment] 2022-06-01 11:57
> 👉 https://docs.photoprism.app/getting-started/troubleshooting/mariadb/#incompatible-schema

`docker exec photoprism photoprism migrations ls`
time="2022-06-01T06:32:10Z" level=info msg="PhotoPrism® needs your support!"
time="2022-06-01T06:32:10Z" level=info msg="Visit https://photoprism.app/membership to learn more."
|-----------------|---------|---------------------|---------------------|--------------------------------|
|       ID        | Dialect |     Started At      |     Finished At     |             Status             |
|-----------------|---------|---------------------|---------------------|--------------------------------|
| 20211121-094727 | mysql   | 2022-02-26 22:16:19 | 2022-02-26 22:16:19 | OK                             |
| 20211124-120008 | mysql   | 2022-02-26 22:16:19 | 2022-02-26 22:16:19 | OK                             |
| 20220329-030000 | mysql   | 2022-05-17 03:02:35 | 2022-05-17 03:02:35 | OK                             |
| 20220329-040000 | mysql   | 2022-05-17 03:02:35 | -                   | Error 1064: You have an        |
|                 |         |                     |                     | error in your SQL syntax;      |
|                 |         |                     |                     | check the manual that          |
|                 |         |                     |                     | corresponds to your MySQL      |
|                 |         |                     |                     | server version for the right   |
|                 |         |                     |                     | syntax to use near 'IF EXISTS  |
|                 |         |                     |                     | idx_albums_album_filter ON     |
|                 |         |                     |                     | albums' at line 1              |
| 20220329-050000 | mysql   | 2022-05-17 03:02:35 | 2022-05-17 03:02:37 | OK                             |
| 20220329-060000 | mysql   | 2022-05-17 03:02:37 | 2022-05-17 03:02:40 | OK                             |
| 20220329-061000 | mysql   | 2022-05-17 03:02:40 | -                   | Error 1064: You have an error  |
|                 |         |                     |                     | in your SQL syntax; check      |
|                 |         |                     |                     | the manual that corresponds    |
|                 |         |                     |                     | to your MySQL server version   |
|                 |         |                     |                     | for the right syntax to use    |
|                 |         |                     |                     | near 'INDEX idx_files_photo_id |
|                 |         |                     |                     | ON files (photo_id,            |
|                 |         |                     |                     | file_primary)' at line 1       |
| 20220329-070000 | mysql   | 2022-05-17 03:02:40 | -                   | Error 1064: You have an error  |
|                 |         |                     |                     | in your SQL syntax; check      |
|                 |         |                     |                     | the manual that corresponds    |
|                 |         |                     |                     | to your MySQL server version   |
|                 |         |                     |                     | for the right syntax to use    |
|                 |         |                     |                     | near 'IF EXISTS photo_taken_at |
|                 |         |                     |                     | DATETIME AFTER photo_uid' at   |
|                 |         |                     |                     | line 1                         |
| 20220329-071000 | mysql   | 2022-05-17 03:02:40 | 2022-05-17 03:02:41 | OK                             |
| 20220329-080000 | mysql   | 2022-05-17 03:02:41 | -                   | Error 1064: You have an        |
|                 |         |                     |                     | error in your SQL syntax;      |
|                 |         |                     |                     | check the manual that          |
|                 |         |                     |                     | corresponds to your MySQL      |
|                 |         |                     |                     | server version for the right   |
|                 |         |                     |                     | syntax to use near 'IF EXISTS  |
|                 |         |                     |                     | media_id VARBINARY(32) AFTER   |
|                 |         |                     |                     | photo_taken_at' at line 1      |
| 20220329-081000 | mysql   | 2022-05-17 03:02:41 | -                   | Error 1064: You have an error  |
|                 |         |                     |                     | in your SQL syntax; check      |
|                 |         |                     |                     | the manual that corresponds    |
|                 |         |                     |                     | to your MySQL server version   |
|                 |         |                     |                     | for the right syntax to        |
|                 |         |                     |                     | use near 'UNIQUE INDEX         |
|                 |         |                     |                     | idx_files_search_media ON      |
|                 |         |                     |                     | files (media_id)' at line 1    |
| 20220329-083000 | mysql   | 2022-05-17 03:02:41 | 2022-05-17 03:02:41 | OK                             |
| 20220329-090000 | mysql   | 2022-05-17 03:02:41 | -                   | Error 1064: You have an        |
|                 |         |                     |                     | error in your SQL syntax;      |
|                 |         |                     |                     | check the manual that          |
|                 |         |                     |                     | corresponds to your MySQL      |
|                 |         |                     |                     | server version for the right   |
|                 |         |                     |                     | syntax to use near 'IF EXISTS  |
|                 |         |                     |                     | time_index VARBINARY(48) AFTER |
|                 |         |                     |                     | photo_taken_at' at line 1      |
| 20220329-091000 | mysql   | 2022-05-17 03:02:41 | -                   | Error 1064: You have an error  |
|                 |         |                     |                     | in your SQL syntax; check      |
|                 |         |                     |                     | the manual that corresponds    |
|                 |         |                     |                     | to your MySQL server version   |
|                 |         |                     |                     | for the right syntax to        |
|                 |         |                     |                     | use near 'UNIQUE INDEX         |
|                 |         |                     |                     | idx_files_search_timeline ON   |
|                 |         |                     |                     | files (time_index)' at line 1  |
| 20220329-093000 | mysql   | 2022-05-17 03:02:41 | 2022-05-17 03:02:42 | OK                             |
| 20220421-200000 | mysql   | 2022-05-17 03:02:42 | -                   | Error 1064: You have an error  |
|                 |         |                     |                     | in your SQL syntax; check the  |
|                 |         |                     |                     | manual that corresponds to     |
|                 |         |                     |                     | your MySQL server version for  |
|                 |         |                     |                     | the right syntax to use near   |
|                 |         |                     |                     | 'INDEX idx_files_missing_root  |
|                 |         |                     |                     | ON files (file_missing,        |
|                 |         |                     |                     | file_root)' at line 1          |
| 20220521-000001 | mysql   | 2022-05-25 03:02:43 | 2022-05-25 03:02:44 | OK                             |
| 20220521-000002 | mysql   | 2022-05-25 03:02:44 | 2022-05-25 03:02:45 | OK                             |
| 20220521-000003 | mysql   | 2022-05-25 03:02:45 | 2022-05-25 03:02:45 | OK                             |
|-----------------|---------|---------------------|---------------------|--------------------------------|

time="2022-06-01T06:32:10Z" level=info msg="closed database connection"


--------------------------------------------------------------------------------------------------------------------------------------
`docker exec photoprism photoprism migrations run -f`
time="2022-06-01T06:33:43Z" level=info msg="PhotoPrism® needs your support!"
time="2022-06-01T06:33:43Z" level=info msg="Visit https://photoprism.app/membership to learn more."
time="2022-06-01T06:33:43Z" level=info msg="migrate: running previously failed migrations"
time="2022-06-01T06:33:43Z" level=info msg="migrating database schema..."
time="2022-06-01T06:33:44Z" level=info msg="migrate: 20220329-040000 successful [47.839887ms]"
time="2022-06-01T06:33:44Z" level=info msg="migrate: 20220329-061000 successful [44.680234ms]"
time="2022-06-01T06:33:44Z" level=info msg="migrate: 20220329-070000 successful [33.164792ms]"
time="2022-06-01T06:33:44Z" level=info msg="migrate: 20220329-080000 successful [24.364695ms]"
time="2022-06-01T06:33:44Z" level=info msg="migrate: 20220329-081000 successful [32.74057ms]"
time="2022-06-01T06:33:44Z" level=info msg="migrate: 20220329-090000 successful [30.963455ms]"
time="2022-06-01T06:33:44Z" level=info msg="migrate: 20220329-091000 successful [33.414971ms]"
time="2022-06-01T06:33:44Z" level=info msg="migrate: 20220421-200000 successful [34.272154ms]"
time="2022-06-01T06:33:44Z" level=info msg="migration completed in 1.188280732s"
time="2022-06-01T06:33:44Z" level=info msg="closed database connection"


--------------------------------------------------------------------------------------------------------------------------------------
`docker exec photoprism photoprism index -f`
runs too. Updated a lot of and matched.

-> Now it is working. Thank you very much!!!

**Comment by lastzero** [comment] 2022-06-01 12:00
You're welcome! 👉 https://photoprism.app/membership

**Comment by lastzero** [comment] 2022-10-08 16:53
After this happened again several times, we decided to display an error message with a link to the documentation:

```
$ photoprism --db-server mysql:4001 migrate
ERRO[2022-10-08T16:34:52Z] config: MySQL 8.0.27 is not supported, please upgrade
to MariaDB 10.5.12 or later (https://docs.photoprism.app/getting-started/#databases) 
```

**Comment by lastzero** [comment] 2022-11-04 11:44
Nobody complained so far, so I'll move ahead and close this as done!

**Closed as completed by lastzero** 2022-11-04 11:44 UTC
Labels: enhancement, question, released
