### ISSUE TITLE
UX: PWA iOS image details panel loses focus

### ISSUE THREAD

**Issue by elapse2039** [photoprism/photoprism#2251] opened 2022-04-13 21:24 UTC
**What does not work as described in the documentation?**

The PWA works really well on iOS but sometimes when you have opened an image full screen, then clicked on image details using the "pencil" editor icon the focus is grabbed by the wall of photos behind it.  You can see one-line-pixel of the photo wall and it is sliding up and down instead of the image you have made full screen.  The focus is refocused onto the image details panel above the wall of photos about ~2secs after you lift your finger and you can then scroll up to the top of the image details panel as expected.  Otherwise, the image details panel will only start scrolling once you've scrolled the photo wall (underneath the details panel) up to it's beginning.

**How can we reproduce it?**

1. Go to any photo wall of >50 photos and scroll part way down (say to 10th row on iPhone).
2. Click on any photo to enlarge.
3. Click on the photo's detail icon (pencil) and scroll down the photo details panel.
4. When you want to scroll up on image details and you will see a small single pixel line at the bottom change as the photo wall behind it is in fact scrolling.
5. Lift finger ~2secs and image details panel may get focus.
6. If this doesn't happen keep scrolling upwards (the photo wall scrolls but image details doesnt)
7. Once photo wall has scrolled to top the focus pops to image details and you can scroll back up the image detais panel.

**What behavior do you expect?**

When image details panel is open I expect to scroll up and down that panel and it to remain in focus.

**What could be the cause of your problem?**

I suspect two panels are registered for touch/focus and when you reach the bottom of the image details panel this panel stops listening and the photo wall takes over focus. The subsequent swipe event is then ignored by the image details panel and somehow propagated onto the photo-wall panel underneath. Here it remains in focus until the photo wall panel reaches it's top (or bottom) view position.  The image details panel no longer reacts to focus/swipes as it has scrolled down to it's bottom view position.  The image details panel then reacts to the swipe/focus once the photo wall panel has finished scrolling.

**Which software versions do you use?**

Build 220302-0059f429-Linux-AMD64

**On what kind of device is PhotoPrism installed?**

Photoprism server is on a linux laptop.  The PWA is on iPhone 8 with 128GB of ram.

**Do you use a Reverse Proxy, Firewall, VPN, or CDN?**

Reverse Proxy and Firewall.

**Comment by graciousgrey** [comment] 2022-04-14 06:36
Thanks for reporting :)

**Comment by lastzero** [comment] 2022-11-02 11:20
Is this still happening? Any idea how to fix/improve it?

**Comment by lastzero** [comment] 2022-11-04 11:41
I'll close this since we received no more feedback. We welcome contributions with a fix should this still be an issue.

**Comment by elapse2039** [comment] 2022-11-04 12:51
Yes, still happens.  No thoughts on how to fix it.

**Comment by lastzero** [comment] 2022-11-04 12:58
So with the latest iOS 16 and our latest release, as the report says "220302-0059f429-Linux-AMD64"?

**Comment by lastzero** [comment] 2022-11-04 13:03
@theresagresch Can you confirm this?

**Comment by elapse2039** [comment] 2022-11-04 14:39
Version "221102-905925b4d" on iOS 16.0.3 iPhone8.

**Comment by GregoryIvo** [comment] 2023-02-09 01:29
Hi, I can't seem to reproduce this on iPhone 14 pro, Build221118-e58fee0fb. Maybe this can be closed @lastzero @elapse2039? ios 16.2

**Comment by lastzero** [comment] 2023-02-09 08:20
In that case, we'll close it until it's confirmed (again).

**Closed as completed by lastzero** 2023-02-09 08:20 UTC
Labels: bug, help wanted, please-test, ux
