### ISSUE TITLE
Feature: Option to upload images to albums of shared links

### ISSUE THREAD

**Issue by coxtor** [photoprism/photoprism#3228] opened 2023-02-24 11:11 UTC
Hi, I host all images of trips that I made with friends. For to share these images I share Albums with public links. It would be great to have the option to add images to the album, ideally with an extra tag. The upload feature could be togglable when creating the share link. 
A comparable feature is implemented in the demo of immich. 

[immich demo](https://demo.immich.app/albums/f80e6c7b-e7cf-4584-86be-00875712a033)

![grafik](https://user-images.githubusercontent.com/7712562/221164898-4d33b31b-2606-483a-bba3-4f1041f0ed3c.png)

**Comment by graciousgrey** [comment] 2023-02-24 11:21
Duplicate of 

- https://github.com/photoprism/photoprism/issues/557

Feel free to leave a :+1: in there :)

**Closed as completed by graciousgrey** 2023-02-24 11:21 UTC
Labels: duplicate
