### ISSUE TITLE
Just a few (only jpg) photos are visible after index

### ISSUE THREAD

**Issue by Whisprin** [photoprism/photoprism#163] opened 2019-12-18 16:19 UTC
I'm using the latest docker image.

To be sure I stopped and deleted the photoprism container and started fresh.

```
docker stop photoprism
> photoprism
docker rm -f photoprism 
> photoprism
docker pull photoprism/photoprism:latest
> Status: Downloaded newer image for photoprism/photoprism:lates
docker run -p 2342:2342 -d --name photoprism -v ~/Pictures/Photoprism:/home/photoprism/Pictures/Originals photoprism/photoprism
> 963ca64db19545e8a9e274caac2a115284b2a37a2e3e0a34ad503d965d9a72f5
docker exec -ti photoprism photoprism index
> INFO[2019-12-18T16:00:21Z] indexed 282 files in 21.643856983s           
> INFO[2019-12-18T16:00:21Z] closed database connection
```

After the index completed there are just 15 images visible in the web ui. I have 126 ARW and 15 JPG images = 141 images in the folder. See attached screenshot: On the left side it says 141 images, but only 15 are visible. I haven't applied any filters

![Screenshot from 2019-12-18 17-14-38](https://user-images.githubusercontent.com/3153136/71103367-4bf1e880-21ba-11ea-9d26-d9c2c97d401a.png)

**Comment by lastzero** [comment] 2019-12-18 16:53
Yes, ARW seems to be a RAW format, right? So you need to import them (will be converted to JPEG automatically) or run the converter before indexing (we added a checkbox to the Web UI for that). We can't display RAW photos as JPEG without having a JPEG ;)

**Comment by Whisprin** [comment] 2019-12-18 16:56
Thanks!
Yes, ARW is RAW. How do I run the converter? I searched https://docs.photoprism.org for "converter" but "No matching documents".

**Comment by lastzero** [comment] 2019-12-18 16:58
`photoprism help` -> `photoprism convert`

**Comment by lastzero** [comment] 2019-12-18 17:00
No, just when importing as some users said they don't want us to touch their directories. Also it would take significant time to test all files for existing JPEGs when indexing or re-indexing.

**Comment by lastzero** [comment] 2019-12-18 17:02
The reason why we decided to have the import step is performance. Otherwise you need to always scan all files in the main directory for changes, missing JPEGs, etc

**Comment by Whisprin** [comment] 2019-12-18 17:06
Awesome, thanks. Is this case common enough to add it to the getting started docs? Or maybe the index step can output an info to the console for the user?

Other than that the issue is resolved for me. Thanks

**Comment by lastzero** [comment] 2019-12-18 17:07
> > A JPEG representation might be created for RAW images in order to render thumbnails.
> 
> I was under the impression this will happen during the index step as well.

We should clarify that. Only a general info for running the server, not the index command specifically. If you run it in read only mode, the checkbox for creating JPEGs is disabled.

**Comment by lastzero** [comment] 2019-12-18 17:10
> Awesome, thanks. Is this case common enough to add it to the getting started docs? Or maybe the index step can output an info to the console for the user?
> 
> Other than that the issue is resolved for me. Thanks

Yes, we should improve our docs there. However, we might index in random order in the future. So we only know something is missing when we're done. But then a new command might already run, so in theory we could have 1 second to report that right now something is missing and the user should take action. Maybe we do a report page listing potential issue with the note not to panic and wait for the indexer to finish its run.

**Comment by lastzero** [comment] 2019-12-18 17:11
...or people just use use the importer for importing photos as designed :)

**Comment by lastzero** [comment] 2019-12-18 17:46
@Whisprin If our setup guide is clear now, I'll close this issue :)

See http://docs.photoprism.org/en/latest/setup/

If the text didn't change, you might have to clear your cache.

**Closed** 2019-12-18 18:35 UTC
Labels: question
