### ISSUE TITLE
unable to right click on images when viewing them full-screen

### ISSUE THREAD

**Issue by classabbyamp** [photoprism/photoprism#1299] opened 2021-05-18 01:42 UTC
When I try to right click on an image in full-screen mode (e.g. to copy it to my clipboard), most of the time it goes back to the list/icon view of whatever album/tag/etc I'm looking at. I'm looking for either a fix for this or a way to copy the image (not url) to my clipboard.

**Comment by graciousgrey** [comment] 2021-05-18 08:30
Works for me. What browser so you use?
![photo_2021-05-18_10-30-12](https://user-images.githubusercontent.com/15210372/118618580-0dec6000-b7c4-11eb-8603-cad89da62434.jpg)

**Comment by classabbyamp** [comment] 2021-05-19 01:33
I'm using vivaldi, so chrome under the hood

**Comment by graciousgrey** [comment] 2021-05-20 08:49
Just downloaded vivaldi and tested on our demo, I can right click on photos and click "Copy image" without problems. I'm on linux as well.

**Comment by lastzero** [comment] 2021-05-22 09:34
I'll close this as we're eventually going to rework the viewer anyways and we can't reproduce this right now. If you know how to fix this for your local environment with the browser version you use, you're welcome to send a pull request.

**Closed by lastzero** 2021-05-22 09:34 UTC
Labels: question

**Comment by jNullj** [comment] 2023-09-25 16:01
I can duplicate this, i started having this issue.
I am running on latest release (upgraded today)
The issue only appears on some photos, it appears it only happends for photos with specific size or aspect ratio.
When i resize the browser and make it smaller then the image i can copy it and the problem does not show

**I can replicate the issue with the demo at the photoprism logo image**
Steps to relicate:
1. Open chrome latest version
2. Open link to demo/photo https://demo.photoprism.app/library/browse#&gid=1&pid=4
3. Click photoprism logo photo (left click) to view it
4. Right click to copy, image view will close unexpectetly
5. Select copy in context menu will not copy the image to clipboard

You can make the window much smaller now and see the issue is not showing

Video of issue when windows is large:

https://github.com/photoprism/photoprism/assets/15849761/5afb1a7d-0512-4b12-b3d4-af659ff2d163

Video of issue not appearing when window is smaller in one of the axis then image:


https://github.com/photoprism/photoprism/assets/15849761/86a43a3b-88a6-4f6e-b834-fab46d7f9ba2

**Comment by graciousgrey** [comment] 2023-10-16 16:22
@jNullj I tested with various window sizes and exactly this photo, unfortunately I can't reproduce this. What operating system are you using?

**Comment by jNullj** [comment] 2023-10-21 10:11
Just tested on the current demo, This issue show up on Windows 10 in both Firefox and Google Chrome.
As you mentioned the OS in use I also tested on my daily drive Linux (Arch Linux) in chromium, and i got a different issue. While i was able to copy the image and it did not close on right click like in windows, After selecting an item in the right click context menu the UI is stuck with mouse button "down" and the images try to swap left/right while the mouse buttons are free.

**Comment by jNullj** [comment] 2023-10-21 10:12
> @jNullj I tested with various window sizes and exactly this photo, unfortunately I can't reproduce this. What operating system are you using?

@graciousgrey Just tested on the current demo, This issue show up on Windows 10 in both Firefox and Google Chrome.
As you mentioned the OS in use I also tested on my daily drive Linux (Arch Linux) in chromium, and i got a different issue. While i was able to copy the image and it did not close on right click like in windows, After selecting an item in the right click context menu the UI is stuck with mouse button "down" and the images try to swap left/right while the mouse buttons are free.

**Comment by lastzero** [comment] 2023-11-04 15:41
After following the steps described in [the comment above](https://github.com/photoprism/photoprism/issues/1299#issuecomment-1734042076), I was able to reproduce the problem on Windows 11 in Chrome and Firefox, but only with our logo SVG, which is just 224x224 pixels.

It could have been because the viewer only attaches a click handler if the image is large enough. However, when I do the same on other operating systems and with the same browsers, it does not happen, so the context menu is displayed as expected and the viewer does not close. There were also no warnings or errors visible in the browser console (logs).

I'll therefore need to leave it to our community to find a solution, because I have no idea why this happens (only on Windows) and how to fix it:

- https://github.com/photoprism/photoprism/issues/3720#issuecomment-1793476393
