### ISSUE TITLE
Condensed/list view of album list

### ISSUE THREAD

**Issue by rixx** [photoprism/photoprism#3803] opened 2023-10-09 10:59 UTC
I use albums a lot – they are basically tags, right? So I have both albums for specific occasions (like vacations), and for topics, and so on.

However, navigating to an album can be pretty frustrating, as they display in large tiles in the list view at /library/albums. I'd like to be able to switch to a list (and/or smaller tiles, but the list is more relevant to me), just like in the regular photo view.

**Comment by graciousgrey** [comment] 2023-10-09 11:59
Seems to be a duplicate of 

- https://github.com/photoprism/photoprism/issues/382

feel free to leave  :+1: in there :)

**Closed as completed by graciousgrey** 2023-10-09 11:59 UTC
Labels: duplicate
