### ISSUE TITLE
UX: Display Summary Metadata next to image being displayed

### ISSUE THREAD

**Issue by ravensorb** [photoprism/photoprism#3139] opened 2023-01-21 20:13 UTC
The ability to edit the meta data is great, however it would also be helpful if there was a way to show/hide a summary of the metadata next to current image being viewed.

This idea might be a duplicate from #1307

**Comment by graciousgrey** [comment] 2023-01-23 13:56
Yes, it's a duplicate of #1307. Feel free to leave a :+1: there :)

**Closed as completed by graciousgrey** 2023-01-23 13:56 UTC
Labels: duplicate
