### ISSUE TITLE
Photos missing in "Places"

### ISSUE THREAD

**Issue by GarryLai** [photoprism/photoprism#4406] opened 2024-07-14 10:23 UTC
#### 1. What is not working as documented?

Number of photos less then it display on map.
eg. The number on the map is 10 but after I click on it show 2.
It seems like is the number displayed more then actually.

#### 2. How can we reproduce it?

1. Upload some photos.
2. Goto "Places"
3. Zoom in (this only happened when you zoom it closely)
4. Click on photo groups

#### 3. What behavior do you expect?

Photos shown should be same as the number on the map.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![image](https://github.com/user-attachments/assets/d6d98d87-2b1c-46a6-8406-0b4d4c18079a)
![image](https://github.com/user-attachments/assets/37adff13-fb80-4c33-a294-0b7eb391bc60)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: x64 240713-2197af8

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Ubuntu WSL2 (Docker)

(d) Browser Types & Versions: Chrome

(e) Ad Blockers, Browser Plugins, and/or Firewall Software: Ublock

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: E5-2630*2

(b) Physical Memory & Swap Space in GB: 64GB

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...: HDD*2 with RAID 1

(d) Anything else that might be helpful to know?

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Firewall: Foritgate

**Comment by lastzero** [comment] 2024-07-14 10:35
Did you already perform a full rescan? Could these pictures be in review or flagged as private?

**Comment by lastzero** [comment] 2024-07-14 10:37
Also see the following issue, which might be the same as what you report:
- https://github.com/photoprism/photoprism/issues/3953#issuecomment-1867283614

**Comment by GarryLai** [comment] 2024-07-14 10:53
> Also see the following issue, which might be the same as what you report:
> 
> * [Places: No pictures are displayed when clicking on some clusters #3953 (comment)](https://github.com/photoprism/photoprism/issues/3953#issuecomment-1867283614)

Yeah, is the same problem.

**Comment by GarryLai** [comment] 2024-07-14 10:54
> Did you already perform a full rescan? Could these pictures be in review or flagged as private?

Yes, after full rescan it seems still buggy.

**Comment by lastzero** [comment] 2024-07-14 12:54
Thanks for taking a look! Does this mean that your issue is also related to the "Quality Filter" and therefore a duplicate?

**Comment by GarryLai** [comment] 2024-07-14 14:44
> Thanks for taking a look! Does this mean that your issue is also related to the "Quality Filter" and therefore a duplicate?

Yes, this bug has existed for a long time. It need someone to find out and fix it.

**Comment by GarryLai** [comment] 2024-07-14 15:17
@lastzero The bug seems happened in frontend.
It will use the **WRONG** coordinate on calling API `/api/v1/photos`.
For example:
If I turned on "Quality Filter" they used the correct coordinate `25.045610427856445,121.07545471191406,25.04454803466797,121.07527160644531`, which can get images normally.
But, if I turned off "Quality Filter", they used wrong coordinate `25.04560089111328,121.07499694824219,25.04450035095215,121.07499694824219` in the same place, so I get no pictures or less then normal.
I think this is why the bug only happened when I zoom in closely.

**Comment by lastzero** [comment] 2024-07-14 16:19
Feel free to submit a pull request if you know how to fix it 👍

**Comment by graciousgrey** [comment] 2024-07-15 11:50
Thanks for debugging and reporting! 

As it seems to be related I will close this issue as a duplicate of 

- #3953 

We can continue the conversation there.

While I can reproduce the issue with the files provided in #3953 , it does not occur with our own files. Also, with the files provided in #3953  it seems to be independent of the zoom level, while the zoom level seems to play a role in your case.
Could you send us some [sample files](https://www.photoprism.app/contact#file-samples) for further debugging? Preferably one that displays correctly when the quality filter is disabled and one that does not.

Thank you very much!

**Closed as completed** 2024-07-15 12:02 UTC
Labels: duplicate
