### ISSUE TITLE
Stacking: Deleting a stacked file leads to inconsistent photo metadata

### ISSUE THREAD

**Issue by kvalev** [photoprism/photoprism#2330] opened 2022-05-17 23:06 UTC
**What does not work as described in the documentation?**

When multiple files are stacked, one of the `file`'s metadata is used as the `photo`' metadata. However if said file is deleted from the file system, the `photo`'s metadata does not get updated and still shows the metadata if the deleted file.

**How can we reproduce it?**

1. Have two stacked videos (for example ones taken close to each other, time and location-wise), sample videos are attached
2. Check the API response when loading the album where the videos are located - there are multiple `photo` properties inferred from the first stacked file - `Name`, `OriginalName`, `Filename`. The photo should  also contain 4 files - the two videos and the two thumbnails. The primary file will be the thumbnail of the first video. Here is a sample response (trimmed for brevity):

```
[
    {
        "ID": "110-136",
        "UID": "prc1lxz2pznenetl",
        "Type": "video",
        "Path": "remove-duplicate-stacked-file",
        "Name": "sample-mp4-file-small 1",
        "OriginalName": "sample-mp4-file-small1",
        "FileRoot": "sidecar",
        "FileName": "remove-duplicate-stacked-file/sample-mp4-file-small 1.mp4.jpg",
        "Merged": true
        "Files": [
            {
                "UID": "frc1sxaqc99mpawn",
                "PhotoUID": "prc1lxz2pznenetl",
                "Name": "remove-duplicate-stacked-file/sample-mp4-file-small 1.mp4.jpg",
                "Root": "sidecar",
                "Primary": true,
                "OriginalName": "sample-mp4-file-small1",
                "FileType": "jpg",
                "MediaType": "image"
            },
            {
                "UID": "frc1sx93t68l3trw",
                "PhotoUID": "prc1lxz2pznenetl",
                "Name": "remove-duplicate-stacked-file/sample-mp4-file-small 1.mp4",
                "Root": "/",
                "Primary": false,
                "OriginalName": "sample-mp4-file-small1",
                "FileType": "mp4",
                "MediaType": "video"
            },
            {
                "UID": "frc1sxb2i6i1zk8b",
                "PhotoUID": "prc1lxz2pznenetl",
                "Name": "remove-duplicate-stacked-file/sample-mp4-file-small.mp4",
                "Root": "/",
                "Primary": false,
                "OriginalName": "sample-mp4-file-small1",
                "FileType": "mp4",
                "MediaType": "video"
            },
            {
                "UID": "frc1sxc1e1yw2qwv",
                "PhotoUID": "prc1lxz2pznenetl",
                "Name": "remove-duplicate-stacked-file/sample-mp4-file-small.mp4.jpg",
                "Root": "sidecar",
                "Primary": false,
                "OriginalName": "sample-mp4-file-small1",
                "FileType": "jpg",
                "MediaType": "image"
            }
        ]
    }
]
```

3. Now delete the "main" video file, in the example above that would be `sample-mp4-file-small 1.mp4`.
4. Reindex
5. Check the API response when loading the album where the videos are located - there are multiple problems with the `photo` metadata. First the number of files is 3 and not 2, as the sidecar thumbnail file is still included. Even worse, the thumbnail is used as primary file. And secondly the metadata if the `photo` still refers to the metadata of the deleted video and was not updated to the metadata of the remaining one - e.g. the `FileName` property. Here is a sample response (trimmed for brevity):

```
[
    {
        "ID": "110-136",
        "UID": "prc1lxz2pznenetl",
        "Type": "video",
        "Path": "remove-duplicate-stacked-file",
        "Name": "sample-mp4-file-small 1", # This is incorrect
        "OriginalName": "sample-mp4-file-small1", # This is incorrect
        "FileRoot": "sidecar",
        "FileName": "remove-duplicate-stacked-file/sample-mp4-file-small 1.mp4.jpg", # This is incorrect
        "Merged": true,
        "Files": [
            {
                "UID": "frc1sxaqc99mpawn",
                "PhotoUID": "prc1lxz2pznenetl",
                "Name": "remove-duplicate-stacked-file/sample-mp4-file-small 1.mp4.jpg",
                "Root": "sidecar",
                "Primary": true, # This should not be the primary file
                "OriginalName": "sample-mp4-file-small1",
                "FileType": "jpg",
                "MediaType": "image"
            },
            {
                "UID": "frc1sxb2i6i1zk8b",
                "PhotoUID": "prc1lxz2pznenetl",
                "Name": "remove-duplicate-stacked-file/sample-mp4-file-small.mp4",
                "Root": "/",
                "Primary": false,
                "OriginalName": "sample-mp4-file-small1",
                "FileType": "mp4",
                "MediaType": "video"
            },
            {
                "UID": "frc1sxc1e1yw2qwv",
                "PhotoUID": "prc1lxz2pznenetl",
                "Name": "remove-duplicate-stacked-file/sample-mp4-file-small.mp4.jpg",
                "Root": "sidecar",
                "Primary": false,
                "OriginalName": "sample-mp4-file-small1",
                "FileType": "jpg",
                "MediaType": "image"
            }
        ]
    }
]
```

**What behavior do you expect?**

The `photo`'s information should not contain any trace of the deleted video and all of it's metadata should be updated.

**What could be the cause of your problem?**

`SetPhotoPrimary` is incomplete:

https://github.com/photoprism/photoprism/blob/420208295ee01753c2d6859aefaa7881f02261f9/internal/query/files.go#L121-L156

**Can you provide us with example files for testing, error logs, or screenshots?**

https://user-images.githubusercontent.com/270592/168925962-b576d625-afa2-4142-80bf-6a0492794bfc.mp4

https://user-images.githubusercontent.com/270592/168925971-c4d7928f-9080-431d-b837-b616a597aa10.mp4

**Which software versions do you use?**

- PhotoPrism Architecture & Build Number: `Build 220517-b9c68f8f-Linux-AMD64`
- Database Type & Version: `mariadb:10.7`

**On what kind of device is PhotoPrism installed?**

Tried both on a Raspberry Pi 4 and on mac os.

**Do you use a Reverse Proxy, Firewall, VPN, or CDN?**

No

**Comment by lastzero** [comment] 2022-05-18 01:47
You manually deleted the primary JPEG from the sidecar folder? Not via UI, but directly in the filesystem? Since the original folder is being indexed and not the sidecar folder, this isn't supported and you have to use the UI instead (which will not allow this without selecting a new primary first).

**Comment by kvalev** [comment] 2022-05-18 04:22
No, I deleted the file in the original folder.

**Comment by lastzero** [comment] 2022-05-18 05:59
Anyhow, the JPEG with the ID frc1sxc1e1yw2qwv must be the new primary then as it's name matches the video file name. Unstacking both in the UI should also work with the latest changes. There's a related issue (closed). I am currently out of the office and only have my phone with me, so sorry if I missed any details.

**Comment by kvalev** [comment] 2022-05-18 06:30
No worries, you can easily reproduce it when you are back and see for yourself.

**Comment by lastzero** [comment] 2022-05-18 06:33
This will be on Friday and by then I will have 300+ new emails in my inbox, so no time to reproduce or code 😂

**Comment by lastzero** [comment] 2022-05-18 06:38
- Does it work when you select the correct primary in the UI or unstack the video file after and/or instead of deleting the other? 
- As we don't keep a complete history of all files and how their metadata has been used, automated resolution is not always possible or we avoid it to prevent unmaintainable code and surprise results you do not want if you would have known upfront this would happen.
- Sometimes files are not lost permanently but just are missing for a limited time. In this case for example, you do not want photoprism to take action and change everything. Please keep this in mind as well.

**Comment by kvalev** [comment] 2022-05-19 18:12
> * Does it work when you select the correct primary in the UI or unstack the video file after and/or instead of deleting the other?

Manually unstacking videos makes it even worse...
- unstacking one video changed the type of the original one to `image`, although it is a video
- the unstacked video file was renamed for whatever reason (wonder how this will behave if originals was mounted readonly)
- the sidecar jpg belonging to the unstacked video was left orphaned in the original `photo` object

**Comment by lastzero** [comment] 2022-05-19 18:55
Seems related to:
- https://github.com/photoprism/photoprism/issues/1823

Can you please go through the comments and see if this is relevant?

**Comment by kvalev** [comment] 2022-05-19 20:08
Yes, you have described the exact same problem: https://github.com/photoprism/photoprism/issues/1823#issuecomment-1005838855

> When unstacking, make sure the photo _Name_ (see _Settings_ tab in photo edit dialog) does not match the file _Name_ of the file you want to unstack. It then does not get renamed and related files should now be unstacked together with it.

If you were to unstack the file with the same _Name_ then all hell breaks loose. I feel like this is a pretty important caveat and it should either be prohibited to unstack the "main" file or better yet, PhotoPrism should be able to handle that. At the end of the day you cannot prevent people deleting the "main" file directly from the file system and thus forcefully unstacking the files.

**Comment by lastzero** [comment] 2022-05-19 20:25
We will test this, but so far this rather sounds like an improvement for an edge case rather than an actual bug. There may also be workarounds, for example unstacking the group of files with other file name prefixes first. From what I remember, this is how it was designed.

**Comment by kvalev** [comment] 2022-05-19 21:07
Well given that PP allows you to shoot yourself in the foot by unstacking the wrong file, it definitely feels like a bug, rather than a feature.

**Comment by lastzero** [comment] 2022-05-19 21:11
Since you are using the software for so long and only notice this now (and nobody else), it can not be that big of a drama!? 🤗

**Comment by kvalev** [comment] 2022-05-20 06:14
And given that you have worked in software for so long you should know by now what a bug is and that not all bugs are super urgent.

**Comment by lastzero** [comment] 2022-05-20 07:02
We have a zero bug policy, and you said you shot yourself in the foot, which sounds pretty urgent.... as I said, we will test it, but it may well be a tradeoff we made to implement other features requested by our users, such as the ability to name sidecar files like the originals instead of using cryptic hash-based names. This is indeed a feature, although the side effects may look like a bug to you. Before we did this, I explained the consequences and the community wanted us to implement it this way.

**Comment by lastzero** [comment] 2022-05-20 22:06
As far as I can see, the sample videos you added for testing are identical (same file size, same preview). So I downloaded a few examples from [pexels.com](https://www.pexels.com/video/a-fully-automated-production-line-of-beers-5532773/). Next, I turned sequential name indexing on and off, unstacked files, deleted files from the file system, changed primary files, and deleted obsolete JPEGs from the user interface.

While I see the need to further improve the user interface and documentation (while many users are waiting for new features instead), the functionality is as designed by us and approved by other users.

**This is also important because we don't want to delete anything automatically, even if it's just a JPEG sidecar file. You might want to keep a preview of an Ultra HD video version, while permanently keeping a lower resolution version of the video to save storage space. It's not up to us to decide what our users want or get.**

![Screenshot 2022-05-20 at 23 35 52](https://user-images.githubusercontent.com/301686/169617425-920f29f6-3616-4ad2-bcf3-38eb87c1606a.jpg)

![Screenshot 2022-05-20 at 23 34 41](https://user-images.githubusercontent.com/301686/169617433-890f8630-1dd8-48fb-b672-73d900c3e3c0.jpg)
![Screenshot 2022-05-20 at 23 34 52](https://user-images.githubusercontent.com/301686/169617430-7a8147df-1ce1-4697-97ff-60ddfeabe927.jpg)
![Screenshot 2022-05-20 at 23 35 17](https://user-images.githubusercontent.com/301686/169617872-e51f9cc0-58b6-4f32-b7d5-4ec7799b06ad.jpg)

![Screenshot 2022-05-20 at 23 35 31](https://user-images.githubusercontent.com/301686/169617426-737683b8-763c-4751-a25c-021fcd454b1c.jpg)

![Screenshot 2022-05-20 at 23 35 57](https://user-images.githubusercontent.com/301686/169617424-7a86c26c-3459-4c98-89d2-21d529779333.jpg)

![Screenshot 2022-05-20 at 23 42 10](https://user-images.githubusercontent.com/301686/169617423-d1d3d890-6d6e-4d82-84e5-d4940ec56a3d.jpg)
![Screenshot 2022-05-20 at 23 43 44](https://user-images.githubusercontent.com/301686/169617419-61da39f2-fa7d-49c2-bd57-4bd67e1c371e.jpg)

![Screenshot 2022-05-20 at 23 59 55](https://user-images.githubusercontent.com/301686/169618110-fc93138d-87e5-4161-b188-49e37e97676a.jpg)

**Comment by lastzero** [comment] 2022-05-20 22:10
I will close this issue as there are a lot of feature requests with much higher priority. Nevertheless, we will keep this feedback in mind should we get the opportunity to improve UX and documentation.

**Closed as completed by lastzero** 2022-05-20 22:10 UTC
Labels: bug, won't fix
