### ISSUE TITLE
UX: Lag when selecting pictures

### ISSUE THREAD

**Issue by wiwie** [photoprism/photoprism#477] opened 2020-08-21 17:56 UTC
When browsing pictures under /photos and scrolling down a bit, such that a larger number of pictures is visible (maybe around 300), any kind of operation that changes the current selection of pictures is very laggy, i.e. clicking on a picture to select it or holding down shift and then clicking to select multiple pictures is followed by a delay of about 2s before the new selection is represented in the UI.

This is tested on a computer with decent hardware and Firefox 79.0.

**Comment by geirgp** [comment] 2020-10-11 19:30
I experience the same lag. decent Macbook Pro, latest Chrome.

**Comment by lastzero** [comment] 2020-10-11 19:54
How many pictures shown / selected? As mentioned, it can and should be optimized.... Just didn't have time for this yet and apparently no one else :/

**Comment by geirgp** [comment] 2020-10-15 10:14
I endend up selecting 110 photos, and scrolled through 1500-ish in that selection process.

**Comment by lastzero** [comment] 2020-10-15 10:42
Which one was it? List (table), mosaic (just previews) or cards (with details)?

**Comment by aureooms** [comment] 2020-10-26 11:19
@lastzero I looked at the implementation of `Clipboard` just as a sanity check. Does not look like the problem comes from there. More likely to come from the UI code as already noted. I left some comments [here](https://github.com/photoprism/photoprism/commit/65648450a4be9ffbf4f1b4a15f5a4e984daef9e4) for some potential improvement of the code style of `Clipboard`.

**Comment by lastzero** [comment] 2020-10-26 11:34
**Thanks for taking a look at this!** I agree, even arrays containing 1000 items should not cause this kind of lag.

We use lots of conditional rendering (`v-if`, `v-else-if`, `v-else`) in our VueJS templates though. So when the selection state changes, VueJS might re-render *all results*. Instead, it should only refresh the *selected* picture.  The difficult part is not to introduce (sometimes subtle) bugs with optimizations.

**Comment by aureooms** [comment] 2020-10-26 11:55
@lastzero Could you point me to the relevant files?

**Comment by lastzero** [comment] 2020-10-26 12:05
See:
- https://github.com/photoprism/photoprism/tree/develop/frontend/src/component/photo
- https://github.com/photoprism/photoprism/blob/develop/frontend/src/pages/photos.vue

I expect the [`component/photo/cards.vue`](https://github.com/photoprism/photoprism/blob/develop/frontend/src/component/photo/cards.vue
) view to be the slowest as it contains the most logic and thus causes the most overhead when re-rendering. Selecting pictures was much faster in the past. Since then we've added a ton of features like video & live photo support.

**Comment by aureooms** [comment] 2020-10-26 15:45
I did a quick performance recording on the default gallery view (mosaic I guess) after scrolling down a bit. I observe a lot of GC trashing. Vue probably has no way to understand what is going on inside `Clipboard` (`$clipboard` is not a prop). Once `selection` is updated, the entire list has to be recomputed (because render depends on `$clipboard.has(...)` calls). Replacing `this.selection` by a `Set` as suggested [here](https://github.com/photoprism/photoprism/commit/65648450a4be9ffbf4f1b4a15f5a4e984daef9e4) won't solve the issue unless Vue is able to do some clever set diffing...

Something that may have a better chance of working could be having some sort of internal `selected` state for each card, decoupling the global `Clipboard` from that state, so that the list does not depend on a `selection` prop. Of course now it is ugly because the selection state is spread all over. If you do not want to decouple, I think one should precompute `$clipboard.has(photo)` for each card and have a component for individual cards so that Vue can more quickly tell which cards need to be rerendered. It would still imply recomputing something for each item, but maybe much faster so that it would no become a problem unless you load a really large collection.

Additionally, having a scrolling "pagination" would help: with a state looking like `numberOfphotosBeforeDisplayedPhotos`, `displayedPhotos`, `numberOfphotosAfterDisplayedPhotos`, a component to display empty space for before and after that only depends on the number of items to be faked, and a component for displaying `displayedPhotos`, I am sure this exists already somewhere?

Any other idea?

**Comment by lastzero** [comment] 2020-10-26 16:08
Interesting, might come up with a replacement for `$clipboard.has()` when I have time to think about it. Of course you're more than welcome to give it a try first!

In general, the code seems easier to understand and maintain when the logic is encapsulated and independent of the view - but not at any price. Without VueJS, I'd probably use simple CSS classes for setting and getting the state.

PhotoPrism intentionally doesn't know the exact number of results:

- First, because the number is continuously changing while the indexer is running and/or other people are using the application at the same time.
- Second, because the database returns results faster when it only needs to fetch the first rows instead of computing the complete result set just to come up with a number that might change the next second.
- Last but not least, files are typically merged to photo stacks when they are shown in the UI. So the number of database rows is not the the same as the number of photos.

**Comment by aureooms** [comment] 2020-10-26 16:40
> Interesting, might come up with a replacement for `$clipboard.has()` when I have time to think about it. Of course you're more than welcome to give it a try first!

First I can try to rewrite `$clipboard` using a `Set` if you think this will not break things. I will need to understand how I can run the test suite for the whole thing.

> In general, the code seems easier to understand and maintain when the logic is encapsulated and independent of the view - but not at any price. Without VueJS, I'd probably use simple CSS classes for setting and getting the state.

Maybe the way selection is displayed is flawed anyway: with a large number of selected items the only exact information that can be extracted from the UI is `selection.length` in the bottom right corner. A more robust way to implement selection would be to have a preview of the selection somewhere which would be less prone to the kind of performance issues that are encountered here (since we only need to iterate over `this.selection`). Then there is no need to display a selected toggle on each gallery card... until the size of the selection becomes too large to inspect what is included... Probably both solutions should coexist but somehow the complexity of render should only depend on what can be shown on the screen, it should not depend on things outside of the viewport (I believe the default browser tab memory limit is proportional to the number of viewport pixels). See also below.

> PhotoPrism intentionally doesn't know the exact number of results:

`numberOfphotosBeforeDisplayedPhotos` and `numberOfphotosBeforeDisplayedPhotos` do not have to be database row counts, really anything that reflects how much stuff has been loaded in the UI. Since each item has known dimensions, a placeholder can be rendered instead of a card that would depend on the selection state. Of course this placeholder could be identical to a normal, but ignoring the selection state. I am just describing some sort of "infinite scrolling" as defined in https://github.com/photoprism/photoprism/issues/500#issue-704103396. A first implementation would just keep all metadata in cache but evict thumbnails of things that are far away from the currently displayed stuff, if thumbnails take up most of the memory.

**Comment by aureooms** [comment] 2020-10-27 16:57
> First I can try to rewrite $clipboard using a Set if you think this will not break things. I will need to understand how I can run the test suite for the whole thing.

This seems like a bad idea because Vue does not support `Set` and `Map` props: https://github.com/vuejs/vue/issues/2410#issuecomment-318487855?

**Comment by aureooms** [comment] 2020-10-27 17:38
> I did a quick performance recording on the default gallery view (mosaic I guess) after scrolling down a bit. I observe a lot of GC trashing. Vue probably has no way to understand what is going on inside Clipboard ($clipboard is not a prop). Once selection is updated, the entire list has to be recomputed (because render depends on $clipboard.has(...) calls). Replacing this.selection by a Set as suggested here won't solve the issue unless Vue is able to do some clever set diffing...

I am not sure now. In Vue, is it only props reactive updates that trigger renders? In that case I am not sure what is forcing the rerender. Certainly the `selection.length` check before each `$clipboard.has(...)` should trigger a render when going from `0` to `1`. Not sure what happens once it is positive and stays positive. Was the `selection.length` check added for performance reasons?

**Comment by aureooms** [comment] 2020-10-27 21:42
>  Certainly the `selection.length` check before each `$clipboard.has(...)` should trigger a render when going from `0` to `1`

I see, if I remove all mentions of `selection.length` then the view does not get updated :).

**Comment by aureooms** [comment] 2020-10-27 23:09
>  If you do not want to decouple, I think one should precompute `$clipboard.has(photo)` for each card and have a component for individual cards so that Vue can more quickly tell which cards need to be rerendered. It would still imply recomputing something for each item, but maybe much faster so that it would no become a problem unless you load a really large collection.

This is what I implemented.

**Comment by lastzero** [comment] 2020-10-28 06:39
Probably won't be able to review your suggestions before the weekend... looking forward to your PR / draft... as mentioned, changes should be kept to a minimum as a major refactoring will likely introduce new issues and at least requires much more testing.

**Comment by aureooms** [comment] 2020-10-28 08:47
> Probably won't be able to review your suggestions before the weekend... looking forward to your PR / draft... as mentioned, changes should be kept to a minimum as a major refactoring will likely introduce new issues and at least requires much more testing.

The changes I have introduced so far only fix the problem for [`component/photo/mosaic.vue`](https://github.com/photoprism/photoprism/blob/develop/frontend/src/component/photo/mosaic.vue). It does so by factoring out [the `v-flex` element](https://github.com/photoprism/photoprism/blob/67287a2d5770f805556ac081773a706cba178074/frontend/src/component/photo/mosaic.vue#L23) to a new component `component/photo/tile.vue`. To fix the performance everywhere requires similar changes to:

  - [`component/photo/cards.vue`](https://github.com/photoprism/photoprism/blob/67287a2d5770f805556ac081773a706cba178074/frontend/src/component/photo/cards.vue#L23)
  - [`component/photo/list.vue`](https://github.com/photoprism/photoprism/blob/67287a2d5770f805556ac081773a706cba178074/frontend/src/component/photo/list.vue#L32)
  - [`share/photo/mosaic.vue`](https://github.com/photoprism/photoprism/blob/67287a2d5770f805556ac081773a706cba178074/frontend/src/share/photo/mosaic.vue#L19)
  - [`share/photo/cards.vue`](https://github.com/photoprism/photoprism/blob/67287a2d5770f805556ac081773a706cba178074/frontend/src/share/photo/cards.vue#L19)
  - [`share/photo/list.vue`](https://github.com/photoprism/photoprism/blob/67287a2d5770f805556ac081773a706cba178074/frontend/src/share/photo/list.vue#L28)

I will limit the changes to what is needed to fix the issue raised in this thread. But I think that it would make sense in the future to refactor to share logic between `component` and `share`.

**Comment by lastzero** [comment] 2020-10-28 09:05
Using separate components for result container & items caused issues, but I don't remember what exactly. That's why there is only one component for each view type right now.

**Comment by lastzero** [comment] 2020-10-28 09:06
Maybe the items didn't react anymore when the backend sent updated metadata.

**Comment by lastzero** [comment] 2020-10-28 09:12
As a developer, I would very much refactor the frontend further and continue working on sharing (which includes finding the right abstraction before implementing it). But we need to make a cut somewhere. The overall quality is good enough by any standard and users are waiting for a release.

**Comment by aureooms** [comment] 2020-10-28 09:13
> Maybe the items didn't react anymore when the backend sent updated metadata.

Is there a regression test for this?

**Comment by lastzero** [comment] 2020-10-28 09:42
@graciousgrey maintains our acceptance tests... would be difficult to implement and a small project by itself.

**Comment by aureooms** [comment] 2020-10-29 10:35
> Maybe the items didn't react anymore when the backend sent updated metadata.

Let's say you have a component that renders something related to a photo by receiving a `Photo` instance as a prop with key `photo`. If I understand [Vue reactivity](https://vuejs.org/v2/guide/reactivity.html) correctly (`v2`), you need the `photo` prop to change to trigger a render (meaning `photo` must be a new instance of `Photo` when, for instance, the metadata changes), or you can avoid creating a new `Photo` instance and changing the `photo` prop by instead updating some of the properties of the existing instance which you watch with a `deep` watcher. Am I correct?

**Comment by wiwie** [comment] 2021-01-19 21:51
I can confirm that it has significantly improved.

**Comment by wiwie** [comment] 2021-01-19 21:52
reopened, so you can decide when to close the issue.

**Comment by lastzero** [comment] 2021-01-19 22:14
Already released! Thanks for testing ❤️

**Closed by lastzero** 2021-01-19 22:14 UTC
Labels: frontend, help wanted, please-test, todo

**Comment by efffghhbh** [comment] 2021-01-19 22:40
Le mar. 19 janv. 2021 à 17:14, Michael Mayer <notifications@github.com> a
écrit :
