### ISSUE TITLE
Expose photos via DLNA

### ISSUE THREAD

**Issue by rodolf0** [photoprism/photoprism#2000] opened 2022-02-02 23:37 UTC
Since Photoprism does the heavy lifting for indexing your whole photo library, would it be possible for the service to expose some form of minimal DLNA server for external surfaces to consume?

Example use case:
Running photoprism in a storage server it'd be quite useful to browse pictures in a TV.

**Comment by mirisbowring** [comment] 2022-02-09 11:51
This is probably a duplicate of https://github.com/photoprism/photoprism/issues/1008 right?

At least they belong together :)

**Comment by rodolf0** [comment] 2022-02-09 12:20
Yes, the intention is the same. Thanks for pointing out that issue. My searches didn't surface it.

DLNA is probably a bit more general and allows not only Chromecast to stream from the server. But if we get Chromecast support I'd be sold.

I'm ok with closing this one in favor of issue #1008.

**Comment by graciousgrey** [comment] 2022-02-09 12:50
Good catch!
 I will close this one. @rodolf0 feel free to leave a comment regarding DLNA in #1008 :)

**Closed as completed by graciousgrey** 2022-02-09 12:50 UTC
Labels: duplicate
