### ISSUE TITLE
[Mobile]: Infinite scroll not working

### ISSUE THREAD

**Issue by linosgian** [photoprism/photoprism#242] opened 2020-02-04 20:26 UTC
### Description
Even after the latest commit (491751f4fc7d7779f793b3773c6e6673c306b5ef),  infinite scrolling does not work on mobile devices. 

### Testing devices
A. Honor 10 - Chrome 79.0.3945.136
B. Samsung Tab A (2018) - Chrome 79.0.3945.136

### Potential root cause
I'm gonna take a leap here and guess what might affect the scrolling just for mobile devices:
https://github.com/photoprism/photoprism/blob/491751f4fc7d7779f793b3773c6e6673c306b5ef/frontend/src/pages/photos.vue#L90
`pageSize` initial value shown above is used to determine whether the next batch of photos (50?) should be loaded:
https://github.com/photoprism/photoprism/blob/491751f4fc7d7779f793b3773c6e6673c306b5ef/frontend/src/pages/photos.vue#L150-L151
https://github.com/photoprism/photoprism/blob/491751f4fc7d7779f793b3773c6e6673c306b5ef/frontend/src/pages/photos.vue#L167-L174

**Comment by lastzero** [comment] 2020-02-04 20:39
Strange, works for me on Android 10 with Chrome...

**Comment by lastzero** [comment] 2020-02-05 16:24
Wondering if anyone else has these issues and can confirm?

Our recent changes are there to keep all clients in sync. When you add or remove photos, the result is marked as dirty. In that case, we load the full list again and not just the next entries when scrolling down.

**Comment by linosgian** [comment] 2020-02-05 21:58
It seems that the infinite scroll library we're using (vue-infinite-scroll) might be outdated.
I found this related issue https://github.com/ElemeFE/vue-infinite-scroll/issues/124

**Comment by lastzero** [comment] 2020-02-16 06:20
They recommend adding `-webkit-user-drag: none;`, we can try that. Works when you install our Web app on the home screen (removes browser toolbar at the top). Maybe broke after updating dependencies. It used to work.

**Comment by lastzero** [comment] 2020-02-16 06:26
Tested it a second time and it worked. Maybe only happens when the browser toolbar is in a certain position.

**Comment by graciousgrey** [comment] 2020-02-16 13:33
I can reproduce it on Galaxy Tab A with Android 9 --> in the browser infinite scrolling does not work. If I open the progressive web app it works fine

**Comment by linosgian** [comment] 2020-02-16 21:57
It's definitely only occurring on Chrome (Android) devices. I've tested the same device (Honor 10) on Firefox Preview browser and the scrolling works just fine. Also tested this on Chrome on iOS and it also works fine. I could test what you're suggesting @lastzero.

**Comment by lastzero** [comment] 2020-03-23 21:02
Maybe this fixes it. Build is running!

**Comment by lastzero** [comment] 2020-03-24 15:18
Should be working now. Added touch event listeners to trigger refresh (top) and loadMore (bottom). Hope this doesn't break things in other / older browsers.

**Comment by linosgian** [comment] 2020-04-01 07:35
I just updated to the latest build, and it works fine on all devices/browsers (those I've tested at least)

**Comment by lastzero** [comment] 2020-04-01 08:04
Thank you for testing!

**Closed by lastzero** 2020-04-01 08:04 UTC
Labels: bug, please-test
