### ISSUE TITLE
Labels: Don't allow to create/rename labels with existing label names

### ISSUE THREAD

**Issue by hr-ru** [photoprism/photoprism#3736] opened 2023-09-18 01:04 UTC
(Similar to  #3434 but I see this issue only after manually renaming labels, not by just a library scan as described in that other issue)

#### 1. What is not working as documented?

In the "Labels" view, there are duplicated entries

#### 2. How can we reproduce it?

1. Import photos (assuming some labels are automatically assigned, e.g. the first "Bakery")
2. Manually label a photo (e.g. with "Bakeries")
3. Rename the manually created label (click on the label, modify, e.h. to "Bakery")
4. In the "Labels" view, there are now to labels "Bakery", each with one picture (clicking on either one will show both pictures)

Notes:
- This does not depend on automatic label assignment. You can as well manually label one photo with "A" and a second photo with "B" and then rename the label B to A to get a duplicate "A" entry under Labels

#### 3. What behavior do you expect?

Under "Labels", just a single entry for each label

#### 4. What could be the cause of your problem?

I assume something is handled incorrectly internally when a label is renamed

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

I can reproduce this was any two arbitrary pictures, so I assume there is no benefit from sharing specific pictures with you.
![Screenshot 2023-09-18 at 00 27 42](https://github.com/photoprism/photoprism/assets/101403752/3f32137f-01af-4250-8150-dbc081798deb)
![Screenshot 2023-09-18 at 00 28 08](https://github.com/photoprism/photoprism/assets/101403752/a44f0a79-3730-4395-b341-28019eb208a1)

This is how it looks like in the labels database:
```
sqlite> select * from labels where label_name="Regenbogen";
202|ls15ng34l2os8660|regenbogen|regenbogen|Regenbogen|10|0|||1|||2023-09-18 00:16:51.925405018+00:00|2023-09-18 00:16:51.976187752+00:00||
203|ls15nge33dortwww|rainbow|regenbogen|Regenbogen|10|0|||1|||2023-09-18 00:17:02.052458741+00:00|2023-09-18 00:17:08.433066316+00:00||
204|ls15nxc10yjqk5so|regen|regenbogen|Regenbogen|10|0|||1|||2023-09-18 00:27:12.591081024+00:00|2023-09-18 00:27:19.904587775+00:00||
sqlite> select * from labels where label_name="Horse";
102|ls0dqse1o6k5a07p|horse|horse|Horse|10|0|||10|562d0e47ae8a26694e93ff4acd831aebd677db78||2023-09-02 22:36:14.2214874+00:00|2023-09-07 22:09:03.120262133+00:00||
158|ls0jeq919te4a5yb|pferd|horse|Horse|10|0|||5|751839fca20ff2e513000a562ab73a4be9dfa346||2023-09-06 00:01:21.95378545+00:00|2023-09-06 00:03:57.521498565+00:00||
sqlite> select * from labels where label_name="Bakery";
171|ls0l77o15dgqzja8|bakery|bakery|Bakery|0|0|||1|ecb8350dd16a430254ae82af8b6d94f63918677c||2023-09-06 23:14:12.934622241+00:00|2023-09-06 23:14:12.961736135+00:00||
201|ls15mtc23t0g1jzw|bakeries|bakery|Bakery|10|0|||1|||2023-09-18 00:03:12.739247898+00:00|2023-09-18 00:03:39.266720387+00:00||

sqlite> select * from photos_labels where  label_id=171;
24960|171|image|16
sqlite> select * from photos_labels where  label_id=201;
17962|201|manual|0

sqlite> select * from photos_labels where  label_id=202;
35512|202|manual|0
sqlite> select * from photos_labels where  label_id=203;
35511|203|manual|0
sqlite> select * from photos_labels where  label_id=204;
35485|204|manual|0
sqlite> 

```

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...
PhotoPrism® CE  Build 230719-73fa7bbe8, ARMv7

(b) Database Type & Version: MariaDB, MySQL, SQLite,...
SQLite

(c) Operating System Types & Versions: Linux, Windows, Android,...
Ubuntu (Linux version 5.4.253-426) on Odroid (ARMv7)

#### 7. On what kind of device is PhotoPrism installed?

Odroid HC1 (ARMv7), 2G RAM, 8G Swap, SSD storage

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Apache reverse proxy, but should not be related to the issue.

**Comment by graciousgrey** [comment] 2023-09-18 11:50
This is to be expected. You create a new label and then change the name of the new label to a name that an existing label already has. The result is two labels with the same name. The duplicate label was created by you and not automatically generated by PhotoPrism. 

We do not automatically merge labels with the same name, nor do we prohibit two labels from having the same name. Either would be an enhancement rather than a bug, but we would need to weigh potential impacts before changing this.

You can easily prevent this by not renaming labels to a name that another label already has.
For example, if you find that you've given a photo the label "bakeries" but you'd rather assign it to the label "bakery," you can remove the "bakeries" label from the photo and add the existing "bakery" label.

**Comment by lastzero** [comment] 2023-09-19 22:25
@hr-ru Thanks for reporting this! I'll go ahead and close the issue since it is working as designed. However, if we work on the feature again, we will keep this in mind.

**Closed as completed by lastzero** 2023-09-19 22:25 UTC
Labels: won't fix

**Comment by hr-ru** [comment] 2023-09-19 23:02
Alright, thanks for having looked into this issue!

It was rather confusing when I first discovered duplicated labels without any obvious reasons, but now that I see the reason behind it, it is not a big issue (just need to remember if I accidentally miss-type a manually added label, I should not simply "change" it, but delete and add the correct one)

**Comment by robross0606** [comment] 2024-08-11 15:22
I still think there's a bug here because, once you _do_ create duplicate labels, PhotoPrism doesn't fully keep them separate.  The view shows the labels separately with correct counts:

![image](https://github.com/user-attachments/assets/4608a2d6-db09-4202-b2d6-80189249506b)

However, going into each label shows all the pictures from both labels in both views.  This is the label that claimed there was "one picture" in it:

![image](https://github.com/user-attachments/assets/2e9f2d9b-a3fa-4d46-88d1-ba51e06158c9)

That's still a semi-bug, even if PhotoPrism isn't going to auto-merge them.  Currently it keeps them separate in one view and merges them in another.  At the very least, this is a very confusing UX.  What would be great is if there were a way to select the label and have an option to move everything in that label to another label without doing each picture separately.

**Comment by robross0606** [comment] 2024-08-11 15:34
> ... you can remove the "bakeries" label from the photo and add the existing "bakery" label.

@graciousgrey, I feel really stupid, but I cannot figure out how to "add the existing... label" to a photo.  If I remove the duplicate label and type the label again, it just creates another duplicate.  This is such a strange UX for "labels" since deduplicating labels is entirely the _point_ of a label.  Look at anything that does label clouds (Jira, GitLab, etc.) and you'd see labels deduplicated by design.  Allowing duplication of identical labels is very very confusing and not really handled consistently or well by PhotoPrism right now.

**Comment by lastzero** [comment] 2024-08-11 15:52
I guess your particular issue here could be that "bakery" is a standard label i.e. one that the image classification uses. So you can certainly change how it's displayed (rename it), but if bakeries already exists and bakery gets merged (deleted), it will be recreated when the index is updated the next time.

**Comment by robross0606** [comment] 2024-08-11 16:09
I guess that is a problem because, so far in my experience, the auto-classification is terrible. It identified two of my example photos as "landscaping" and one as "beach". Pretty much all the auto-detected labels were way off the mark. If reindexing is going to bring those back and we cannot train the classifications, PhotoPrism becomes imminently less useful.  I assume this is Tensor flow at work, so I could just turn that off.

**Comment by lastzero** [comment] 2024-08-11 16:13
Note that when renaming an existing label, the search will find pictures with both the original label name and the new name, e.g. "Bakery" (English) and "Bäckerei" (German). This is to support foreign languages while also having a canonical (English singular) name for use in URLs, generated filters (moments) and for classification with TensorFlow. I agree that this can seem confusing and overly complex if you only speak English, manage all labels manually and e.g. only want to change a label from singular to plural.

**Comment by robross0606** [comment] 2024-08-11 16:17
Understood on the i18n complexity but, in this case, it isn't minor plurals I need to change. The automatic labels are just wildly wrong. I have things like "barn" for my house which is a 4000 square foot colonial on a hill with a front porch. If tensor flow is that bad, coupling it this tightly to basic functionally is problematic.

**Comment by lastzero** [comment] 2024-08-11 16:19
As publicly announced, we are currently working on advanced AI classification and label generation. However, these more powerful models will not run on the sometimes terrible hardware that many of our users have. That's why we've started with models that will run on most hardware, including Raspberry Pis.

**Comment by robross0606** [comment] 2024-08-11 16:27
Thanks for the details @lastzero.  That's great news since I'm running on fairly decent hardware.  Obviously not equivalent to a liquid-cooled server farm, but it is at least a dedicated, full-blown PC.  I don't mind Tensorflow making (bad) guesses.  The problem is just that adjusting or counteracting the outcome seems impossible at the moment.  Have I no choice but to either turn off Tensorflow or live with it classifying things in the strangest way possible?  Someone tell me how it decided to label this as "monitor": 🤣 
![image](https://github.com/user-attachments/assets/675a08f8-3182-408b-b311-c7c61dbbb18b)
