### ISSUE TITLE
Places: No pictures are displayed when clicking on some clusters

### ISSUE THREAD

**Issue by cttlee** [photoprism/photoprism#3953] opened 2023-12-14 14:03 UTC
#### 1. What is not working as documented?

I just index 5xk pictures but the 'places' not works well, thumbnails were shown on places but lot of "no pictures found" when clicked.
I choose some pictures and re-index about 13k from a fresh docker container of photoprism, issue still happen.

#### 2. How can we reproduce it?

1. Go to 'places'
2. Click on 'thumbnail'
3. See no "pictures found"

When reporting an import, indexing, or performance issue, please include the number and type of pictures in your library, as well as any configuration options you have changed, such as for thumbnail quality.

#### 3. What behavior do you expect?

places works

#### 4. What could be the cause of your problem?

No ideal

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
<img width="1055" alt="5" src="https://github.com/photoprism/photoprism/assets/449238/ebd461c5-f4fe-4dbd-811f-0a35933386c8">

<img width="1916" alt="3" src="https://github.com/photoprism/photoprism/assets/449238/caa36884-378d-4af8-8598-c4dc551a5a18">
<img width="1913" alt="4" src="https://github.com/photoprism/photoprism/assets/449238/4d14dbde-9124-49a8-9b63-1055a82ae593">

8 picture can be found on 'search'
<img width="604" alt="2" src="https://github.com/photoprism/photoprism/assets/449238/1c3d8f00-d67f-4ad9-a905-79b509867689">

pictures downloaded on search
[photoprism-download-20231214-134915-9e7iqnyb.zip](https://github.com/photoprism/photoprism/files/13674116/photoprism-download-20231214-134915-9e7iqnyb.zip)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64 Build [231128-f48ff16ef]

(b) Database Type & Version: MariaDB,

(c) Operating System Types & Versions:  Windows 10  / Docker 4.26

(d) Browser Types & Versions: Chrome,

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?: No

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: I3-2110

(b) Physical Memory & Swap Space in GB: 3G / 4G

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...: HDD

(d) Anything else that might be helpful to know?

Log when click thumbnail A/B

time="2023-12-14T14:07:50Z" level=debug msg="places: found 6,217 results for public:true dist:2.000000 count:500000 [420.7577ms]"
time="2023-12-14T14:07:50Z" level=debug msg="server: GET /api/v1/geo?count=500000&offset=0&q=&s=&public=true (200) [646.7535ms]"
time="2023-12-14T14:08:00Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [4.4ms]"
time="2023-12-14T14:08:00Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [4.9415ms]"
time="2023-12-14T14:08:01Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [3.2338ms]"
time="2023-12-14T14:08:01Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [3.795ms]"
time="2023-12-14T14:08:01Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [4.6916ms]"
time="2023-12-14T14:08:01Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [5.1798ms]"
time="2023-12-14T14:08:01Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [4.1012ms]"
time="2023-12-14T14:08:01Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [4.5609ms]"
time="2023-12-14T14:08:03Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8927001953125,116.31600189208984,39.8927001953125,116.31600189208984 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [3.2881ms]"
time="2023-12-14T14:08:03Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8927001953125,116.31600189208984,39.8927001953125,116.31600189208984&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [3.8244ms]"
time="2023-12-14T14:08:03Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8927001953125,116.31600189208984,39.8927001953125,116.31600189208984 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [4.1946ms]"
time="2023-12-14T14:08:03Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8927001953125,116.31600189208984,39.8927001953125,116.31600189208984&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [4.6808ms]"
time="2023-12-14T14:08:03Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8927001953125,116.31600189208984,39.8927001953125,116.31600189208984 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [4.0474ms]"
time="2023-12-14T14:08:03Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8927001953125,116.31600189208984,39.8927001953125,116.31600189208984&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [4.5905ms]"
time="2023-12-14T14:08:04Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [3.2273ms]"
time="2023-12-14T14:08:04Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [3.7402ms]"
time="2023-12-14T14:08:04Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [4.2134ms]"
time="2023-12-14T14:08:04Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [4.622ms]"
time="2023-12-14T14:08:05Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8927001953125,116.31600189208984,39.8927001953125,116.31600189208984 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [4.9984ms]"
time="2023-12-14T14:08:05Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8927001953125,116.31600189208984,39.8927001953125,116.31600189208984&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [5.4959ms]"
time="2023-12-14T14:08:13Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8927001953125,116.31600189208984,39.8927001953125,116.31600189208984 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [3.1156ms]"
time="2023-12-14T14:08:13Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8927001953125,116.31600189208984,39.8927001953125,116.31600189208984&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [3.5103ms]"

**Comment by lastzero** [comment] 2023-12-14 14:16
Thanks a lot! We will test it with the files and coordinates you provided. This might be a special case where the bounding box calculated by the user interface does not match the actual coordinates in the database, so the query returns 0 results.

**Comment by cttlee** [comment] 2023-12-14 14:19
It wired I tried upload those pictures on demo photoprism, but it was woks.

**Comment by lastzero** [comment] 2023-12-14 14:25
@cttlee If you have any idea what else could be causing this, please let us know. For example, you could try a different browser. A complete rescan may help as well. Also, make sure your instance can [communicate with our geocoding API](https://docs.photoprism.app/getting-started/troubleshooting/firewall/#outgoing-connections) in case a reverse geocoding error is preventing the index from being updated.

Are we allowed to upload your file samples to https://dl.photoprism.app/samples/ for further testing?

**Comment by cttlee** [comment] 2023-12-14 14:27
sure, no problem

**Comment by lastzero** [comment] 2023-12-14 14:32
Thank you! I've uploaded them to https://dl.photoprism.app/samples/JPEG/Issue%203953/.

**Comment by cttlee** [comment] 2023-12-14 14:36
browser: same result on edge, chrome and firefox
make sure your instance can communicate with our geocoding API: most pictures works on places

**Comment by lastzero** [comment] 2023-12-14 14:38
Going through the following checklist could also help:

- https://docs.photoprism.app/getting-started/troubleshooting/#missing-pictures

For example, the images might be marked as private, be stacked or under review...

**Comment by lastzero** [comment] 2023-12-14 14:42
The pictures could also be found in clusters nearby if you have taken other photos in this area.

**Comment by cttlee** [comment] 2023-12-14 14:49
> The pictures could also be found in clusters nearby if you have taken other photos in this area.

I can't find pictures in cluster A from cluster B
<img width="979" alt="7" src="https://github.com/photoprism/photoprism/assets/449238/d5255b69-056d-45e1-b821-eaa72e9f86cc">

**Comment by cttlee** [comment] 2023-12-14 15:02
How I test the api with GET?
{"code":401,"error":"Please log in to your account"}

test url
http://192.168.1.123:2342/api/v1/photos?count=120&offset=360&merged=true&country=&camera=0&lens=0&label=&latlng=38.49129867553711,-115.17500305175781,35.132598876953125,-122.7490005493164&year=0&month=0&color=&order=newest&q=&public=true&s=

**Comment by lastzero** [comment] 2023-12-14 15:16
If this is a local server that you use for testing, you can enable public mode, which disables API authentication:
- https://docs.photoprism.app/getting-started/config-options/#authentication

Alternatively, add an "X-Session-ID" header to your requests, as shown here:
- https://docs.photoprism.app/developer-guide/api/#request-examples

**Comment by cttlee** [comment] 2023-12-15 01:21
<img width="1916" alt="290541871-caa36884-378d-4af8-8598-c4dc551a5a18" src="https://github.com/photoprism/photoprism/assets/449238/b3ef62a8-ad54-423f-ab6a-41b064b3c0e6">

GPS  39.892216 116.31464

Log when cluster clicked: no picture found
photoprism-1  | time="2023-12-15T01:08:57Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625&year=0&month=0&color=&order=newest&q=&public=true&s= (200) [3.952ms]"
photoprism-1  | time="2023-12-15T01:08:58Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 latlng:39.8922004699707,116.31500244140625,39.8922004699707,116.31500244140625 camera:0 lens:0 year:0 month:0 count:120 order:newest merged:true [4.783ms]"

Changed URL as below: pictures found
api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.8922164699707,116.31500244140625,39.8922004699707,116.31**463**244140625&year=0&month=0&color=&order=newest&q=&public=true&s=


same result on edge, chrome and firefox, and it works well when uploading those pictures to https://demo.photoprism.app

**Comment by cttlee** [comment] 2023-12-15 02:22
Fresh photoprism docker container, just upload those 8 pictures by browser, it works on 'places', will index more again.

photoprism-1  | time="2023-12-15T02:18:35Z" level=debug msg="photos: found 4 results for public:true dist:2.000000 latlng:39.892215728759766,116.31463623046875,39.892215728759766,116.31463623046875 camera:0 lens:0 year:0 month:0 quality:3 count:120 order:newest merged:true [5.629ms]"
photoprism-1  | time="2023-12-15T02:18:35Z" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=39.892215728759766,116.31463623046875,39.892215728759766,116.31463623046875&year=0&month=0&color=&order=newest&q=&public=true&quality=3&s= (200) [18.2796ms]"

**Comment by cttlee** [comment] 2023-12-15 02:47
Just indexed 1xx pictures, the issue found

**Comment by cttlee** [comment] 2023-12-15 07:53
Fresh preview version, indexed 1xx pictures: Issue reproduced
Downgrade photoprism version in container to 1011, 0923:  Issue reproduced
Downgrade to 0719: Issue not reproduced
Indexed another 1k+ pictures no abnormal found in 'places', it seems the issue is related to cluster view.

**Comment by lastzero** [comment] 2023-12-15 09:23
@cttlee @heikomat This confirms my suspicion that the bounding box coordinates could be slightly off in these cases:

https://github.com/photoprism/photoprism/blob/8e81f78c120fb8573f0a713353bd4dd1957f5501/frontend/src/page/places.vue#L354-L368

So either something is wrong with our code in [`places.vue`](https://github.com/photoprism/photoprism/blob/develop/frontend/src/page/places.vue), or it is an inaccurate calculation in the MapLibre library we use?

**Comment by cttlee** [comment] 2023-12-15 11:57
I'm not familiar with frontend, but my understanding is when user clicking cluster icon, the limit/range of lat and lng passed to database for quering images is not accurate

**Comment by lastzero** [comment] 2023-12-16 16:16
@cttlee I'll try to take a look before leaving our office for the holidays! If anyone finds a way to fix the miscalculated coordinates before I do, please leave a comment :)

**Comment by cttlee** [comment] 2023-12-22 06:11
@lastzero The key point to reproduce the issue is "Quality Filter" 

Pictures displayed when "Quality Filter" checked
Pictures can't display when "Quality Filter" un-checked

**Comment by graciousgrey** [comment] 2023-12-22 15:11
> Pictures displayed when "Quality Filter" checked
Pictures can't display when "Quality Filter" un-checked

Good catch, I can now reproduce it consistently.

**Comment by GarryLai** [comment] 2024-07-16 02:32
@cttlee @lastzero Did anyone find out the bug? This has been exist for a long time.

**Comment by lastzero** [comment] 2024-07-28 16:02
@GarryLai @cttlee Thank you! The pull request was really helpful. After seeing it, I dug a little deeper and found that the regular Search UI sets the quality filter when enabled, while the Places UI did not. With today's changes, this should be fixed (except maybe for edge cases where you use the maps in combination with other views or when you reuse it after changing the scope/other filters).

We started a new development preview build for you so you can test this:

- https://docs.photoprism.app/getting-started/updates/#development-preview

**Please let us know if it works for you!** :crossed_fingers:

**Comment by lastzero** [comment] 2024-09-15 12:06
After further testing, it seems likely that the remaining issues were caused by rounding errors when converting coordinates from 32 to 64 bit floating point numbers. These changes therefore ensure that latitude and longitude coordinates are always stored and processed with 64-bit precision. In addition, I have made the padding of bounding boxes (as used when querying pictures in a cluster) more accurate, since the proper search range for the longitude depends on the latitude.

**Comment by lastzero** [comment] 2024-09-15 22:02
A [new release](https://docs.photoprism.app/release-notes/) that includes these fixes and improvements will be available soon! If you are affected by this issue, please note that [a complete re-scan](https://docs.photoprism.app/user-guide/library/originals/) will be required after the update to improve the GPS location accuracy of your pictures.

**Closed as completed** 2024-09-16 07:29 UTC
Labels: bug, help wanted, released, frontend, places
