### ISSUE TITLE
UX: Auto Import / Index

### ISSUE THREAD

**Issue by p-baum** [photoprism/photoprism#281] opened 2020-04-09 12:24 UTC
I would prefer to automate the import of files that find their way to my Import directory.  How about some kind of Import directory polling/watching?

**Comment by lastzero** [comment] 2020-04-09 12:38
That's basically what happens when you use our integrated WebDAV sync feature. We think about adding more options / workers to run additional operations in the background, although it might impact performance for some users and consume additional energy (for example, because the CPU frequently wakes up from sleep).

**Comment by p-baum** [comment] 2020-04-09 12:43
What/where is the integrated WebDAV sync feature?

**Comment by p-baum** [comment] 2020-04-09 13:32
Actually the use case I have in mind here is for importing from the filesystem for which the WebDAV feature bears no relevance.

**Comment by lastzero** [comment] 2020-04-09 14:08
Our copy command works from any local directory and will only import new files without modifying the source. You can easily run it with cron. For remote file systems / APIs, we will provide additional support in the future.

**Comment by p-baum** [comment] 2020-04-09 14:11
Ok. I was hoping to avoid cron.  Can of worms on docker.

**Comment by RAYs3T** [comment] 2020-08-05 07:00
@p-baum You could define the cron on the host-system and pass the command to the docker. Using thatmethod you wouldn't have to deal with modification to the original image / container.

For example: 
```shell

*/10 * * * * docker exec <container-name> /bin/bash echo "This is executed in the container..."
```

**Comment by lastzero** [comment] 2020-08-11 20:46
Reason we don't import / index originals automatically is that we don't know when files are added / modified. So it might happen that PhotoPrism tries to index a file that is currently being uploaded, and that will lead to an error (at best). Maybe not a big deal, but it's better to run indexing operations when you know other apps don't perform changes at the same time or at a time you know is safe.

**Comment by rainsuns** [comment] 2020-10-02 15:17
> Reason we don't import / index originals automatically is that we don't know when files are added / modified. So it might happen that PhotoPrism tries to index a file that is currently being uploaded, and that will lead to an error (at best). Maybe not a big deal, but it's better to run indexing operations when you know other apps don't perform changes at the same time or at a time you know is safe.

Excuse me, I want to create a timed task to automatically index photos at 2 AM, how do I do it?

**Comment by RAYs3T** [comment] 2020-10-05 07:43
@rainsuns If you're on linux you could create a cron job that executes a command in the docker container using `docker exec`

For example (on your host system) use `crontab -e` to edit your cronjobs.
Make sure to do this for either the root user (`crontab -e  -u root`) or a user that is in the docker group so it can execute commands against the docker daemon.

Add  a new line to the cron file
```crontab
0 2 * * *    /usr/bin/docker exec -it <name_of_photo_prism_container> /photoprism/bin/photoprism index
```
Replace `<name_of_photo_prism_container>` with the name of your PP container (`docker ps` will tell you the name`).


Extra tip, for more special times here is a great site for cron timings:
https://crontab.guru/#0_2_*_*_*

**Comment by thelioncape** [comment] 2020-11-01 13:28
I think this would be a useful feature - similar to how the blackhole idea works with bittorrent clients.
The service would check a blackhole directory for photos, videos, etc. periodically (every few minutes? It's not an intensive operation to list files in a directory) and then move and process the files into folders in the photo library. I'm happy to try making something like this if it's something that's likely to be implemented

**Comment by Engr-AllanG** [comment] 2020-11-19 18:56
I am currently trying to determine the best way to autosync as well, so I can have auto upload with my phone. I tried out Nextcloud but had issues with Nextcloud's auto upload and duplicate files. I trieid Seafile but looks like android auto uplaod is currently broken. Regardless I don't really want a duplicate library in Nextcloud. Next I tried FolderSync on android to upload via webdav directly to originals folder. But as discussed in this thread, you have to manually initiate indexing or use Cron or something. I suppose I could have the cron job run every few minutes, but having it auto scan a folder sounds better. I don't know anything about cron yet.

The other way I'm looking at doing it is in conjunction with FolderSync, creating a webdav server or adding webdav to my samba server and then using the already exiting photoprism sync-via-webdav feature

**Comment by voarsh2** [comment] 2020-12-29 04:27
> 0 2 * * *    /usr/bin/docker exec -it <name_of_photo_prism_container> /photoprism/bin/photoprism index

This is helpful, I haven't looked into WebDav, but indexing for me, for my existing files on my NAS, seems a much easier way to go for me, so I think this should be documented/made more norm.

**Comment by lastzero** [comment] 2021-01-02 18:09
This will automatically trigger indexing / importing after WebDAV uploads, deleting, renaming, editing, copying, and moving.

We still don't use a general file system change listener or simple timer because...

1. not all operating systems and file systems support notifications
2. these have a file count limit which some users may exceed
3. there is a certain risk this may cause feedback loops or bad performance, e.g. when auto importing to originals triggers the auto indexer (not needed since the importer already added new files to the index) or in combination with external apps and events
4. if we don't use a listener and just start indexing "randomly", there is a big risk of conflicts with other applications / user operations happening at the same time

I'm willing to look further into is when someone explains why 1 - 4 are no problems, and should better be ignored :ghost:

**Comment by lastzero** [comment] 2021-01-02 18:53
Only watching the import folder may be easier as there **typically** shouldn't be as many files. We may still have to deal with users who import their complete, existing library with potentially millions of files. Those edge cases shouldn't break the app, or crash the operating system.

**Comment by swingstate** [comment] 2021-01-04 15:12
Testing this now with Iphone + PhotoSync. After the upload, when should the photo become visible?

**Comment by lastzero** [comment] 2021-01-04 15:18
After it has been imported. Auto refresh depending on your sort order. Try recently added.

**Comment by lastzero** [comment] 2021-01-04 15:18
You can configure the delay using the config options listed in our docs.

**Comment by swingstate** [comment] 2021-01-04 15:38
Thanks for the hint. Manual import worked well and now out import & index does too. 

@ich777 Can you add 

PHOTOPRISM_AUTO_INDEX | --auto-index SECONDS | auto indexing safety delay in SECONDS (WebDAV)

PHOTOPRISM_AUTO_IMPORT | --auto-import SECONDS | auto importing safety delay in SECONDS (WebDAV)

I am using 60 seconds delay for import and 120 seconds for import as default values at the moment.

to the Unraid template?

**Comment by lastzero** [comment] 2021-01-04 15:42
Delay should depend on your network speed and file size. If you're uploading videos from China, use a longer delay. 60s should work for importing images locally. Or default is 15 minutes, so pretty conservative.

**Comment by swingstate** [comment] 2021-01-04 15:43
good hint. I would upload locally only until 2FA is in place ;o)

**Comment by lastzero** [comment] 2021-01-04 15:46
VPN FTW 🥁

**Comment by ich777** [comment] 2021-01-04 20:30
@swingstate is this really needed?
If someone really needs this he can adds this on his own, what I can add and makes sense to me is a link to the Documentation since PhotoPrism will change much things because it's in heavy development from what I've seen.

**Comment by lastzero** [comment] 2021-01-04 20:39
@ich777 Heavy development? We're implementing your feature requests.... to @swingstate's point: I think this is an important setting, as many users will want to index and import automatically... for this reason, we've implemented this on a weekend and didn't wait until next year 👍

**Comment by ich777** [comment] 2021-01-04 20:43
I mean PhotoPrism itself is under heavy development and think you will add more and more features and variables or am I wrong.
I can of course add them, don't wanted to offend anyone that's why I asked. :)

**Comment by lastzero** [comment] 2021-01-04 20:50
Not if we can help it... personally think we have too much config already, but this was needed... most of what is added next will be in `settings.yml`, and not available via env variable. So not much more work for you! :)

To disable auto indexing / importing, use a negative value like `-1`. `0` defaults to the existing worker interval, which happens to be 15 minutes. If auto import is `0`, it defaults to the auto index value. Or you can use individual values by not setting everything to `0`. Guess you see the pattern?

**Comment by swingstate** [comment] 2021-01-04 20:50
This is how I added the two manually and it works flawless. 

<img width="1140" alt="Bildschirmfoto 2021-01-04 um 21 47 40" src="https://user-images.githubusercontent.com/73672554/103578345-ac8fb880-4ed6-11eb-904a-afe12b25ed08.png">

Since adding photos to photoprism is a key element of the whole user story I think the docker template should include this, at least in the addtl. settings.

**Comment by lastzero** [comment] 2021-01-04 20:51
We can add the vars to our default Dockerfile, thanks for the reminder!

**Comment by lastzero** [comment] 2021-01-04 20:58
Done!

**Comment by ich777** [comment] 2021-01-04 21:08
@swingstate Updated the Unraid template, will take a few hours that the change will show up in the CA App.
Set the values to 180 seconds.

**Comment by swingstate** [comment] 2021-01-04 21:09
do I need to remove the variables again, since I added them manually?

**Comment by ich777** [comment] 2021-01-04 21:10
@swingstate No, just leave your template as it is.

**Comment by Engr-AllanG** [comment] 2021-01-04 22:07
I just tested this change with success!

-Pulled/started latest docker image
-Turned off my cron job I had been using to trigger import
-Synced my latest photos to the import folder via photosyc app from android
-Photoprism auto imported and indexed after some period of time

-Allan

**Comment by lastzero** [comment] 2021-01-07 09:14
Seems the typical file watching limit is too low for applications with many files (like IDEs or PhotoPrism):
https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit

**Comment by swingstate** [comment] 2021-01-07 10:18
Is that a problem or a challenge? What does that mean in this context?

**Comment by RAYs3T** [comment] 2021-01-07 10:21
@lastzero Is any other change required besides adding the intervals to the `docker-compose.yml`?
I've tried this today but it simply won't process newly uploaded files via WebDAV.

The processing should be shown in the docker-compose logs (general stdout log)?

![image](https://user-images.githubusercontent.com/16596807/103880759-db29b100-50d9-11eb-8730-153dde027cd2.png)

Maybe this is an issue with network mounted folders, since I mount mine via NFS from Docker.
![image](https://user-images.githubusercontent.com/16596807/103881160-5c814380-50da-11eb-97fa-7281e9c03b65.png)

When I re-enable my cron which just does `/usr/bin/docker exec photoprisim_photoprism_1 photoprism index` it works fine.

**Comment by lastzero** [comment] 2021-01-07 10:22
Just for us to remember should we want to implement file watchers in addition to the existing and working WebDAV watchers.

**Comment by marcusbabajews** [comment] 2021-01-07 23:58
I'm happy to see this thread is so active.

I've just finished a 40 hour indexing operation and don't wish to repeat it :)
I want to implement a cron job to run the reindex on my originals every night by using

`/photoprism/bin/photoprism index`

Before even touching this command **I need to understand whether the command will perform a complete rescan or not**. (I see no obvious switches that affect this behaviour)

Thanks team - love the software!

**Comment by marcusbabajews** [comment] 2021-01-08 01:51
Apologies but i'm answering my own question. 

Using the --help option after "index" i found some more information. It turns out that it is 'safe' to run this command on its own. To prompt a rescan -a needs to be used.

I'm successfully doing simple re-indexing using the command in my OP.

Thanks again all.

> I'm happy to see this thread is so active.
> 
> I've just finished a 40 hour indexing operation and don't wish to repeat it :)
> I want to implement a cron job to run the reindex on my originals every night by using
> 
> `/photoprism/bin/photoprism index`
> 
> Before even touching this command **I need to understand whether the command will perform a complete rescan or not**. (I see no obvious switches that affect this behaviour)
> 
> Thanks team - love the software!

**Comment by lastzero** [comment] 2021-01-08 09:35
Here's a [command reference](https://docs.photoprism.org/getting-started/docker-compose/#command-reference) from our docs:

![Screenshot 2021-01-08 at 10 35 06](https://user-images.githubusercontent.com/301686/103999454-32448a00-519d-11eb-8e79-96743c3bab6f.png)

**Comment by lastzero** [comment] 2021-01-08 09:39
Note that even a complete rescan is MUCH faster once you have thumbnails. Creating those typically requires the most time when you index for the first time. That's also why I'm wondering so many users don't want to store any thumbnails at all. It means indexing will be that slow forever.

**Closed** 2021-01-08 09:40 UTC
Labels: done, idea, sponsor

**Comment by AlexanderSch90** [comment] 2021-01-12 12:15
Please Update: https://docs.photoprism.org/getting-started/config-options/

What does the following code ? ENV PHOTOPRISM_WORKERS 0 

Do I have to set the parameter to 1 for an enabled auto index?

**Comment by lastzero** [comment] 2021-01-12 12:19
If PHOTOPRISM_WORKERS is 0, "", or not set at all, the default will be used depending on your CPU and database - so we can't put a specific value in our docs. The CLI lib we use shows 0 as default as it is an integer. It is not possible to set an integer to an empty string or NULL.

**Comment by lastzero** [comment] 2021-01-12 12:20
Running `photoprism help` and `photoprism config` will show the default, as documented. See command reference.

**Comment by lastzero** [comment] 2021-01-12 12:20
If PHOTOPRISM_WORKERS would be 0, you could not index at all - not only auto indexing would be affected.

**Comment by lastzero** [comment] 2021-01-12 12:22
@AlexanderSch90 Just checked our docs - where do you see `ENV PHOTOPRISM_WORKERS 0`?

**Comment by AlexanderSch90** [comment] 2021-01-12 13:02
> If PHOTOPRISM_WORKERS would be 0, you could not index at all - not only auto indexing would be affected.

https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/Dockerfile

**Comment by AlexanderSch90** [comment] 2021-01-12 13:03
> @AlexanderSch90 Just checked our docs - where do you see `ENV PHOTOPRISM_WORKERS 0`?

https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/Dockerfile

**Comment by AlexanderSch90** [comment] 2021-01-12 13:08
Okay my photoprism config says that PHOTOPRISM_WORKERS 2
and 
PHOTOPRISM_AUTO_INDEX 300
PHOTOPRISM_AUTO_IMPORT 300

That means, that after 300 Minutes an Auto Import AND Auto Index will be generate? I will try this...

**Comment by lastzero** [comment] 2021-01-12 13:29
> > @AlexanderSch90 Just checked our docs - where do you see `ENV PHOTOPRISM_WORKERS 0`?
> 
> https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/Dockerfile

This is our Docker image for developers, not sure why you're trying to use this to set up PhotoPrism as a user?

We should add `PHOTOPRISM_AUTO_INDEX` to our `docker-compose.yml` examples though...

**Comment by AlexanderSch90** [comment] 2021-01-12 13:33
Yes! I use your Dockerfile. I want this feature. It will be nice, if you add PHOTOPRISM_AUTO_INDEX and Import to your docker-compose.yml

But if i run photoprism config in my docker container i see:
PHOTOPRISM_AUTO_INDEX 300
PHOTOPRISM_AUTO_IMPORT 300

So it is still enable by default?! For me its OK. Thanks for your work!

**Comment by lastzero** [comment] 2021-01-12 13:35
It defaults to `PHOTOPRISM_WAKEUP_INTERVAL`

**Comment by AlexanderSch90** [comment] 2021-01-15 06:28
sorry, but the automatic import is not working in my Docker container. I have set this ENV an wait 24 hour without a result:
```
      PHOTOPRISM_WAKEUP_INTERVAL: 900
      PHOTOPRISM_AUTO_INDEX: 300
      PHOTOPRISM_AUTO_IMPORT: 300
```
What should i do to get it work?

**Comment by lastzero** [comment] 2021-01-15 09:44
Are you using webdav to copy / add files? Is read only mode disabled?

**Comment by RAYs3T** [comment] 2021-01-15 11:58
@lastzero Can confirm that this is not working (using PhotoSync to add pictures via WebDav).
My first guess was that this is caused by my way of mounting the filesystem via NFS, but now that @AlexanderSch90 has the same issue without doing so, it might be something else.

If I have some time on the weekend I might be able to debug it on mysystem and dig around a little bit.

**Comment by AlexanderSch90** [comment] 2021-01-15 14:27
Here NFS too

**Comment by RAYs3T** [comment] 2021-01-15 14:31
Oh, well - I will try to enable the atime later for this volume. I could imagine that this is causing the issue. Is this also disabled for your's?

**Comment by lastzero** [comment] 2021-01-15 14:31
Doesn't matter where you store your photos as auto indexing is triggered by our WebDAV server - not the file system.

**Comment by RAYs3T** [comment] 2021-01-15 14:37
So neither the file "changed" timestamp nor kernel notification for file changes is used? Guess you store and use the time in the database instead? Which makes this even more interesting...

**Comment by lastzero** [comment] 2021-01-15 14:43
Getting all mixed up: We use WebDAV events for triggering auto indexing, which indexes changed / added files based on the filesystem mod time & file size - just like when you manually start indexing, unless you perform a complete rescan as documented.

**Comment by AlexanderSch90** [comment] 2021-01-22 21:53
> @lastzero Can confirm that this is not working (using PhotoSync to add pictures via WebDav).
> My first guess was that this is caused by my way of mounting the filesystem via NFS, but now that @AlexanderSch90 has the same issue without doing so, it might be something else.
> 
> If I have some time on the weekend I might be able to debug it on mysystem and dig around a little bit.


Does it work for you now?
Not at my place. I use the Docker latest...

**Comment by darrepac** [comment] 2021-02-26 16:15
I am not sure to get it.
I have my photos file stored on a NAS. Photos folder is nfs mounted into my raspberry pi where I am running Photoprism pointing to mounted photo folder..
It is slowly but happily indexing since I also mounted a folder for "storage" (which I didn't at first and it made everything crash cause the storage folder fullfill my raspberry sd card).
Once everything is indexed, my wish (and the way I was using with google photos):
- auto upload of my photos taken on my iPhone (seems to be supported by the ios app) but I don't have clear if once imported it is automatically viewable on photoprism web interface or it needs a manual index?? I would like to be automatically viewable on Photoprism
- manual indexing for all the photos every night. Particularly useful for photos I put from a camera into my PC (no need for instant photoprism support as, previsouly, it was taking time for google photos to upload all the photos). This part seems ok for what I have seen above with cron job

Thanks for the clarifications

**Comment by lastzero** [comment] 2021-02-26 17:05
Files will automatically be indexed / imported if synced (uploaded) via WebDAV - but not if you manually copy them to the filesystem as we want avoid situations where files are still being transferred or related sidecar files are not copied yet. That's why you currently should start indexing manually at a time that seems right for you. If you know there are no other filesystem operations at night, you may run this as a cron job. In other environments, there might be conflicting batch operations of other apps running at night.

**Comment by darrepac** [comment] 2021-02-26 17:18
Is the ios app using webdav for upload?

**Comment by lastzero** [comment] 2021-02-26 17:42
The PhotoPrism iOS app is a community project and not developed by us. Not 100% sure how it's implemented. You may want to try PhotoSync for uploading via WebDAV.

**Comment by darrepac** [comment] 2021-02-26 17:44
Ok, will take a deeper look

**Comment by shasycouk** [comment] 2021-03-10 15:12
I was using PhotoSync already, on both Android and iOS, but with SMB. Luckily enough I came across this thread here. Changed it to WebDAV én voila, automatic importing. Amazing. Cannot say it enough: thanks so much for all your hard work.

**Comment by Birdheezy** [comment] 2021-03-20 18:42
> I am currently trying to determine the best way to autosync as well, so I can have auto upload with my phone. I tried out Nextcloud but had issues with Nextcloud's auto upload and duplicate files. I trieid Seafile but looks like android auto uplaod is currently broken. Regardless I don't really want a duplicate library in Nextcloud. Next I tried FolderSync on android to upload via webdav directly to originals folder. But as discussed in this thread, you have to manually initiate indexing or use Cron or something. I suppose I could have the cron job run every few minutes, but having it auto scan a folder sounds better. I don't know anything about cron yet.
> 
> The other way I'm looking at doing it is in conjunction with FolderSync, creating a webdav server or adding webdav to my samba server and then using the already exiting photoprism sync-via-webdav feature. The downside to this is currently photoprism sync is limited to a minimum of once an hour. I'm trying to replace my phone photo app, and this requires 'instant' upload so that I could share via public link a photo/video right after taking the picture (which I do quite a bit, mostly for large videos)

This is exactly my use case. Trying to move away from 3rd party photo hosting and host it myself. Trying to figure out how to get photoprism to scan folders to look for updates/added files but looks like from other comments on here that's not possible. I'm not familiar with the webdav import function but maybe that's my best bet. 

I setup an import folder, but there's no way to import files to a specific folder. it just imports to year/month/file.jpg. I want to keep all my phone photos in 1 folder so even with this import function, it won't do what i want.

The ability to add photos to the import folder, then let PP import to specific folders them based on the camera that took the photo would be awesome. Aka, drop all my pixel phone photos and canon 6D photos into the import folder, then any pixel photos are sent to photos/pixel/camera and canon 6D are sent to photos/canon 6D. Since PP is smart enough to know which camera took which photo.

**Comment by graciousgrey** [comment] 2021-03-22 13:40
@Birdheezy If you want all your phone photos in a separate folder and not organized by date taken, you can move them via webDAV to the originals folder instead of import e.g. ` originals/phone`. You can use  apps like  PhotoSync to do this automatically. 
When new files are added to the originals or import folder via webDAV PhotoPrism will start indexing/importing those files with a short delay automatically.

**Comment by mmontes11** [comment] 2021-05-13 19:32
I am not using WebDav in my media workflow, so I've created this to automatically index my originals:
https://github.com/mmontes11/photoprism-auto-index

I hope it can help somebody with the same problem 😄

**Comment by graciousgrey** [comment] 2021-05-20 11:49
Now you can find example docker-compose.yml + job.ini files here: https://dl.photoprism.org/docker/scheduler/.
Within the jobs.ini you can configure when and how often commands (e.g. index or import) should run. This is independent from WebDav :)

**Comment by ITCMD** [comment] 2021-05-21 13:50
How would one schedule a cron job on a Windows Docker install?

**Comment by TimoJohn** [comment] 2021-05-26 13:11
The solution with the Jobs runs like charm together with traefik . 
Thanks to all of you!

**Comment by lastzero** [comment] 2021-05-26 13:27
> How would one schedule a cron job on a Windows Docker install?

The same way as shown in https://dl.photoprism.org/docker/scheduler/

**Comment by Heisenberg2980** [comment] 2021-08-24 10:10
> @rainsuns If you're on linux you could create a cron job that executes a command in the docker container using `docker exec`
> 
> For example (on your host system) use `crontab -e` to edit your cronjobs.
> Make sure to do this for either the root user (`crontab -e -u root`) or a user that is in the docker group so it can execute commands against the docker daemon.
> 
> Add a new line to the cron file
> 
> ```
> 0 2 * * *    /usr/bin/docker exec -it <name_of_photo_prism_container> /photoprism/bin/photoprism index
> ```
> 
> Replace `<name_of_photo_prism_container>` with the name of your PP container (`docker ps` will tell you the name).
> 
> I'm using the docker flag `-i` so that you can see the output in the system logs.
> 
> Extra tip, for more special times [here ](https://crontab.guru/#0_2_*_*_*)is a great site for cron timings

Thank you very much for this command, it is exactly what I was looking for!!

Btw, if anyone is trying to add this to cron and getting the error "the input device is not a TTY", just remove the "-ti" parameter:

'''0 2 * * *    /usr/bin/docker exec <name_of_photo_prism_container> /photoprism/bin/photoprism index'''

**Comment by SiJiL82** [comment] 2022-03-15 11:33
I've been using `docker exec -it photoprism /photoprism/bin/photoprism import` which has stopped working with the error `stat /photoprism/bin/photoprism: no such file or directory`
Does anyone know what the path for automating the import call should be now?

**Comment by RAYs3T** [comment] 2022-03-15 12:54
Just leave out the path.

`docker exec -it photoprism photoprism import`

**Comment by adyanth** [comment] 2022-06-10 06:24
Planning to use this for calling from a Kubernetes CronJob.

```python
import requests

baseurl = "https://photoprism.domain.com"

auth = {"username": "admin", "password": "pass"}
res = requests.post(
    f"{baseurl}/api/v1/session", json=auth, verify=False
)
res.raise_for_status()
session = {"X-Session-ID": res.headers["x-session-id"]}

data = {
    "path": "/", "convert": True,
    "rescan": False, "skipArchived": False
}
res = requests.post(
    f"{baseurl}/api/v1/index", json=data,
    headers=session, verify=False
)
res.raise_for_status()
print(res.json())
```

**Comment by mmontes11** [comment] 2022-06-10 06:34
@adyanth I also used a CronJob for this, but calling the `index`subcommand instead:

https://github.com/mmontes11/charts/blob/main/charts/photoprism/templates/cronjob.yml#L36

**Comment by adyanth** [comment] 2022-06-10 07:26
@mmontes11 looks like that would need an RWX volume mount for photoprism? I am using the sqlite DB, so that won't be a good idea for me. I preferred connecting to the existing photoprism service and call the index API.

Edit: This works well for me.

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "photoprism-cron"
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron
              image: python:alpine
              imagePullPolicy: IfNotPresent
              command:
                - sh
              args:
                - -c
                - "pip install requests; clear; python /scripts/index.py"
              envFrom:
                - secretRef:
                    name: photoprism
              volumeMounts:
                - mountPath: /scripts
                  name: scripts
          volumes:
            - name: scripts
              configMap:
                name: photoprism-scripts
          restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: photoprism-scripts
data:
  index.py: |
    import os
    import requests

    baseurl = os.environ.get("PHOTOPRISM_BASE_URL", "http://photoprism:2342")

    auth = {
        "username": os.environ.get("PHOTOPRISM_ADMIN_USERNAME", "admin"),
        "password": os.environ["PHOTOPRISM_ADMIN_PASSWORD"]
    }
    res = requests.post(
        f"{baseurl}/api/v1/session", json=auth, verify=False
    )
    res.raise_for_status()
    session = {"X-Session-ID": res.headers["x-session-id"]}

    print("---> Logged in, indexing now...")

    data = {
        "path": os.environ.get("PHOTOPRISM_INDEX_PATH", "/"),
        "convert": os.environ.get("PHOTOPRISM_INDEX_CONVERT", "true") == "true",
        "rescan": os.environ.get("PHOTOPRISM_INDEX_RESCAN", "false") == "true",
        "skipArchived": os.environ.get("PHOTOPRISM_INDEX_SKIPARCHIVED", "false") == "true",
    }
    res = requests.post(
        f"{baseurl}/api/v1/index", json=data,
        headers=session, verify=False
    )
    res.raise_for_status()
    print(res.json())
    print("Complete")
```

**Comment by mgrove36** [comment] 2022-06-10 07:32
> I've been using `docker exec -it photoprism /photoprism/bin/photoprism import` which has stopped working with the error `stat /photoprism/bin/photoprism: no such file or directory` Does anyone know what the path for automating the import call should be now?

@SiJiL82 you can find out with `docker exec -it which photoprism`. I believe it's now `/opt/photoprism/bin/photoprism`

**Comment by azukaar** [comment] 2022-07-04 21:00
I don't really understand the lengthy conversation about not simply supporting auto-importing / auto-indexing. Out of hundreds of self hosted media solution (Movies, images, musics, etc..) Photoprism is literally is only one software that exist that does not support this... Imagine having to manually hit scan everytime your library changes in Plex, Jellyfin, Airsonic or Navidrome?
All those software managed to do this quite easily day one, because it's not complex to scan a folder periodically and check for new / missing / edited files, and most of them even get away using FS watchers optionally for faster response.

This is honestly a huuuuge let down from a UX perspective and is honestly not really justified, especially when the answer ends up being "We can't do it because XYZ... But, oh! just do it yourself with some CRON job!". If the recommendation ends up being "scan periodically" anyway you might as well implement it, no?

**Comment by ITCMD** [comment] 2022-07-04 21:18
I agree. I've made a script that indexes every 5 minutes if nobody is on one of the game servers sharing the hardware, but it's less than ideal.

Takes 1-10 minutes for a photo I take to show up in my Photoprism library. I honestly am confused why this isn't being treated as a **very** high priority issue.

**Comment by ITCMD** [comment] 2022-07-04 21:19
I think someone said that indexing should work if it's uploaded over webdav. I do want to confirm that this is not true. Photoprism will not index photos uploaded over webdev until an index command is run to docker.

**Comment by lastzero** [comment] 2022-07-04 21:28
Yes, automatic indexing and import will work if you use WebDAV. Since our users have a wide variety of file systems and operating systems, we will not release something that has only been tested with the default file system on Linux, as this could result in a huge number of support requests that we will not be able to handle. Also, we are currently working on multi-user support, which many are also waiting for. Feel free to [support us by contributing](https://docs.photoprism.app/developer-guide/) or [becoming a sponsor](https://photoprism.app/membership) if you haven't signed up yet.

**Comment by azukaar** [comment] 2022-07-04 21:57
The very vast majority of the system supports file watchers, but that's beside the point, since you don't actually need watchers to simply trigger a periodic scan right?
The "solution in the middle" / "low effort solution" I was proposing was simply having the option to have periodic scan without the sketchy CRON setup behind it.

**Comment by lastzero** [comment] 2022-07-04 22:51
Why Cron? It's a few lines of YAML and we even provide a tested example: https://dl.photoprism.app/docker/scheduler/

**Comment by ITCMD** [comment] 2022-07-05 01:27
> Yes, automatic indexing and import will work if you use WebDAV. Since our users have a wide variety of file systems and operating systems, we will not release something that has only been tested with the default file system on Linux, as this could result in a huge number of support requests that we will not be able to handle. Also, we are currently working on multi-user support, which many are also waiting for. Feel free to [support us by contributing](https://docs.photoprism.app/developer-guide/) or [becoming a sponsor](https://photoprism.app/membership) if you haven't signed up yet.

Like I said though, automatic indexing does **not** occur for me when I upload via webdav.

Is there some setting I need to enable for that to work?

**Comment by graciousgrey** [comment] 2022-07-05 04:49
@ITCMD it's triggered after a safety delay that can be configured with 

PHOTOPRISM_AUTO_INDEX

https://docs.photoprism.app/user-guide/library/originals/#automatic-indexing

In case this does not work feel free to open a bug report following this template --> https://photoprism.app/kb/reporting-bugs

**Comment by graciousgrey** [comment] 2022-07-05 05:14
We understand that it is much more convenient to set up job automation (e.g. for indexing) in the user interface than to use our examples from the documentation. The same is true for some other config options ( Even if there is not yet an issue for every option). 
We have this on our radar, and the long term goal is for the end user to be able to do as much as possible through the GUI. It's just a matter of development resources and time. 

Feel free to leave a :+1: there: https://github.com/photoprism/photoprism/issues/2495

**Comment by azukaar** [comment] 2022-07-05 10:56
> Why Cron? It's a few lines of YAML and we even provide a tested example: https://dl.photoprism.app/docker/scheduler/

Whether you use CRON or another scheduler, doesnt change the DIY aspect of it, esp. for people not using your docker-compose right away / at all.

> Feel free to leave a 👍 there: https://github.com/photoprism/photoprism/issues/2495

Done! Here's also a good inspiration. Navidrome is one of the best performing (if not the best) software in that category. This makes it much cleaner, no need for external scheduler, just a simple setup

https://github.com/navidrome/navidrome/blob/master/scheduler/scheduler.go

**Comment by lastzero** [comment] 2022-07-05 22:45
Thank you! We appreciate your feedback. As Theresa said, we are aware that many details can and should be improved. However, we cannot and should not work on everything at the same time. In general, we try to focus on features and improvements for which no other tools or workarounds exist. I fully agree with you that implementing a built-in scheduler or watcher is technically not a problem and makes perfect sense once we get to it.

Without having tested Navidrome (looks great!): Finding the right strategy for indexing photos and videos is generally much harder than for audio files, especially if you don't just have single JPEGs. Music files usually don't have extremely complex metadata split across files and formats. Also, probably 99.99% of users never edit them. While WAV could be considered a RAW format of sorts, most users only have a single file per track, which is also often nicely organized into albums. 

In practice, a single "photo" may consist of 3 or more files, some of which may be created hours later - e.g. manually in Photoshop - and may have a completely different size or use (such as JPEG, RAW, and XMP, which is not itself an image, so indexing it simply because it was uploaded or otherwise added makes little sense):
- https://docs.photoprism.app/getting-started/faq/#what-are-sidecar-files-and-where-do-i-find-them

**Comment by mfed3** [comment] 2022-08-06 15:21
I am giving you honest feedback here, not supporting an auto import feature makes this already niche product useless to 99.9% of people who would ever possibly use it. No one but a techie on linux would ever be able to figure out how to set up cron jobs, so therefore I can never recommend this software to any friends or family for it to work out of the box in a home server. Sometimes developers have no common sense in understanding the priority should be to listen to what the community wants not what you want to develop, otherwise your product will die on the vine. Due to the attitude I see here I am most likely going to be shutting down my docker container and putting this product in the "tried it, doesn't meet my needs" bin. Good luck on your next project.

**Comment by lastzero** [comment] 2022-08-06 15:37
You can use WebDAV for auto index & import:
https://docs.photoprism.app/user-guide/sync/webdav/

Background jobs for other use cases and less experienced users will be added later.

Please don't use GitHub Issues for questions and general comments. We provide other forums for that. Thank you! ❤️

**Comment by mfed3** [comment] 2022-08-06 15:43
I'm going to go ahead and call out your bull**** right now. I am essentially expressing to you as a customer that I am experiencing this same issue, and would like this feature that you closed implemented. Please don't use GitHub Issues to try to one up people and give yourself a false sense of superiority when you simply can't take the criticism. Thank you!

**Comment by heikomat** [comment] 2022-08-06 15:51
@mfed3 to be fair
1. you're not a customer, as this is free, open source software. No one owes you anything here.
2. There are other, non-closed issues regarding this topic.
3. @lastzero doesn't say things won't be improved upon. Just that these developments wont happen right now, but probably at some other time.
4.  Setting up any server-application requires some tech-skills. That's why non-techies like to use things like google photos, because that is already setup for them. If you want to host your own, you need to learn how to do that.

As @lastzero said, please use issues to discuss issues with the software. You can use for example the community chat for other questions or comments

**Comment by lastzero** [comment] 2022-08-06 16:00
@mfed3 👉 https://photoprism.app/code-of-conduct

**Comment by evertinker** [comment] 2022-08-08 20:47
> Just leave out the path.
> 
> `docker exec -it photoprism photoprism import`

is there a way to call import and specify the option of 'move' vs 'copy'? When I call it the way you describe it seems to ignore my config file/option checked in web interface and default to 'move'.

**Comment by lastzero** [comment] 2022-08-09 04:29
`docker exec -it photoprism photoprism help`

**Comment by evertinker** [comment] 2022-08-09 12:00
> 

thanks, that's what I needed!

**Comment by graciousgrey** [comment] 2022-08-12 08:44
Related open issues:
https://github.com/photoprism/photoprism/issues/2608
https://github.com/photoprism/photoprism/issues/2495

**Comment by arendtio** [comment] 2023-01-14 21:30
Thanks for the Ofelia example, I will try that 👍

In addition, I would like to express my opinion, that I would love to see some kind of scheduling of the index job as part of Photoprism. Sure, I would prefer some fancy real-time filesystem change notification system, but simply having the option to let the job run once per day would be completely sufficient. And if making it part of the software is a complete no-go please add a hint in the documentation referencing the Ofelia example.

To give some context: I have a hard drive which is my repository for all pictures from multiple devices. Some transfer their pictures automatically via ssh, others get transferred manually. The repository is also available via NFS for desktop computers and **Photoprism has read-only access**. Therefore, neither the import functionality nor the WebDAV interface seem to be viable options. Nevertheless, I would like to see yesterday's photos in Photoprism if they got transferred overnight.

**Comment by lastzero** [comment] 2023-01-14 21:36
Once we have a budget to spend, we are happy to provide all of this! 🥳

**Comment by arendtio** [comment] 2023-01-15 10:32
I ended up using [Chadburn](https://github.com/PremoWeb/chadburn) (a fork of Ofelia) because I like the label syntax better (no need for the container name; no extra config file; matches the style of the Traefik configuration) and Chadburn does "not require a dummy task on the Chadburn container", which Ofelia does... However, Chadburn uses the standard 5-part cron syntax instead of the 6-part syntax that Ofelia uses for the scheduling format. In addition, it might be helpful to know that the timings are UTC timings by default.

An example of the labels can be found here: https://www.reddit.com/r/photoprism/comments/ygug5j/scheduler_with_ofelia/

**Comment by lastzero** [comment] 2023-01-15 15:38
That could be something to contribute to the Advanced section in the Getting Started docs!
