### ISSUE TITLE
UX: Back button in "Folders" 

### ISSUE THREAD

**Issue by rosscullen** [photoprism/photoprism#1409] opened 2021-07-04 21:54 UTC
Just installed today and really impressed so far. I'm a traditional user with a 'folders and files' style workflow. 

Would be great to see a back button on the menu bar (I've mocked up an example below)

![photoprism-folders-back-button](https://user-images.githubusercontent.com/35301905/124400350-9d6cb480-dd19-11eb-9913-b43fb3c4c98d.jpg)

Could also be used in other areas. I got the idea off the Home Assistant project where it works very well on it. Hopefully other users feel similarly and the idea hasn't already been suggested. Thanks and keep up the great work :-)

**Comment by lastzero** [comment] 2021-07-05 16:46
Any reason you don't use the standard browser back button?

**Comment by rosscullen** [comment] 2021-07-05 21:46
Thats a fair and valid question... 
Personally, I think over time I have lost trust with the browser back button. eCommerce forms... eBanking... a lot of the time you loose your search results or page takes longer to re-render etc. 

I'm no UX expert/researcher but I have generally found with web applications, the navigation is contained within the application area (particularly if you're using a browser in kiosk mode or similar). And it is quicker than dragging your mouse all the way up to the top left hand corner of the screen. By having your own back button, there may also be an opportunity to used a cached version of the previous page... but I don't know enough to understand the 'behind the scenes' of the core similarities/differences.

Which also brings up another question... would you consider using breadcrumbs to navigate folders/sub-folders? Similar to $ynology Photos. 

Lastly, when you open a photo, would you consider centering the buttons that currently are in the top right (and a back button like $ynology Photos).

Appreciate you taking the time to consider my suggestions, really impressed what you have achieved to date... well done

**Comment by graciousgrey** [comment] 2021-07-06 07:05
> using it as a PWA, where's the browser back button?

That's a valid point. Using touch gestures could be an option as well.

> would you consider using breadcrumbs to navigate folders/sub-folders? Similar to $ynology Photos.

We already have breadcrumbs in Originals (see https://demo.photoprism.org/library/files/demo/Toronto ) That's the only section with subfolders.

> Lastly, when you open a photo, would you consider centering the buttons that currently are in the top right (and a back button like $ynology Photos).

We plan to build our own optimized photo viewer: https://github.com/photoprism/photoprism/issues/1307.

**Comment by rosscullen** [comment] 2021-07-07 21:07
Thanks for updates 👍🏻

**Comment by graciousgrey** [comment] 2022-10-12 17:14
The next release will come with breadcrumbs in albums/folders/calendar/states/moments that allow you to navigate back on desktop and tablet. This can be tested on our demo already: https://demo.photoprism.app/folders/arjngsl2536ivhdp/demo-german-film-award-2012

Within the PWA you can use swipe gesture to go back.

**Comment by lastzero** [comment] 2022-11-04 11:44
Nobody complained so far, so I'll move ahead and close this as done!

**Closed by lastzero** 2022-11-04 11:44 UTC
Labels: idea, please-test, ux

**Comment by Jopo-JP** [comment] 2023-03-10 01:19
> The next release will come with breadcrumbs in albums/folders/calendar/states/moments that allow you to navigate back on desktop and tablet. This can be tested on our demo already: https://demo.photoprism.app/folders/arjngsl2536ivhdp/demo-german-film-award-2012
> 
> Within the PWA you can use swipe gesture to go back.

The problem is, if you swipe back, you loose the menu on bigger screens like an tablet.

 ![Screenshot](https://i.imgur.com/CYWAI1E_d.webp?maxwidth=1520&fidelity=grand)

Tested on an iPad on Safari. You need to reload the site so the menu is back.
Same for the PWA.

**Comment by lastzero** [comment] 2023-03-10 05:46
@Jopo-JP I don't observe this on Android, is that a Safari or iOS specific problem? Does it happen in public mode only (our demo) or always, so back can never be used?

**Comment by Jopo-JP** [comment] 2023-03-10 13:05
On Android I can't say. On my phone on Android, this is not an issue, as I can press the Logo, so the menu appears from the left. Probably the same on an iPhone.

I think this will also happen on Android tablet at a specific viewpoint. Other Browser on iOS ell definitely have the same behavior since the use all the same WebKit.
Since it will Display the menu like on an bigger screen on the left site but minimized.

**Comment by lastzero** [comment] 2023-03-10 14:42
@Jopo-JP Ok, so I've tested this on Desktop Safari and on my iPad Air. Still can't reproduce the problem with our demo.

- Is it possible you have plugins installed, are using security software or a proxy that is somehow manipulating the server response?
- If you think this is a bug that needs to be fixed, we require complete technical information, including all software versions, the exact steps to reproduce it, and/or a screen recording.
- If you are not sure and want to discuss this with other users first, you can do so in [GitHub Discussions](https://github.com/photoprism/photoprism/discussions).
