### ISSUE TITLE
Image fails to upload without any error message

### ISSUE THREAD

**Issue by maxime1992** [photoprism/photoprism#3912] opened 2023-11-26 20:44 UTC
#### 1. What is not working as documented?

Says upload is successful, but the picture is never there?

#### 2. How can we reproduce it?

Try to upload this picture:

![DSCN1263](https://github.com/photoprism/photoprism/assets/4950209/0a95e72f-c602-42eb-8a23-e452a790649a)

(MD5 should be `ebaf7b60146fc62c0d1f4da1b84083c0`)

It'll upload successfully but the picture will never be visible anywhere.

#### 3. What behavior do you expect?

Have the picture correctly uploaded.

#### 4. What could be the cause of your problem?

I know that I've had issues in the past with Samsung panoramas but it was fixed by I believe applying a transformation using image magick (?) if the processing failed or something like that. Maybe this is kind of similar?

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

I have provided a file above.

#### 6. Which software versions do you use?

Build 231021-9abea5b55

OS: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-88-generic x86_64)

DB: `mariadb:10.11`

#### 7. On what kind of device is PhotoPrism installed?

Old laptop on an SSD, but probably unrelevant here.

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Unrelevant as other pics upload just fine.

**Comment by lastzero** [comment] 2023-11-26 20:59
Please check your logs, increase the log level if needed, and go through the first following checklist step by step:
- https://docs.photoprism.app/getting-started/troubleshooting/#missing-pictures

**Comment by lastzero** [comment] 2023-11-27 07:48
Works for me:

![works-for-me](https://github.com/photoprism/photoprism/assets/301686/df4cd30f-3eb3-4e91-888c-51394127462d)

@maxime1992 As detailed in the [checklist linked above](https://docs.photoprism.app/getting-started/troubleshooting/#missing-pictures), there can be many reasons why the image is not displayed as expected, e.g. it could be in *Private* or it's a duplicate. Since bug reports are not meant to find out if a problem is an actual bug in our software or has another cause, I will convert this into a discussion until it is confirmed/reproducible and it is clear that this is something that needs to be resolved in our code.

**Closed as completed** 2023-11-27 07:48 UTC
Labels: waiting, needs-analysis
