### ISSUE TITLE
Indexer: Prefer existing file names when generating titles

### ISSUE THREAD

**Issue by shzient** [photoprism/photoprism#361] opened 2020-06-18 15:21 UTC
Hello,

May I know if it is possible to allow the indexing function to use my filename as the title field of the metadata?
As some of my files have non-english characters, they are indexed with title "Unknown".

If able to retain the title as filename would be nice.

**Comment by lastzero** [comment] 2020-06-18 15:49
We are actually using the file name as title if possible. Can you give us an example?

**Comment by shzient** [comment] 2020-06-19 14:08
I am deploying photoprism using the docker-compose file

And I put my files into the default ~/Pictures/Originals directory.
Whether I index using the webgui or using the docker exec commands, the title of the pictures are not of its original filenames.
```
[root@docker Pictures]# pwd
/root/Pictures
[root@docker Pictures]# ls -l Originals/ak
total 956
-rw-r--r-- 1 root root 813009 Jun  8 23:42 えく - スカイフレア (82063926) .png
-rw-r--r-- 1 root root 161749 Jun  6 15:48 紅シャケ＠お仕事募集中 - モスティマ (81974640) .jpg
[root@docker Pictures]# ls -l Originals/al
total 1276
-rw-r--r-- 1 root root 451062 Jun 18 19:00 Cyka - swappable mag (82405706) .jpg
-rw-r--r-- 1 root root 662922 Jun 15 21:18 dishwasher1910 - Friedrich the smol (82201574) 1ページ.jpg
-rw-r--r-- 1 root root 185971 Jun 19 21:07 EaycddvU0AAfuUR.jpg

```
link to screenshot for the wrong namine
[https://i.imgur.com/6Eg0gHh.jpg](url)

**Comment by lastzero** [comment] 2020-06-20 12:47
Going to test this next week. You can see the indexed file name (and original name if any) in the "advanced" edit dialog tab on the right. File names are used as title in our public demo e.g.:

<img width="933" alt="Screenshot 2020-06-20 at 14 46 47" src="https://user-images.githubusercontent.com/301686/85202187-e7e4e400-b304-11ea-972c-cfc435f7897e.png">

**Comment by shzient** [comment] 2020-06-20 14:30
The "Name" attribute does indeed take on the filename, what is concerning is the "Title" attribute that does not follow the filename.
Wonder if it is possible to have an option to use filename as "Title"
![image](https://user-images.githubusercontent.com/67113204/85204170-23070780-b345-11ea-893a-87f6e3f8100c.png)

**Comment by lastzero** [comment] 2020-06-23 09:14
Our function that converts file names to titles works as intended. The issue here is that we sometimes use a title based on image classification if the indexer finds a (seemingly) good match.

I've change it so that existing file titles are prefered and used more often.

**Comment by shzient** [comment] 2020-06-23 15:28
that's great. thanks for the implementation.
Looking forward to try out the new function

**Comment by lastzero** [comment] 2020-06-27 12:37
I'm closing this, you can still provide feedback whenever you have time :)

**Closed by lastzero** 2020-06-27 12:37 UTC
Labels: please-test, todo
