### ISSUE TITLE
WebDAV: Uploading to Nextcloud may result in 0 byte files

### ISSUE THREAD

**Issue by RAYs3T** [photoprism/photoprism#443] opened 2020-08-04 09:00 UTC
## Preamble
Im not sure if this is something broken with my nextcloud instance or actually a bug.
So i would appreciate if someone (who has access to a Nextcloud instance) could test this.

## Problem desciption
**If you setup the upload via WebDAV to nextcloud and share one or multiple pictures, the file in nextcloud is emtpy. It basically only created the file with no contents. Therefore you can't load/display the picture.**

![image](https://user-images.githubusercontent.com/16596807/89273908-7ce73680-d640-11ea-93a6-4238e51c7689.png)

Also if you download the file it has zero bytes in it.

### Log output from PhotoPrism:
```
photoprism_1  | time="2020-08-04T08:44:36Z" level=debug msg="GET /api/v1/accounts?share=true&count=1000&offset=0 (200) [2.157622ms]"
photoprism_1  | time="2020-08-04T08:44:36Z" level=debug msg="cache hit for account-folders:1 [80.977µs]"
photoprism_1  | time="2020-08-04T08:44:36Z" level=debug msg="GET /api/v1/accounts/1/folders (200) [191.263µs]"
photoprism_1  | time="2020-08-04T08:44:43Z" level=debug msg="GET /api/v1/status (200) [77.041µs]"
photoprism_1  | time="2020-08-04T08:44:43Z" level=debug msg="POST /api/v1/accounts/1/share (200) [32.591231ms]"
photoprism_1  | time="2020-08-04T08:44:54Z" level=info msg="share-worker: uploaded //20200803-201544-Unknown-2020-10f.jpg to Edging-Technology"
```

### Log output from Nextcloud: 
```
84.46.x.x - - [04/Aug/2020:10:44:44 +0200] "PUT /remote.php/dav/files/RAYs3T//20200803-201544-Unknown-2020-10f.jpg HTTP/1.1" 401 557
80.187.x.x - - [04/Aug/2020:10:44:50 +0200] "POST /apps/text/session/sync HTTP/1.1" 200 318
84.46.x.x - - [04/Aug/2020:10:44:49 +0200] "PUT /remote.php/dav/files/RAYs3T//20200803-201544-Unknown-2020-10f.jpg HTTP/1.1" 201 -
```

**Comment by uLUViL3gCs** [comment] 2020-08-06 15:32
> So i would appreciate if someone (who has access to a Nextcloud instance) could test this.

I can confirm same behavior in my environment.


**Steps** I performed:
- PP, Settings, Backup: Add NC server
- PP, Photos: Select some random photos, Click "Share" button
- NC: the amount and names of the selected photos is created
=> The file size remains 0 KB.

![Screenshot 2020-08-06 at 17 27 17](https://user-images.githubusercontent.com/64777347/89550666-33e2de00-d80a-11ea-84ff-c832e86c63d1.png)

**Environment**:
PhotoPrism™ 200724-2859549-Linux-x86_64 
NC 19.0.1

**Comment by RAYs3T** [comment] 2020-08-11 12:32
@lastzero I guess this has to be considered a part of the MVP milestone?

**Comment by lastzero** [comment] 2020-08-11 15:44
Yes, going to look into that soon!

**Comment by lastzero** [comment] 2020-08-12 04:43
Couldn't find any issues when uploading to **Nextcloud 19.0.1**:

<img width="1019" alt="Screenshot 2020-08-12 at 06 32 00" src="https://user-images.githubusercontent.com/301686/89975306-b1bd4400-dc65-11ea-9fd4-4d27c4614cbc.png">

Also doesn't matter how many files I select, they are properly uploaded. Note that we don't use https for our local test environment, this can make a difference (connection should fail completely though).

Logs:

```
2020-08-12 06:37:10 INFO share-worker: uploaded //20190609-125732-Travelex-Currency-Exchange-2019-25w.jpg to Neon
2020-08-12 06:37:10 INFO share-worker: uploaded //20150212-031100-Theme-Park-Santa-Monica-2015-17p.jpg to Neon
```

To debug this further, we need additional information. Maybe it's just a file permission problem, either in Nextcloud or PhotoPrism?

**Comment by lastzero** [comment] 2020-08-12 04:46
Maybe this only affects certain file types or there is a request size limit in Nextcloud or a proxy in front of it?

**Comment by RAYs3T** [comment] 2020-08-12 07:35
## Test with a third-party WebDAV client works
Just to make sure this isn't caused by the Nextcloud I've used a third-party WebDAV client (Cyberduck) and tested the upload.
The upload succeeded and the file had the correct size (selected file was uploaded with the WebDAV client. others are from PP.

![image](https://user-images.githubusercontent.com/16596807/89985698-c573a500-dc7b-11ea-9bde-8f8030bd1df3.png)

## Proxy
The Nextcloud is hosted by the Apache, the this is serving the content directly without a additional proxy in front of it.

## Directory listing works, upload istelf not.
I don't think this has something to do with HTTPs. The listing of the upload directories works. You can see the folders that exists on the Nextcloud and select the correct one. I've also tried using the root directory and not a sub-folder. Same result.


## File upload call gets rejected with 401, unauthorized.
In the last test I descovered someshow that the final call that should upload the file gets **rejected with HTTP status 401**

```
95.81.15.169 - - [12/Aug/2020:09:18:35 +0200] "PROPFIND /remote.php/dav/files/RAYs3T/ HTTP/1.1" 401 557
95.81.15.169 - - [12/Aug/2020:09:18:36 +0200] "PROPFIND /remote.php/dav/files/RAYs3T/ HTTP/1.1" 207 3880
95.81.15.169 - - [12/Aug/2020:09:18:36 +0200] "PROPFIND /remote.php/dav/files/RAYs3T/Auth/ HTTP/1.1" 207 2872
95.81.15.169 - - [12/Aug/2020:09:18:37 +0200] "PROPFIND /remote.php/dav/files/RAYs3T/MobileBackups/ HTTP/1.1" 207 1173
95.81.15.169 - - [12/Aug/2020:09:18:38 +0200] "PROPFIND /remote.php/dav/files/RAYs3T/PP-Shares/ HTTP/1.1" 207 3996
95.81.15.169 - - [12/Aug/2020:09:18:38 +0200] "PROPFIND /remote.php/dav/files/RAYs3T/ShareXUploads/ HTTP/1.1" 207 34136
...
95.81.15.169 - - [12/Aug/2020:09:18:46 +0200] "PUT /remote.php/dav/files/RAYs3T//20200811-201311-Otto-Von-Bahren-Park-Hamburg-2020-1y1.jpg HTTP/1.1" 401 557
```
... so the WebDAV implementation used in PP is not checking for the status of the file upload?
```2020-08-12 09:19:03 INFO share-worker: uploaded //20200811-201311-Otto-Von-Bahren-Park-Hamburg-2020-1y1.jpg to Edging-Technology```

## Test with different file types
To rule out an error with the size or type I uploaded the same file that I've used in the upload with cyberduck, uploaded it to PP and tried to share it from there. Same result.

**Comment by lastzero** [comment] 2020-08-12 07:57
Our WebDAV upload is based on https://github.com/studio-b12/gowebdav

They also have a stand-alone command you can use for testing: https://github.com/studio-b12/gowebdav/tree/master/cmd/gowebdav

**Comment by lastzero** [comment] 2020-08-12 08:06
Looks like there is a `\` too much in the server path: `/remote.php/dav/files/RAYs3T//` ?

**Comment by RAYs3T** [comment] 2020-08-12 09:33
Yep, that's an inssue in the gowebdav client.
![image](https://user-images.githubusercontent.com/16596807/89999807-9ebf6980-dc8f-11ea-841f-94c1cc81c07f.png)


```
PS C:\development\test> $env:ROOT = "https://nc.edging-technology.net/remote.php/dav/files/RAYs3T/"
PS C:\development\test> $env:USER = "RAYs3T"
PS C:\development\test> $env:PASSWORD = "....."
PS C:\development\test> gowebdav -X PUT /webdav_test.png .\Chart_KAD.PNG
Put: .\Chart_KAD.PNG -> /webdav_test.png
```

![image](https://user-images.githubusercontent.com/16596807/89999730-7cc5e700-dc8f-11ea-9f68-c9d159192e5e.png)

I will test a little bit more and raise an issue over there. I wonder why it is working without issues for your tho...

**Comment by RAYs3T** [comment] 2020-08-12 10:36
Opened an initial issue https://github.com/studio-b12/gowebdav/issues/35

**Comment by RAYs3T** [comment] 2020-08-12 11:10
@lastzero and I have the bad feeling that this might be our issue... https://github.com/studio-b12/gowebdav/issues/28

**Comment by lastzero** [comment] 2020-08-12 11:46
Error reporting might be an issue, but what causes the error in the first place? Maybe just a small change needed as it works over here.

Are there custom settings for Nextcloud that can lead to auth issues? Plugins?

We use URL auto detection when adding the account (`http://servername/`). Manually entering the full WebDAV path may lead to a slightly different request URL.

**Comment by RAYs3T** [comment] 2020-08-12 12:25
Hmm tried it with the short (autogen) and full path. Same result.
I found some issue over at Nextcloud, but it's a little bit different (for them the file in storage is ok, while in my environment also the file stored on the spinning rust is only the encryption header, nothing else...

https://github.com/nextcloud/server/issues/21315

**Comment by lastzero** [comment] 2020-08-12 13:11
No, we don't modify originals. So no encryption whatsoever. Maybe a HTTP / Webserver issue after all, or there's a problem with the base64 encoded password in the header (there are slightly different standards for this, do you use any special characters other than a-z and 0-9?).

**Comment by RAYs3T** [comment] 2020-08-12 13:15
It's actually an app password generated by Nextcloud itself. Looks something like this `P42LX-gd4kw-Lk4Ia-9331kLa-6z7hh`

With the encryption I was referring to your test nextcloud instance Is the build-in nextcloud encryption enbaled for this?

**Comment by lastzero** [comment] 2020-08-12 13:17
Probably not... If this is not the default.

**Comment by RAYs3T** [comment] 2020-08-12 13:19
Hmm ok because in the nextcloud issue there is some replation to encryption.. @uLUViL3gCs do you have encryption enabled in your instance?

**Comment by RAYs3T** [comment] 2020-08-13 09:42
@lastzero could you try this with your build against https://try.nextcloud.com/ ? (User gets created automatically)
I was able to reproduce the same behavior there. So i can rule out issues with my instance.

I will dig around in the gowebdav later and see if i can figure out what is causing this. A quick look revealed that the status returned from the NC instance does not include any error so for, but I will dive deeper into it later.

**Comment by uLUViL3gCs** [comment] 2020-08-13 10:06
> @uLUViL3gCs do you have encryption enabled in your instance?

No, I am not using encryption as coming along, build-in by NC.

> It's actually an app password generated by Nextcloud itself. Looks something like this P42LX-gd4kw-Lk4Ia-9331kLa-6z7hh

Same here.

>  I found some issue over at Nextcloud, but it's a little bit different (for them the file in storage is ok, while in my environment also the file stored on the spinning rust is only the encryption header, nothing else...

Just to let you know that even on storage the uploaded file size is 0kB in my case.

> could you try this with your build against https://try.nextcloud.com/ ? 

Using nextcloud demo and the same local PP, I am encountering same issue (files visible, file size == 0kB).

Just for your information that I am using nginx for the local PP instance.

**Comment by RAYs3T** [comment] 2020-08-13 11:15
I'm also using nginx as revrese proxy. But it should not have any impact since the connection to Nextcloud is direct without a proxy (PP connects directly to the NC instance via HTTPS)

**Comment by lastzero** [comment] 2020-08-13 11:38
Did anyone try without app password? Do app passwords also have a username or is it just the password without username?

Nginx will limit upload size by default, we had many "bug" reports related to this when the real issue was that the files were larger than what nginx was configured for.

**Comment by lastzero** [comment] 2020-08-13 11:45
That reminds me that we run Nextcloud behind a Caddy proxy, so this might fix / modify the request in a certain way...

**Comment by lastzero** [comment] 2020-08-13 11:51
Could it be a locking issue? See https://help.nextcloud.com/t/file-is-locked-how-to-unlock/1883

**Comment by RAYs3T** [comment] 2020-08-13 11:52
app password use the same username as the login.
I'll try it without an app password in the try.nextcloud.com instance...

**Comment by uLUViL3gCs** [comment] 2020-08-13 11:54
> Did anyone try without app password?

Yes, just now on my local NC => Same result, file gets uploaded, 0kB size.

> Do app passwords also have a username or is it just the password without username?

Yes, same user name is required.

**Comment by RAYs3T** [comment] 2020-08-13 11:57
Can confirm. Using the normal login (user+pass) does also not work. Tested with try.nextcloud.com

**Comment by al13nus** [comment] 2020-08-26 16:10
Receiven this error without any uploads to NC. Having nginx-proxy between NC and PP.

`2020-08-26 18:02:04 ERRO http: write tcp 172.18.0.10:2342->172.18.0.4:44468: write: broken pipe (GET /api/v1/accounts/1/folders HTTP/1.1 Host: photoprism.***.cloud Connection: close Accept: application/json, text/plain, */* Accept-Encoding: gzip Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7 Cdn-Loop: cloudflare Cf-Connecting-Ip: 37.120.24.211 Cf-Ipcountry: DE Cf-Ray: 5c8ec3bef941fa24-AMS Cf-Request-Id: 04cd18ab580000fa24958a5200000001 Cf-Visitor: {"scheme":"https"} Connection: close Cookie: __cfduid=d67***514dfe621598042813; organizr_token_45cac20***-b810-4b8a39aba4a7=***O0gW4 Dnt: 1 Referer: https://photoprism.***.cloud/albums Sec-Fetch-Dest: empty Sec-Fetch-Mode: cors Sec-Fetch-Site: same-origin User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 X-Client-Hash: 16b801aa X-Client-Version: 200819-7b518178-Linux-x86_64 X-Forwarded-For: 37.120.24.211, 141.101.104.243 X-Forwarded-Port: 443 X-Forwarded-Proto: https X-Forwarded-Ssl: on X-Real-Ip: 141.101.104.243 X-Session-Id: 20a1f1dc40a631ba483ad56216533df9b83a9de7b33f292f ) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/render/json.go:59 (0xd5955b) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:841 (0xd5fae8) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:884 (0xd94b17) /go/src/github.com/photoprism/photoprism/internal/api/account.go:130 (0xd94a8f) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd5bc1a) /go/src/github.com/photoprism/photoprism/internal/server/recovery.go:32 (0xdf14cd) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd5bc1a) /go/src/github.com/photoprism/photoprism/internal/server/logger.go:18 (0xdf0ff9) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd5bc1a) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0xd65c39) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xd6532c) /usr/local/go/src/net/http/server.go:2843 (0x7c8162) /usr/local/go/src/net/http/server.go:1925 (0x7c386c) /usr/local/go/src/runtime/asm_amd64.s:1374 (0x477f80)`

**Comment by lastzero** [comment] 2020-08-28 10:03
This seems to be the only remaining, unfixed bug. I'll take a look at this again using the Nextcloud versions you've been testing with...

**Comment by lastzero** [comment] 2020-08-28 11:00
So I've tested uploading to the official Nextcloud demo using the Mac OS Finder. It has the exact same problem, no file can be uploaded:

![Screenshot 2020-08-28 at 12 39 03](https://user-images.githubusercontent.com/301686/91552135-9459cc80-e92b-11ea-8811-37b61fab4bf3.png)

![Screenshot 2020-08-28 at 12 39 20](https://user-images.githubusercontent.com/301686/91552133-93c13600-e92b-11ea-8a63-81bb5b8b0575.png)

Small files don't cause an error, but they also seem empty:

![Screenshot 2020-08-28 at 12 55 35](https://user-images.githubusercontent.com/301686/91553609-fc111700-e92d-11ea-9d7e-f71ebcd19f93.png)


My local instance works perfectly using those docker-compose.yml settings:

```
  nextcloud:
    restart: unless-stopped
    image: nextcloud
    ports:
      - 8080:80
    depends_on:
      - nextcloud-db
    environment:
      MYSQL_HOST: nextcloud-db
      MYSQL_PASSWORD: xxx
      MYSQL_DATABASE: xxx
      MYSQL_USER: xxx
    volumes:
      - "./nextcloud/files:/var/www/html"
```

I would assume the Nextcloud Demo (and maybe some user instances?) are configured in a way that prevents WebDAV uploads for security or other reasons. Or their implementation is not fully standards compatible unless both, Mac OS and our Go client, are not compatible and only Nextcloud is - which I think is less likely, but who knows?

**Comment by lastzero** [comment] 2020-08-28 13:15
Maybe https://sabre.io/dav/clients/finder/ leads in the right direction:

> Finder is OS X's built-in WebDAV client. It's been around for ages, and it's pretty stable.
> 
> Your server must have Locking support in order to allow a user to make modifications.
> 
> If the server does not supports locks, Finder will operate in read-only mode.
> 
> Finder uses Transfer-Encoding: Chunked in PUT request bodies. This is a little used HTTP feature, and therefore not implemented in a bunch of webservers. The only server I've seen so far that handles this reasonably well is Apache + mod_php. Nginx and Lighttpd respond with 411 Length Required, which is completely ignored by Finder. This was seen on nginx 0.7.63. It was recently reported that a development release (1.3.8) no longer had this issue.
> 
> When using this with Apache + FastCGI PHP completely drops the request body, so it will seem as if the PUT request was succesful, but the file will end up empty.

**Comment by lastzero** [comment] 2020-08-29 08:37
If you check this code, it looks very much like Go sends a `Transfer-Encoding: chunked` header too:

https://golang.org/src/net/http/transfer.go

They only way that can eventually be prevented is if the client knows the ContentLength before sending bytes.

**Comment by RAYs3T** [comment] 2020-09-01 12:12
Since we know what images we're about to upload we have that size, don't we?

**Comment by lastzero** [comment] 2020-09-01 12:15
Right, I wrote eventually. Doesn't mean that actually works or I know exactly how to implement it using the existing library and Go http client.

**Comment by lastzero** [comment] 2020-09-01 13:41
Best way to fix this would be to use mod_php with Apache for Nextcloud WebDAV. Then you're also compatible with Mac OS. Is that possible?

**Comment by RAYs3T** [comment] 2020-09-01 19:00
Hmm I'm already using an apache as proxy (with https://httpd.apache.org/docs/2.4/mod/event.html) since the performance with mod_php itself isn't great. I could try nginx instead.

**Comment by lastzero** [comment] 2020-09-01 19:05
Nginx might work according to some reports, would be great if you can test it!

**Comment by RAYs3T** [comment] 2020-09-01 20:57
Did move my instance to nginx. Same issue.
Uploaded file:
![image](https://user-images.githubusercontent.com/16596807/91905193-73380980-eca6-11ea-9775-ea730cdcc5b7.png)

Nginx logs:
```
2a04:4540:6a25:5e50:8cb:a962:7a2:5ee4 - RAYs3T [01/Sep/2020:22:55:32 +0200] "PROPFIND /remote.php/dav/files/RAYs3T/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Windows) mirall/3.0.0stable-Win64 (build 20200811) (Nextcloud)"
127.0.0.1 - - [01/Sep/2020:22:55:32 +0200] "GET /server-status?auto HTTP/1.1" 404 162 "-" "-"
2a04:4540:6a25:5e50:8cb:a962:7a2:5ee4 - - [01/Sep/2020:22:55:33 +0200] "GET /api/mmr/overview HTTP/2.0" 200 42 "https://playcheck.siege-insights.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0"
149.224.33.109 - - [01/Sep/2020:22:55:34 +0200] "PUT /remote.php/dav/files/RAYs3T//20200829-123114-Markmannsgasse-Cologne-2020-1l8.jpg HTTP/2.0" 401 557 "-" "Go-http-client/2.0"
149.224.33.109 - RAYs3T [01/Sep/2020:22:55:34 +0200] "PUT /remote.php/dav/files/RAYs3T//20200829-123114-Markmannsgasse-Cologne-2020-1l8.jpg HTTP/2.0" 201 0 "-" "Go-http-client/2.0""
```

PP logs:
```
time="2020-09-01T20:55:32Z" level=debug msg="GET /api/v1/accounts?share=true&count=1000&offset=0 (200) [859.533µs]"
time="2020-09-01T20:55:32Z" level=debug msg="cache hit for account-folders:3 [46.932µs]"
time="2020-09-01T20:55:32Z" level=debug msg="GET /api/v1/accounts/3/folders (200) [121.657µs]"
time="2020-09-01T20:55:34Z" level=debug msg="POST /api/v1/accounts/3/share (200) [14.576387ms]"
time="2020-09-01T20:55:34Z" level=info msg="share-worker: uploaded //20200829-123114-Markmannsgasse-Cologne-2020-1l8.jpg to Edging-Technology"
```

**Comment by RAYs3T** [comment] 2020-09-01 21:03
Also tried it with the nginx option `chunked_transfer_encoding on;`, no difference :(

**Comment by lastzero** [comment] 2020-09-02 06:29
Did you follow the advice on https://serverfault.com/questions/408125/enabling-chunked-uploading-in-nginx?

> According to Ubuntu's change log the chunkin module was added in 1.1.8 so 1.1.9 in 12.04 should have it. The nginx wiki explains the chunkin module in detail, but it works by replacing the 411 Length Required error page with a command that resumes the request:
> ```
> chunkin on;
> 
> error_page 411 = @my_411_error;
> location @my_411_error {
>     chunkin_resume;
> }
> ```
> This should be set up in the server block.

**Comment by RAYs3T** [comment] 2020-09-02 10:50
Finally - This did the trick! You've to enable `fastcgi_request_buffering = on`  and it works.

**Comment by lastzero** [comment] 2020-09-02 11:08
Excellent, so the only thing we need to do is add specific docs for Nextcloud users?

**Comment by RAYs3T** [comment] 2020-09-02 11:15
Yes. I guess this will be enough.
Kinda sad that it isn't working with apache on the other hand (maybe there is something similar you can configure..) 

For me it's fine since I wanted to switch to Nginx anyways... :) 


Setting the option only for the webdav routes is a good idea. Will change that in my configuration.

**Comment by uLUViL3gCs** [comment] 2020-09-02 12:05
> Finally - This did the trick! You've to enable `fastcgi_request_buffering = on` and it works.

Just to let you know that the same is true for my instance; changing
`fastcgi_request_buffering off;`
to
`fastcgi_request_buffering on;`
lets the photo being uploaded in full size:
![Screenshot 2020-09-02 at 13 59 58](https://user-images.githubusercontent.com/64777347/91978788-04e65c00-ed25-11ea-84d0-f21224fded6f.png)

**Comment by deajan** [comment] 2020-09-04 07:47
Adding my grain of salt.
I experience same issues of 0 bytes files using the WebDAV implementation of a Canon ImageRunner Advanced printer/scanner (C5250 model).
I'm running PHP 7.4.10/Apache 2.4.36/NC 19.0.2, no reverse proxy.
I've tried to switch from `php-fpm` to `mod_php` (change the MPM event to prefork and check that php.conf file exists) so I can outrule any proxy related issues.

I can indeed upload via CURL using ` curl -X PUT -T ./test.pdf --user Scanner:myscannerpassword --header "Transfer-Encoding: chunked" https://cloud.mynextcloud.tld/remote.php/dav/files/Scanner/scan.pdf`

**Strange enough, I found a way to make my uploads work:**
Using this path fails:
`https://cloud.mynextcloud.tld/remote.php/dav/files/username/MYFOLDER`

Using this path works:
`https://cloud.mynextcloud.tld/remote.php/webdav/MYFOLDER`

The latter still creates 0 byte size files in the GUI, but this time, the file is actually transfered, and exists with a real size in the data directory.
The 0 byte file in GUI only (when the file has a real size) is another problem seen here  https://github.com/nextcloud/server/issues/21315

Hope this helps someone.

**Comment by kesselb** [comment] 2020-09-04 08:35
Some more bug reports:

https://bz.apache.org/bugzilla/show_bug.cgi?id=57087
https://bugs.php.net/bug.php?id=60826

**Comment by deajan** [comment] 2020-09-04 09:58
@kesselb Does indeed explain the php-fpm problem that gets resolved by using mod_php ;)
 Doesn't explain the problem depening on `remote.php/dav/files/username` vs `remote.php/webdav` problem, neither the 0 sized in DB.

What's the difference between dav and webdav URIs ?

**Comment by kesselb** [comment] 2020-09-04 10:00
@deajan wrong repository as your problem/question is not related to photoprism ;)

**Comment by deajan** [comment] 2020-09-04 10:37
@kesselb Ahem... yes ;) Sorry for the noise

**Comment by deajan** [comment] 2020-09-15 08:03
FYI, here's the explanation and possible solutions https://trac.cyberduck.io/wiki/help/en/howto/mount/issues/fastcgi

**Comment by ArtNow198** [comment] 2021-04-26 03:32
> ## Preambuła
> Nie jestem pewien, czy jest to coś zepsutego w mojej instancji nextcloud, czy w rzeczywistości jest to błąd.
> Byłbym więc wdzięczny, gdyby ktoś (mający dostęp do instancji Nextcloud) mógł to przetestować.
> 
> ## Opis problemu
> **Jeśli skonfigurujesz przesyłanie przez WebDAV do nextcloud i udostępniasz jedno lub wiele zdjęć, plik w nextcloud jest pusty. Zasadniczo utworzył tylko plik bez zawartości. Dlatego nie możesz załadować / wyświetlić obrazu.**
> 
> ![wizerunek](https://user-images.githubusercontent.com/16596807/89273908-7ce73680-d640-11ea-93a6-4238e51c7689.png)
> 
> Również jeśli pobierzesz plik, będzie zawierał zero bajtów.
> 
> ## Dzienniki
> ### Dane wyjściowe dziennika z PhotoPrism:
> ```
> photoprism_1  | time="2020-08-04T08:44:36Z" level=debug msg="GET /api/v1/accounts?share=true&count=1000&offset=0 (200) [2.157622ms]"
> photoprism_1  | time="2020-08-04T08:44:36Z" level=debug msg="cache hit for account-folders:1 [80.977µs]"
> photoprism_1  | time="2020-08-04T08:44:36Z" level=debug msg="GET /api/v1/accounts/1/folders (200) [191.263µs]"
> photoprism_1  | time="2020-08-04T08:44:43Z" level=debug msg="GET /api/v1/status (200) [77.041µs]"
> photoprism_1  | time="2020-08-04T08:44:43Z" level=debug msg="POST /api/v1/accounts/1/share (200) [32.591231ms]"
> photoprism_1  | time="2020-08-04T08:44:54Z" level=info msg="share-worker: uploaded //20200803-201544-Unknown-2020-10f.jpg to Edging-Technology"
> ```
> 
> ### Dane wyjściowe dziennika z Nextcloud:
> ```
> 84.46.x.x - - [04/Aug/2020:10:44:44 +0200] "PUT /remote.php/dav/files/RAYs3T//20200803-201544-Unknown-2020-10f.jpg HTTP/1.1" 401 557
> 80.187.x.x - - [04/Aug/2020:10:44:50 +0200] "POST /apps/text/session/sync HTTP/1.1" 200 318
> 84.46.x.x - - [04/Aug/2020:10:44:49 +0200] "PUT /remote.php/dav/files/RAYs3T//20200803-201544-Unknown-2020-10f.jpg HTTP/1.1" 201 -
> ```

**Comment by graciousgrey** [comment] 2021-11-02 11:10
As this is mentioned in our docs (https://docs.photoprism.org/user-guide/settings/sync/). Can we close this issue or is there something left todo? @lastzero

**Closed** 2023-02-22 21:57 UTC
Labels: enhancement, docs 📚
