### ISSUE TITLE
Photoprism deducing location without Exif information. How?

### ISSUE THREAD

**Issue by dddddddavid** [photoprism/photoprism#416] opened 2020-07-22 14:29 UTC
I'm taking photos on a OnePlus One running Ubuntu Touch. This does not support geotagging.

On upload to photoprism (through nextcloud), the photo is titled [My Location] / United Kingdom / 2020. 

Looking back through my gallery, it seems to have been doing this for at least a month, and in the Photoprism 'Detail' section, I'm getting Latitude 0 Longitude 0.

Where is it getting my location information from? It's precise to an area corresponding to 15 miles long and 7 miles wide.

---

This is the complete Exiftool dump of the copy downloaded from my photoprism instance:

ExifTool Version Number         : 11.88
File Name                       : 20200722-140348-[Where-I-Live]-United-Kingdom-2020-24f.jpg
Directory                       : .
File Size                       : 2.1 MB
File Modification Date/Time     : 2020:07:22 15:12:22+01:00
File Access Date/Time           : 2020:07:22 15:12:22+01:00
File Inode Change Date/Time     : 2020:07:22 15:12:38+01:00
File Permissions                : rw-rw-r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Big-endian (Motorola, MM)
Make                            : OnePlus
Camera Model Name               : OnePlus One
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Y Cb Cr Positioning             : Centered
Exposure Time                   : 1/33
ISO                             : 1600
Exif Version                    : 0220
Date/Time Original              : 2020:07:22 14:03:48
Create Date                     : 2020:07:22 14:03:48
Components Configuration        : Y, Cb, Cr, -
Shutter Speed Value             : 1/33
Aperture Value                  : 2.0
Flash                           : Off, Did not fire
Focal Length                    : 3.8 mm
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 4160
Exif Image Height               : 2340
Interoperability Index          : R98 - DCF basic file (sRGB)
Interoperability Version        : 0100
Exposure Index                  : 0
Gain Control                    : None
Compression                     : JPEG (old-style)
Thumbnail Offset                : 560
Thumbnail Length                : 23350
Image Width                     : 4160
Image Height                    : 2340
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Aperture                        : 2.0
Image Size                      : 4160x2340
Megapixels                      : 9.7
Shutter Speed                   : 1/33
Thumbnail Image                 : (Binary data 23350 bytes, use -b option to extract)
Focal Length                    : 3.8 mm
Light Value                     : 3.0

And this is the exiftool dump from the original image:

ExifTool Version Number         : 11.88
File Name                       : image20200722_140348245.jpg
Directory                       : .
File Size                       : 2.1 MB
File Modification Date/Time     : 2020:07:22 15:27:05+01:00
File Access Date/Time           : 2020:07:22 15:27:05+01:00
File Inode Change Date/Time     : 2020:07:22 15:27:17+01:00
File Permissions                : rw-rw-r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Big-endian (Motorola, MM)
Make                            : OnePlus
Camera Model Name               : OnePlus One
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Y Cb Cr Positioning             : Centered
Exposure Time                   : 1/33
ISO                             : 1600
Exif Version                    : 0220
Date/Time Original              : 2020:07:22 14:03:48
Create Date                     : 2020:07:22 14:03:48
Components Configuration        : Y, Cb, Cr, -
Shutter Speed Value             : 1/33
Aperture Value                  : 2.0
Flash                           : Off, Did not fire
Focal Length                    : 3.8 mm
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 4160
Exif Image Height               : 2340
Interoperability Index          : R98 - DCF basic file (sRGB)
Interoperability Version        : 0100
Exposure Index                  : 0
Gain Control                    : None
Compression                     : JPEG (old-style)
Thumbnail Offset                : 560
Thumbnail Length                : 23350
Image Width                     : 4160
Image Height                    : 2340
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Aperture                        : 2.0
Image Size                      : 4160x2340
Megapixels                      : 9.7
Shutter Speed                   : 1/33
Thumbnail Image                 : (Binary data 23350 bytes, use -b option to extract)
Focal Length                    : 3.8 mm
Light Value                     : 3.0

**Comment by lastzero** [comment] 2020-07-22 14:32
So the title and location are correct? This is not a bug report? :D

**Comment by dddddddavid** [comment] 2020-07-22 14:37
It kind of is. Without geotagging, how does photoprism know where the photo was taken?
Magic is not an answer.

**Comment by lastzero** [comment] 2020-07-22 14:45
No magic, it's all open-source! We estimate the approximate location by looking for other photos taken at a similar time. Will be improved in future releases by configuring what cameras belong to you personally. Also we want to estimate GPS coordinates so that photos can be shown on a map.

In addition, we can use certain keywords like "London" to guess the country ("UK").

**Comment by dddddddavid** [comment] 2020-07-22 14:47
OK. Thanks a lot :+1: )

**Comment by flesser** [comment] 2020-08-09 10:58
> We estimate the approximate location by looking for other photos taken at a similar time.

...which gives a lot of false positives in my collection (actually came here to file a bug report for that):

Examples:
- I have some (manually) geotagged photos from the morning, all other photos from later the same day (same camera, but without location data) are assigned to the same location, even though they are a train ride across Germany away from that earlier location
- I take some geotagged photos somewhere on a trip, non-geotagged Photos from my partner's camera back home are assigned to that location

**Comment by Extarys** [comment] 2020-08-20 17:14
I imagine without batch editing this is cumbersome to fix if you took a lot of photos @flesser . May I ask if you manually geotagged all the pictures manually after?

**Comment by lastzero** [comment] 2020-08-20 17:21
You can simply set the real location for the first and last photo of a batch, this will fix it for all photos in between — unless you are continuously traveling and taking pictures 24/7 without GPS coordinates. In our mind, this was an unlikely scenario.

**Comment by pluja** [comment] 2020-11-02 12:24
This is an awesome feature, I hope it gets improved! Which is the time range used to consider that other photos are from the same day/location?

For what @flesser said:
> I have some (manually) geotagged photos from the morning, all other photos from later the same day (same camera, but without location data) are assigned to the same location

Maybe one should be able to choose if he wants, when manually setting a geolocation, which time range (minutes, hours, days, weeks?) from that time they want to apply that same geotags. Or maybe be able to **not apply to other photos**.

**Comment by graciousgrey** [comment] 2020-11-17 14:56
@pluja The time range considered are 24h. We will close this issue. Feel free to open a new feature request issue for editing this time range for certain locations :)

**Closed by graciousgrey** 2020-11-17 14:56 UTC
Labels: question

**Comment by Happyfeet01** [comment] 2021-01-25 11:54
have updated to the Preview Version. But where are these Option?
