### ISSUE TITLE
Live Photos: Use HEIF to create primary JPEG instead of a MOV still image

### ISSUE THREAD

**Issue by alxjsn** [photoprism/photoprism#926] opened 2021-01-20 01:45 UTC
When media gets detected as a live photo, the thumbnail that gets generated is based on the video file and not the original photo. The quality tends to be poor and is especially noticeable when there is motion.

Here is an example of a thumbnail that looks blurry in the thumbnail:
![1611106685-select](https://user-images.githubusercontent.com/3642823/105115479-851c1c80-5a8e-11eb-937b-0972f2c80fd0.png)

What it should look like:
![1611107091-select](https://user-images.githubusercontent.com/3642823/105115642-cf050280-5a8e-11eb-8af2-192fe8cd4473.png)

Example live photo:
[live-photo.zip](https://github.com/photoprism/photoprism/files/5839637/live-photo.zip)

Can the thumbnail be based on the original photo instead of the video file?

**Comment by lastzero** [comment] 2021-01-20 07:46
Yes, you can manually select a different primary JPEG for live photos that include a HEIC image file:

![Screenshot 2021-01-20 at 08 44 31](https://user-images.githubusercontent.com/301686/105143134-bbdc4c00-5afb-11eb-94a1-9a1e5abd726c.png)

We don't do this automatically right now as it might overwrite manual changes. Going to take a look at his later.

**Comment by alxjsn** [comment] 2021-01-21 01:32
Thanks for adding this to the roadmap! How exactly do I change the the thumbnail manually/main image?

When I go into the files section of an image I don't even see a file with an `heic.jpg` extension.

![1611192700-select](https://user-images.githubusercontent.com/3642823/105264039-21f5bd00-5b56-11eb-9e93-08c4ae1d1b07.png)

**Comment by lastzero** [comment] 2021-01-21 08:43
Maybe you need to reindex. This was added recently.

**Comment by joachimtingvold** [comment] 2022-01-06 12:04
I have no `<name>.heic.jpg` either, and I'm running `latest`. All my photos have been imported+indexed on `211215-93b26f19`. I assume "this was added recently" (from Jan 2021) should be present in that version? I.e. that it should create `<name>.heic.jpg`, even though it selects `<name>.mov.jpg` as primary (which is fixed in `preview` now).

**Comment by lastzero** [comment] 2022-01-06 13:43
We suggest testing / reindexing with the upcoming UPDATE. Just pushed a few more improvements.

**Comment by lastzero** [comment] 2022-01-06 14:26
I think what I meant a year ago is that the creation of JPEGs from HEIFs was added recently, not the creation of individual JPEGs for every other file type in a stack. However, I do recall reports from users who said they had multiple JPEGs, but the best one was not used as the primary one.

In January 2021 I may not have known that we also need to change the priority of the main file type from Video to HEIF, which we did 3 days ago. We didn't have a recent iPhone for testing and from what I remember, the test files we received at that time had the same resolution in the related MOV and HEIC files.

We're both exhausted after dealing with all your bug reports and edge cases. Maybe you can search GitHub for related issues and comments? Running the convert command may help, for example.

**Comment by joachimtingvold** [comment] 2022-01-06 14:46
> I think what I meant a year ago is that the creation of JPEGs from HEIFs was added recently, not the creation of individual JPEGs for every other file type in a stack.

In other words, "create `<file>.heic.jpg` from HEIC" should, by that definiton, work in `latest`? Or am I misunderstanding you? I'm just trying to figure out if I have an edgecase here or not.

I know the "use best stacked photo as primary" is only fixed in `preview`.

Just trying to understand what would be the expected outcome of HEICs in `latest`. As far as I understand you, HEICs should generate the following stack using `latest`:
```
<name>.heic
<name>.heic.jpg
<name>.mov
<name>.mov.jpg (primary)
```

While in `preview` it should generate the following;
```
<name>.heic
<name>.heic.jpg (primary)
<name>.mov
<name>.mov.jpg
```

In my case, using `latest`, I get the following for my HEICs;
```
<name>.heic
<name>.mov
<name>.mov.jpg (primary)
```

> In January 2021 I may not have known that we also need to change the priority of the main file type from Video to HEIF, which we did 3 days ago. We didn't have a recent iPhone for testing and from what I remember, the test files we received at that time had the same resolution in the related MOV and HEIC files.

Sure. Which is why I'm somewhat confused, since I do not have the `<name>.heic.jpg` at all (same as OP pointed out in Jan 2021).

> We're both exhausted after dealing with all your bug reports and edge cases.

Don't burn yourselves out. As I've already said before; I have no expectation from anyone to fix things. Most issues I've seen here on GitHub has been of the "very nice to have" or "minor annoyance", so I'd say that PP in general is in a good state (i.e. you shouldn't feel like you have to fix everything "yesterday" (-: ).

> Maybe you can search GitHub for related issues and comments? Running the convert command may help, for example.

Already done that, which lead me to this issue. `convert` is running successfully via daily ofelia task. Same with `index --cleanup`.

**Comment by lastzero** [comment] 2022-01-06 15:07
It's possible that import only creates the primary JPEG while index creates both.

**Comment by lastzero** [comment] 2022-01-06 15:23
> In other words, "create `<file>.heic.jpg` from HEIC" should, by that definiton, work in `latest`? Or am I misunderstanding you? I'm just trying to figure out if I have an edgecase here or not.

Yes, unless users have a custom runtime environment without HEIF support.

This issue here is specifically for Live Photos with multiple related non-JPEG files.

> In my case, using `latest`, I get the following for my HEICs;

Index or import? Does a full rescan create a JPEG for the other file? You can limit it to specific folders for testing.

> Don't burn yourselves out.

No worries... just saying that we can't answer detailed technical questions right now and might also not remember to come back to them at a later time. Aside from that, we appreciate your feedback!

Feel free to create follow up issues if you need additional improvements. If it's just "nice to have" and you don't really need it, I suggest we focus on multi-user without iterating further.

**Closed** 2022-01-07 10:52 UTC
Labels: idea, done, ux

**Comment by joachimtingvold** [comment] 2022-01-08 17:23
After doing a force re-index, it now seems to correctly create `<name>.heic.jpg`, and sets that as a primary, for live photos.

However, I've observed two things so far;

1) Old `<name>.mov.jpg` files are not removed. A fresh indexed live photo only contains `<name>.heic`, `<name>.heic.jpg` and `<name>.mov`. Maybe purging old `<name>.mov.jpg` makes sense, since they are no longer used/needed?

2) The current commits does not seem to resolve stacked live photos. I have several "double" live photos that has been automatically stacked, and they now look like this;

![image](https://user-images.githubusercontent.com/359918/148653467-868e7a3e-a73a-4597-ae57-90a860b3944a.png)

... where `20191210_213735_04E22393.mov.jpg` is the primary photo. It has successfully created `<name>.heic.jpg` for the primary stack photo, but it is not set as primary for the stack.

Also, if I at some point wanted to change the primary photo for a stacked live photo, it currently does not seem to create `<name>.heic.jpg` for the secondary photos. From the screenshot above, `20191210_213735_59BB2523.heic.jpg` is missing.

**Comment by lastzero** [comment] 2022-01-08 17:27
Indexing won't delete files and won't break up existing stacks. You need to do this manually. The potential damage in case of a bug would be far too big.

**Comment by lastzero** [comment] 2022-01-08 17:28
Also some users may prefer the video still, for example because it reduces flickering on mouse over. It's not up to us to decide this.

**Comment by joachimtingvold** [comment] 2022-01-08 17:34
> Indexing won't delete files and won't break up existing stacks. You need to do this manually. The potential damage in case of a bug would be far too big.

I did not expect it to either. It was just an observation that new live photos only had 3 files, but old ones have 4 (due to the extra `<name>.mov.jpg`). If that's "working as intended", it's fine by me.

> Also some users may prefer the video still, for example because it reduces flickering on mouse over. It's not up to us to decide this.

But it no longer creates `<name>.mov.jpg` for live photos, so that's not really an option longer anyways?

**Comment by joachimtingvold** [comment] 2022-01-08 17:38
Actually, I have found several "single" live photos with `<name>.heic.jpg` created, but it's not set as primary. The old `<name>.mov.jpg` is still the primary. Are the commited changes meant to address exisiting photos, or just new ones? Does it require more than just `index -f` to resolve, if it's supposed to fix existing photos as well?

![image](https://user-images.githubusercontent.com/359918/148654124-a73ed967-857f-48d8-81e4-d2bce0f18b76.png)
(`20200715_121819_9D882AA0.mov.jpg` is set as the primary for this one)

**Comment by lastzero** [comment] 2022-01-08 17:43
Nope, just new ones. There's also a rule that assumes videos don't need a still extracted if there already is an image in the stack. But it doesn't mean existing stills will be deleted automatically.

**Comment by lastzero** [comment] 2022-01-08 17:45
Besides, you could also have created JPEGs manually. It's not feasible to track the origin and change history of all files for now.

**Comment by joachimtingvold** [comment] 2022-01-08 17:48
And what would be the proper procedure to get `<name>.heic.jpg` set as primary for live photos for existing photos without nuking the database? I guess I can fix it manually, but.

**Comment by lastzero** [comment] 2022-01-08 17:52
SQL UPDATE for now 😜

**Comment by joachimtingvold** [comment] 2022-01-08 17:53
Haha. OK. Maybe one future change would be to differentiate between "automatically set `file_primary`" and "manually set `file_primary`"?  That way, future changes to logic that dictates "what photo is primary" could be automatically be updated to whatever is default, unless someone has manually overridden the primary for a stack (and in those cases, we could provide a "force" flag to override even manually set primary).

**Comment by lastzero** [comment] 2022-01-08 18:18
Yep. Requires a schema change, so we didn't implement it this time. Will happen eventually.
