### ISSUE TITLE
Drop down menus do not disappear. 

### ISSUE THREAD

**Issue by JulianEggers** [photoprism/photoprism#1181] opened 2021-04-08 16:18 UTC
Drop down menus do not disappear when focusing other elements.
This can result in a UI like this:

![Screenshot_20210408-180920.jpg](https://user-images.githubusercontent.com/7057809/114060626-dbcb1280-9895-11eb-90dd-30384de2426a.jpg)

Chrome on Android with Photoprism opened as Pwa.

I'd suggest to remove the drop down menu whenever the user selects other UI elements.

**Comment by kyeb** [comment] 2021-04-09 04:56
Looks like this is a bug in Vuetify. [This codepen](https://codepen.io/kyeb/pen/YzNEjdy) reproduces the problem if you use Chrome mobile (including using the device switcher thingy in Chrome devtools on desktop).

It looks like this is fixed in the latest version of Vuetify, though (see [this codepen](https://codepen.io/kyeb/pen/zYNPLee)). I could give upgrading a shot, unless there's a particular reason PhotoPrism is still on Vuetify 1.5?

**Comment by lastzero** [comment] 2021-04-13 18:09
We use Vuetify 1.5 as upgrading takes a lot of time and there are many other open issues. We don't think this should be the first priority and will do it when we have time. If you sponsor our work, we can eventually hire developers and work faster. Thank you very much! ❤️

**Comment by benmccann** [comment] 2021-04-24 04:08
This is also happening with the main nav, which is really driving me crazy. When I click the hamburger menu, the nav opens. However, there is then no way to close the nav. I am forced to navigate to another page

**Comment by lastzero** [comment] 2021-04-24 04:27
Closes when you click on the semi transparent overlay outside the menu (main app area). An edge case might be when the phone screen is so small that only the menu fits on it. Dropdowns close in a similar way and don't stay open for me. Again, there might be edge cases with touching / clicking certain other elements that have custom event handlers.

**Comment by benmccann** [comment] 2021-04-24 04:52
That's how I expected it to work, but it's not working for me. I'd installed the PWA for http://demo.photoprism.org/ using Chrome on Android. I'm not sure what the issue is, but it's not due to the presence of other elements because it happens on the video tab where there's only 1 video so the space not covered by the menu is entirely blank

**Comment by lastzero** [comment] 2021-04-24 06:59
I'm mainly using the PWA with Chrome on Android 10. Also tested it on iPhone & iPad. No issues at all. Happy to provide a fix once we figure out why / when this happens. Maybe there's another overlay blocking it?

**Comment by lastzero** [comment] 2021-04-25 09:15
Did you test this using our latest release from April 22nd? Updated a bunch of dependencies.

**Comment by lastzero** [comment] 2021-05-05 11:44
Is this still happening after upgrading to our latest release? If not, we'd like to close this issue.

**Comment by benmccann** [comment] 2021-05-05 23:34
The issue I reported is working now. I'm not sure about the issue that was originally raised here. Sorry if I confused the thread by introducing a new issue.

**Comment by kyeb** [comment] 2021-05-06 00:20
The issue as I reproduced it seems to be fixed now as well!

**Comment by graciousgrey** [comment] 2021-05-06 05:50
Thanks for testing :)

**Closed by graciousgrey** 2021-05-06 05:50 UTC
Labels: bug, waiting
