### ISSUE TITLE
Adding a large number of photos to an Album (with SQLite) leads to too many SQLI variables error

### ISSUE THREAD

**Issue by andir** [photoprism/photoprism#481] opened 2020-08-23 18:01 UTC
When adding a few hundred pictures to a gallery at the same time I'm facing `album: too many SQL variables` errors. IIRC SQLite has a limit of ~1k variables (placebolders?) in queries and thus we should probably do some batching when adding large amounts of images to an Album.

This was reported to me from one of the users of my photoprism instance. I might be missing relevant details. Let me know if there is something specific that you want to know.

**Comment by lastzero** [comment] 2020-08-23 18:06
Wow, OK. Not sure what the limit is but must be a lot! 😂

If course we can use a loop to add them in batches.

**Comment by lastzero** [comment] 2020-08-28 09:09
So the problem is probably not adding the photos to albums, which doesn't happen in one single big query, but the query that returns the final selection. Note that users can't just select single Photos, but also Files, Albums, Labels and Places. From all of this, we create a list of actual photo IDs to add.

I'm not sure how useful albums with thousands of photos - that you've been selecting quickly in one batch - are, maybe better use a dynamic search filter for that? We'll be adding a UI for this ASAP. Already works in the backend, that's how moments are created. To make this more clear, I've added a limit of 500 items for all clipboards.

**Comment by lastzero** [comment] 2020-09-03 06:27
Works for me, so I'm closing this since there was no more feedback:

![Screenshot 2020-09-03 at 08 24 56](https://user-images.githubusercontent.com/301686/92078744-12e8bb00-edbf-11ea-9813-5ff1210294b9.png)

**Closed by lastzero** 2020-09-03 06:27 UTC
Labels: bug, please-test
