### ISSUE TITLE
Category: Improve photos and video UX

### ISSUE THREAD

**Issue by dmitry-brazhenko** [photoprism/photoprism#3033] opened 2022-12-26 11:08 UTC
**Describe what problem this solves and why this would be valuable to many users**

1. I would like to explore location of a particular photo/video
2. I would like to be able to play videos "smoothier"

**Describe the solution you'd like**

1. Add optional right bar where photo details can be viewed (similar to google photos). Screen is below
2. Once I flip through photos/videos I would like just press button on video preview and play it. 

**Sreens:**
1. Right bar with photo details example from google photos:
![image](https://user-images.githubusercontent.com/61410067/209541872-b6a78e8b-9290-4449-916e-dbace0703594.png)
I would be happy to see such in Photoprism

2. "Problem" with video preview. 

How it works in photoprism now
step 1:
![image](https://user-images.githubusercontent.com/61410067/209541994-8ca18a48-2694-40b2-91eb-40ae487a4b84.png)

step2:
new window appears
![image](https://user-images.githubusercontent.com/61410067/209542165-cd24b89d-5632-4b92-99a4-822bf274146d.png)

and if i press "left" or "right" nothing will happen. 

I would like to make it similar to google photos, where video is inlined and i can press left/right button to jump to the next/previous media file

![image](https://user-images.githubusercontent.com/61410067/209542313-5c2aaf04-2740-4644-a29a-14cf448408e1.png)

**Comment by dror3go** [comment] 2022-12-28 11:54
Is that a duplicate of #1307?

**Comment by dmitry-brazhenko** [comment] 2022-12-29 15:27
Generally, seems yes . But probably we can save some details such as 'show photo location' in the preview

**Comment by graciousgrey** [comment] 2022-12-30 08:06
I will close this one as duplicate of #1307. @dmitry-brazhenko feel free to add your screenshots to the mentioned issue :)

**Closed as completed by graciousgrey** 2022-12-30 08:06 UTC
Labels: duplicate
