### ISSUE TITLE
iOS live photos uploaded via photosync.  mov.jpg is set to primary, not HEIC.jpg

### ISSUE THREAD

**Issue by ferronand** [photoprism/photoprism#1596] opened 2021-10-04 22:06 UTC
When uploading to originals folder via photosync, a jpg of the live photo is created(filename.mov.jpg) based on the first frame of the live photo, and a jpg of the actual photo is created(filename.HEIC.jpg).  The mov.jpg is then set to primary in the stack.  How can we instead make sure the HEIC.jpg is set as primary?  Changing the primary manually is not an option for me, as I have about 2 thousand photos.

**Comment by graciousgrey** [comment] 2021-10-05 08:16
Could you send us an example file for testing to hello@photoprism.app ?

**Comment by lastzero** [comment] 2021-10-05 18:34
Duplicate of #926

**Closed as completed by lastzero** 2021-10-05 18:34 UTC
Labels: bug, duplicate

**Comment by lastzero** [comment] 2021-10-05 18:38
We'll implement this, but I need to look after a few other important issues first. In particular multi-user support as everyone and his dog is waiting for this. Setting the best available JPEG can easily be implemented later based on the existing index. In addition, we need to set a flag when the primary was changed manually so that PhotoPrism doesn't change it automatically. Not everyone might want to use the file with the highest resolution by maybe a crop.
