### ISSUE TITLE
Performance issues on new faces

### ISSUE THREAD

**Issue by amgschnappi** [photoprism/photoprism#2283] opened 2022-04-26 22:00 UTC
I have at least 90K+ photos. After months of indexing, it shows more than 2k new faces. Unfortunately, no browser is capable of loading this page on my modest 10 years old laptop.
Is there any way to increase performance?

**Comment by lastzero** [comment] 2022-04-27 05:17
Of course the performance CAN be improved. The question is what it costs compared to better hardware. Every vendor has hardware requirements and so do we... 

Besides, 2000 face clusters seems to be way too much unless you only have portraits/faces and from each person many shots? After MONTHS of indexing also sounds much too long, should be days max. Does that mean, you never updated? Our latest build should already be faster.

**Comment by lastzero** [comment] 2022-04-27 11:14
I'm moving this to GitHub Discussions as it needs a root cause and feasibility analysis before it can be addressed. Our team is constantly working to improve performance based on our own and our users' experience on (probably) more modern hardware. I've also added a general note to our [FAQs in Getting Started](https://docs.photoprism.app/getting-started/faq/#can-you-improve-performance-when-using-older-or-otherwise-slow-hardware).

**Closed as completed** 2022-04-27 11:15 UTC
Labels: idea, needs-analysis
